.isort.cfg
@cjdsellers 
Stupid syntax error on my part. I wrote it in the syntax of `pyproject.toml`. Didn't realize that `.isort.cfg` has its own format.
Discovered when I was running `isort` directly. Not sure why it wasn't throwing errors during the pre-commit run.
As an aside, I've done some testing around on this and it seems to work fine for Cython.
Will definitely create a chunderous PR if you let it run across all files though.
=> fix syntax of .isort.cfg

examples/strategies/ema_cross.py, examples/strategies/ema_cross_filtered.py, nautilus_trader/__init__.py, nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/execution.pxd, nautilus_trader/backtest/execution.pyx, nautilus_trader/common/data.pyx, nautilus_trader/common/execution.pyx, nautilus_trader/common/factories.pxd, nautilus_trader/common/factories.pyx, nautilus_trader/live/execution_engine.pyx, nautilus_trader/live/node.pyx, nautilus_trader/model/c_enums/order_type.pxd, nautilus_trader/model/order.pxd, nautilus_trader/model/order.pyx, nautilus_trader/serialization/serializers.pyx, nautilus_trader/trading/strategy.pxd, nautilus_trader/trading/strategy.pyx, nautilus_trader/trading/trader.pxd, nautilus_trader/trading/trader.pyx, tests/integration_tests/test_live_execution.py, tests/test_kit/strategies.py, tests/unit_tests/backtest/test_backtest_execution.py, tests/unit_tests/common/test_common_execution.py, tests/unit_tests/live/test_live_execution.py, tests/unit_tests/model/test_model_order.py, tests/unit_tests/serialization/test_serialization_serializers.py, tests/unit_tests/trading/test_trading_strategy.py
- Central method for wiring up strategy
- Refactoring of various backtest execution methods
- Better handling of OCO orders
- Above fixed invalid order events
- Enhance flattening of strategy positions
- Remove StopLimitOrder (for now)
- Bump version
=> Enhancements to strategy wire up and backtest execution

nautilus_trader/indicators/max_bid_min_ask.pxd, nautilus_trader/indicators/max_bid_min_ask.pyx, tests/unit_tests/indicators/test_max_bid_min_ask.py
Indicator that tracks the max bid and min ask within a recent time window.
Uses deques to prune the collection as aggressively as possible.
I tried using `libcpp.deque` but ran afoul of trying to put cdef Python classes into it. In retrospect, of course that wouldn't work. Will keep it in my back pocket if there's a time where I need a deque that only has C primitives in it.
=> MaxBidMinAsk

nautilus_trader/analysis/performance.pyx
```
TypeError: Argument 'other' has incorrect type (expected nautilus_trader.model.objects.Money, got int)
Exception ignored in: 'nautilus_trader.analysis.performance.PerformanceAnalyzer.total_pnl_percentage'
Traceback (most recent call last):
File "/Users/youngminbae/PycharmProjects/nautilus_trader/tests/acceptance_tests/test_backtest_acceptance.py", line 81, in test_run_empty_strategy
self.engine.run(start, stop)
TypeError: Argument 'other' has incorrect type (expected nautilus_trader.model.objects.Money, got int)
```
=> Fix incorrect type error in performance analyzer.

.github/workflows/test-tag-publish.yml, .github/workflows/test.yml, docs/source/developer_guide/overview.rst, docs/source/developer_guide/testing.rst, pyproject.toml
1. Attempts to fix the test-tag-publish flow for master.
2. Enables `test` workflows for non-develop branches
3. Trims the size of the published sdist from 15mb to 200kb (by dropping docs/scripts/tests and nautilus_trader/_internal from the package).
4. Trims the size of the published MacOS wheel by 800kb (7.5mb -> 6.7mb).
I noticed that the linux wheels are much larger. Guessing it's just a byproduct of how manylinux2014 works.
I'm up for debating whether _internal should stay as part of the core shipped artifact. I'd argue that it's really big, and almost alway stale. It's really just one sliver of data that should belong in a user database. Getting it into that database probably shouldn't involve storing it in git.
=> Build cleanup

nautilus_trader/model/tick.pxd, nautilus_trader/model/tick.pyx
I think that the ability to work with a datetime without calling python methods in base classes will further add performance for calculating indicators and aggregators 
Using raw format to work with  time speeds up >  2X for simple test`s 
in more sophisticated methods, faster up to 4 X
```
%%cython --annotate
from cpython.datetime cimport datetime
from cpython.datetime cimport timedelta
from nautilus_trader.model.tick cimport Tick
from nautilus_trader.model.objects cimport Price
from nautilus_trader.model.objects cimport Quantity
from nautilus_trader.model.identifiers cimport Symbol
from nautilus_trader.model.tick cimport QuoteTick
from nautilus_trader.core.datetime cimport from_posix_ms
from nautilus_trader.core.datetime cimport to_posix_ms
from tests.test_kit.stubs import UNIX_EPOCH …
```
=> add raw unix_timestamp

nautilus_trader/model/orderbook/book.pxd, nautilus_trader/model/orderbook/book.pyx
This PR changes a couple of things to the OrderBook class
- an `apply` method to the orderbook to allow any update operation to be applied (cleans up switch states in other areas)
- changes the `__repr__` to add the last updated time and instrument_id
- blocks the `OrderBook` class from being directly instantiated, directing the user to the `create` method instead
=> Orderbook apply

nautilus_trader/adapters/betfair/common.py, nautilus_trader/adapters/betfair/parsing.py, nautilus_trader/adapters/betfair/util.py, nautilus_trader/data/socket.py, nautilus_trader/model/orderbook/book.pxd, nautilus_trader/model/orderbook/book.pyx, tests/integration_tests/adapters/betfair/test_betfair_data.py
Tiny PR:
- ensure we don't double `_process_order` in `_remove_if_exists`
- return `void` in L2OrderBook  `_process_order` to make it clear we need the functionality separate 
PR to `flake8_BLK100` branch temporarily just to ensure compare works
=> Cleanup delete path, void _process_order in L2Orderbook

nautilus_trader/adapters/ccxt/execution.pyx
Changed line 822 in CCXT Adapter to resolve binance error in issue #346. The block of code pertains to the sell order side of a stop market order.
=> changed TAKE_PROFIT to STOP_LOSS in BinanceCCXTExecutionCleint

tests/unit_tests/model/test_model_position.py, tests/unit_tests/trading/test_trading_account.py, tests/unit_tests/trading/test_trading_calculators.py, tests/unit_tests/trading/test_trading_filters.py, tests/unit_tests/trading/test_trading_portfolio.py, tests/unit_tests/trading/test_trading_strategy.py, tests/unit_tests/trading/test_trading_trader.py
For right now, only `tests/unit_tests/trading/test_trading_strategy.py` has been converted to use pytest. If the conversion is acceptable to the maintainers, I'll convert the rest on this PR.
In order to get the unit tests to run/pass, I did have to modify the `noxfile.py` `tests` session to include the `--extras ALL_EXTRAS` flag, otherwise it complained about a missing `betfairlightweight` import and probably would have complained about the other extras as well. I didn't include the `noxfile.py` changes in this PR as I wasn't sure if it was just me or actually a bug.
Pre-commit hooks were run, unit and integration tests passed. Let me know if I missed anything.
=> Convert unittest tests to pytest (tests/unit_tests/trading)

tests/unit_tests/indicators/test_ama.py, tests/unit_tests/indicators/test_atr.py, tests/unit_tests/indicators/test_base_indicator.py, tests/unit_tests/indicators/test_bid_ask_min_max.py, tests/unit_tests/indicators/test_bollinger_bands.py, tests/unit_tests/indicators/test_donchian_channel.py, tests/unit_tests/indicators/test_efficiency_ratio.py, tests/unit_tests/indicators/test_ema.py, tests/unit_tests/indicators/test_fuzzy_candlesticks.py, tests/unit_tests/indicators/test_hilbert_period.py, tests/unit_tests/indicators/test_hilbert_snr.py, tests/unit_tests/indicators/test_hilbert_transform.py, tests/unit_tests/indicators/test_hma.py, tests/unit_tests/indicators/test_keltner_channel.py, tests/unit_tests/indicators/test_keltner_position.py, tests/unit_tests/indicators/test_ma_factory.py, tests/unit_tests/indicators/test_macd.py, tests/unit_tests/indicators/test_obv.py, tests/unit_tests/indicators/test_pressure.py, tests/unit_tests/indicators/test_roc.py, tests/unit_tests/indicators/test_rsi.py, tests/unit_tests/indicators/test_sma.py, tests/unit_tests/indicators/test_spread_analyzer.py, tests/unit_tests/indicators/test_stochastics.py, tests/unit_tests/indicators/test_swings.py, tests/unit_tests/indicators/test_volatility_ratio.py, tests/unit_tests/indicators/test_vwap.py, tests/unit_tests/indicators/test_wma.py, tests/unit_tests/live/test_live_data_engine.py
The following files have been converted (29 total):
- tests/unit_tests/indicators/*.py
- tests/unit_tests/live/test_live_data_engine.py
=> Convert unittest tests to pytest (tests/unit_tests/indicators)

tests/unit_tests/analysis/test_analysis_performance.py, tests/unit_tests/analysis/test_analysis_reports.py
This pull request converts tests in the `tests/unit_tests/analysis` directory from unittest to pytest.
Let me know if you'd like me to also modify the tests to use pytest fixture functions instead of classes with a `setup` method.
Also, I've noticed that in `test_analysis_reports.py`, `self.account_id` appears unused. Should I remove it?
=> Convert analysis tests to pytest

tests/acceptance_tests/test_backtest_acceptance.py, tests/acceptance_tests/test_backtest_cached.py, tests/integration_tests/live/test_live_node.py, tests/unit_tests/backtest/test_backtest_exchange.py, tests/unit_tests/common/test_common_enums.py, tests/unit_tests/model/test_model_position.py, tests/unit_tests/trading/test_trading_filters.py
The following files have been converted (7 total):
- tests/unit_tests/acceptance_tests/*.py
- tests/unit_tests/backtest/test_backtest_exchange.py
- tests/integration_tests/live/test_live_node.py
- tests/unit_tests/trading/test_trading_filters.py
- tests/unit_tests/model/test_model/position.py
=> Convert unittest tests to pytest (misc files)

tests/integration_tests/adapters/ccxt/test_ccxt_binance_execution.py, tests/integration_tests/adapters/ccxt/test_ccxt_bitmex_execution.py, tests/integration_tests/adapters/ccxt/test_ccxt_data.py, tests/integration_tests/adapters/ccxt/test_ccxt_execution.py, tests/integration_tests/adapters/ccxt/test_ccxt_providers.py, tests/integration_tests/adapters/oanda/test_oanda_providers.py
The following files have been converted (6 total):
- tests/unit_tests/adapters/ccxt/*.py
- tests/unit_tests/adapters/oanda/*.py
=> Convert unittest tests to pytest (tests/unit_tests/adapters)

RELEASES.md, nautilus_trader/backtest/data_producer.pyx, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/exchange.pxd, nautilus_trader/backtest/exchange.pyx, nautilus_trader/common/logging.pxd, nautilus_trader/common/logging.pyx, nautilus_trader/execution/client.pyx, nautilus_trader/trading/account.pyx, tests/unit_tests/backtest/test_backtest_engine.py, tests/unit_tests/backtest/test_backtest_exchange.py, tests/unit_tests/trading/test_trading_account.py, tests/unit_tests/trading/test_trading_strategy.py
Fixes #388 
- Adds a new `setup` method to SimluatedExchange that is called after setup clocks in BacktestEngine
- Adds simple test
=> Fix SimulatedExchange generate_account_state timestamp

.pre-commit-config.yaml, examples/backtest/fx_ema_cross_audusd_bars_from_ticks.py, nautilus_trader/adapters/betfair/execution.pyx, nautilus_trader/adapters/betfair/parsing.py, nautilus_trader/model/instruments/base.pxd, nautilus_trader/model/instruments/base.pyx, nautilus_trader/model/instruments/betting.pxd, nautilus_trader/model/instruments/betting.pyx, tests/integration_tests/adapters/betfair/conftest.py, tests/integration_tests/adapters/betfair/test_betfair_backtest.py, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/integration_tests/adapters/betfair/test_betfair_execution.py, tests/integration_tests/adapters/betfair/test_betfair_providers.py, tests/integration_tests/adapters/betfair/test_kit.py, tests/integration_tests/adapters/betfair/test_orderbook.py, tests/test_kit/providers.py, tests/unit_tests/model/test_model_instrument.py, tests/unit_tests/trading/test_trading_portfolio.py
Refactor and fix a handful of things in the Betfair adapter
- Fix execution tests that were skipped
- Pull order and instrument from cache rather than computing
- Fix margins and notional value in Betting Instrument & add simple tests
- Add some more test fixtures and split BetfairTestStubs into BetfairTestStubs/BetfairDataProvider
- Add portfolio initial margin test
=> Betfair fixes

nautilus_trader/persistence/external/core.py, tests/unit_tests/persistence/external/test_core.py, tests/unit_tests/persistence/external/test_parsers.py, tests/unit_tests/persistence/test_catalog.py
Fixes a bug that was overwriting instruments when written to parquet. This was a side effect of removing code in #440
=> Fix bug in overwriting parquet instruments

nautilus_trader/persistence/catalog.py, tests/unit_tests/persistence/test_catalog.py
This PR adds a method `calc_streaming_chunks` to the `DataCatalog` for calculating start/end timestamps for batches of data given a list of instrument IDs, data types and a desired `target_size` (in bytes). This will allow the creation of "larger than memory" backtests that can stream batches of multiple instruments and data types *correctly*. We're using `scipy.minimize` to optimise a target function (the total bytes to read given instrument/data type inputs) by varying the end_timestamps. 
The problem may appear trivial on the surface (why not just read a portion from each table?) but when considering backtests containing multiple instruments or data types with tick streams that may vary in granularity significantly - this is the only way (that I can see thus far) that guarantees that …
=> Catalog data streaming

nautilus_trader/backtest/config.py, nautilus_trader/backtest/node.py, nautilus_trader/persistence/batching.py, tests/unit_tests/persistence/test_batching.py
Fixing a couple of bugs related to generic data in streaming backtests.
- `client_id` not correctly passed to backtest engine load_data
- Data objects not being wrapped in GenericData before being loaded
=> Fixing bugs in streaming generic data

nautilus_trader/backtest/node.py, nautilus_trader/persistence/batching.py
- Accidentally used `ts_event` rather than `ts_init` as the source timestamp.
- Indentation bug in engine load data
=> Revert bugs

nautilus_trader/backtest/node.py
Fixes a bug in `streaming_backtest_runner` when loading generic data, currently returning the wrong `Data.data_type`
=> Fix bug in generic data data_type 

.coveragerc, nautilus_trader/persistence/catalog.py, nautilus_trader/persistence/migrate.py, nautilus_trader/persistence/migrations/1.135.0.py, nautilus_trader/persistence/migrations/1.137.0.py, tests/unit_tests/persistence/test_catalog.py
This PR adds the start of a migration script for the DataCatalog. 
- Allow passing a pyarrow `projection` to the DataCatalog.
- Adds a sample `1.136.0 -> 1.137.0` migration for reference
- Adds a placeholder `migrate.py` file with some signatures to be filled in later
=> Catalog Migrations

nautilus_trader/persistence/streaming.py, nautilus_trader/serialization/arrow/schema.py, nautilus_trader/system/kernel.pyx, tests/unit_tests/persistence/test_streaming.py
- Fix a bug persisting OrderInitialized events.
- Replace prints with proper logger
- Log errors on failed persistence write
- Don't log repeatedly for missing writers
=> FeatherWriter cleanup

nautilus_core/core/src/buffer.rs, nautilus_core/core/src/uuid.rs, nautilus_core/model/src/types/balance.rs, nautilus_core/model/src/types/currency.rs, nautilus_core/model/src/types/money.rs
Added separate trait for Buffer with methods for converting to and from strings and a couple other helper methods. Added a macro_rule to mechanically implement Buffer for various Buffer structs.
- [ x ] Refactoring
Running `cargo test`
=> Add buffer trait and macro

nautilus_trader/model/instruments/equity.pyx, tests/unit_tests/model/test_model_instrument.py
* Adds missing arguments for nautilus_trader.model.instruments.equity.Equity to pass margin and fees to instrument. On default values will be set to zero.
* Fixes broken Equity.from_dict, Equity.to_dict.
Comment: I am not sure that maker/taker_fee in percentage is applicable to most US brokers. 
IB has a fixed fee for taking liquidity https://www.interactivebrokers.com/en/index.php?f=commission
Adds the following options:
```
margin_init : Decimal
The initial (order) margin requirement in percentage of order value.
margin_maint : Decimal
The maintenance (position) margin in percentage of position value.
maker_fee : Decimal
The fee rate for liquidity makers as a percentage of order value.
taker_fee : Decimal
The fee rate for liquidity takers as a percentage of order value.
```
Please …
=> Equity margin/fee fix

examples/notebooks/Untitled.ipynb, nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/persistence/streaming.py, tests/unit_tests/common/test_common_actor.py, tests/unit_tests/persistence/test_streaming.py
This PR adds a `publish_signal` method to the `Actor` class. This allows easier publishing / persisting of simple values when prototyping ideas in a trading strategy.
An `Actor` or `Strategy` can publish (and optionally persist by setting `stream=True`) by calling: 
```python
strategy = Strategy()
strategy.publish_signal(name="Test", ts_init=0, value=5.0, stream=False)
```
The signal will be published with the prefix `Signal`, and as such can be subscribed to via the `msgbus` using:
```python
self.msgbus.subscribe("data.SignalTest")
```
And if `stream=True`, the signal will be persisted into the `DataCatalog` as `SignalTest.feather`, alongside other streaming data.
3x tests added
=> Publish signal

nautilus_trader/execution/reports.pyx, tests/unit_tests/execution/test_execution_reports.py
Quantity object can't be negative, `PositionStatusReport.net_qty` will always be positive here.
https://github.com/nautechsystems/nautilus_trader/blob/5446cb7fe12a8bc9477997f2c71bc20eaf3bfc33/nautilus_trader/execution/reports.pyx#L416
Tests added. (pytests can't run on my local env, it reports segmentation fault, will check later
=> Fix PositionStatusReport net_qty sign

nautilus_core/Cargo.lock, nautilus_core/core/Cargo.toml, nautilus_core/core/src/time.rs, nautilus_trader/core/includes/core.h, nautilus_trader/core/rust/core.pxd
Add Rust ffi methods for monotonic time for timestamp, ms, us, ns
- [ x ] New feature (non-breaking change which adds functionality)
Test cases for all
=> Rust ffi methods for monotonic time

nautilus_trader/backtest/node.py, nautilus_trader/config/backtest.py
Changes to accommodate setting venue leverage options.
Re-ran backtest examples after setting `default_leverage` and `leverages`. No errors were encountered.
=> Set backtest leverage options

docs/user_guide/adapters.md
Fix missing exchange lead to :
```
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<FTXDataClient._connect() done, defined at /usr/local/pip-global/nautilus_trader/adapters/ftx/data.py:134> exception=ValueError('The InstrumentId string value was malformed, was ETH-PERP')>
Traceback (most recent call last):
File "/usr/local/pip-global/nautilus_trader/adapters/ftx/data.py", line 139, in _connect
await self._instrument_provider.initialize()
File "/usr/local/pip-global/nautilus_trader/common/providers.py", line 163, in initialize
instrument_ids = [InstrumentId.from_str(i) for i in self._load_ids_on_start]
File "/usr/local/pip-global/nautilus_trader/common/providers.py", line 163, in <listcomp>
instrument_ids = [InstrumentId.from_str(i) for i in …
```
=> Add missing exchange info when specify specific intruments to load (documentation)

nautilus_trader/model/objects.pyx, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py
Load quotes ticks as pd.DataFrame using the use_rust=True, as_nautilus=False arguments in the ParquetDataCatalog.
- [ x] New feature (non-breaking change which adds functionality)
Test added: test_data_catalog_quote_ticks_use_rust
The length, type and values of the dataframe contents are asserted.
=> Load quote ticks as dataframe. use_rust=True, as_nautilus=False

nautilus_trader/config/backtest.py, nautilus_trader/persistence/catalog/base.py, tests/unit_tests/backtest/test_backtest_config.py
Allow passing metdata through to GenericData class for BacktestDataConfig
=> Add metadata to BacktestDataConfig

nautilus_core/core/src/cvec.rs, nautilus_core/persistence/src/parquet/mod.rs, nautilus_core/persistence/tests/test_parquet_reader.rs
CVec should be converted to a Vec with the proper type and then dropped
Using valgrind on the test example
=> Fix dropping CVec to prevent memory leak

nautilus_trader/persistence/external/core.py
Fixes conditional if statement related to the "overwrite_or_ignore" kwarg in the ParquetDataCatalog.
The "overwrite_or_ignore" kwarg is enabled when the pyarrow version is >= 6 AND < 10
The "overwrite_or_ignore" kwarg is enabled when the pyarrow version is >= 6
- [ x] Bug fix (non-breaking change which fixes an issue)
=> Fix overwrite_or_ignore kwarg

nautilus_trader/cache/cache.pxd, nautilus_trader/cache/cache.pyx, tests/unit_tests/cache/test_cache_data.py
Changes to the get_xrate method. If no quotes are found for an instrument, the bar close prices are used instead.
Only bars with PriceType.BID, PriceType.ASK are supported.
Only uses the Bar prices if both bid and ask bars exist for the instrument.
[x ] New feature (non-breaking change which adds functionality)
How has this change been tested?
test_get_xrate_fallbacks_to_bars_if_no_quotes_returns_correct_rate
test_get_xrate_fallbacks_to_bars_if_no_quotes_returns_correct_rate_with_add_bars
=> Bar prices in get_xrate

examples/live/interactive_brokers_example.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/gateway.py, nautilus_trader/adapters/interactive_brokers/parsing/execution.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/adapters/interactive_brokers/providers.py, tests/integration_tests/adapters/interactive_brokers/conftest.py, tests/integration_tests/adapters/interactive_brokers/responses/account_values.json, tests/integration_tests/adapters/interactive_brokers/test_data.py, tests/integration_tests/adapters/interactive_brokers/test_execution.py, tests/integration_tests/adapters/interactive_brokers/test_historic.py, tests/integration_tests/adapters/interactive_brokers/test_kit.py, tests/integration_tests/adapters/interactive_brokers/test_parsing.py, tests/integration_tests/adapters/interactive_brokers/test_providers.py
Fixing a couple of issues with interactive brokers adapters:
- Fix instrument filters bug #812
- Fix missing sizeMinTick #813  
- Fix bug in gateway not setting username/password and env var names
- Add `read_api` to gateway startup to allow execution
- Add exec details for order fills
- Add account balance handling on startup
Tests.
=> Fixes to IB Adapter

nautilus_trader/adapters/interactive_brokers/factories.py
IB Connect timeout of 1 sec is too low and client connection fails.
Timeout has been changed to 6 sec. Connections to TWS works fine.
=> IB connect timeout

nautilus_trader/adapters/interactive_brokers/providers.py, nautilus_trader/config/common.py, tests/integration_tests/adapters/interactive_brokers/test_kit.py, tests/integration_tests/adapters/interactive_brokers/test_providers.py
- Handful of fixes for options load in IB instrument provider
- Adds a `filter_callable` parameter to InstrumentProviderConfig to allow more flexibility when loading instruments (via a callable)
=> Fixes to IB instruments

nautilus_trader/backtest/node.py, nautilus_trader/config/__init__.py, nautilus_trader/config/backtest.py, nautilus_trader/core/inspect.pyx, nautilus_trader/persistence/funcs.py, nautilus_trader/test_kit/stubs/config.py, tests/unit_tests/backtest/test_backtest_config.py, tests/unit_tests/persistence/test_batching.py, tests/unit_tests/persistence/test_streaming.py
- Remove Partialable class (not playing nicely with pydantic)
- Remove some unused `__tokenize__` functions
- Fix some skipped tests
- Add some more backtest run config tokenize tests
=> Remove Partialable from Backtest config

nautilus_trader/model/identifiers.pxd, nautilus_trader/model/identifiers.pyx, tests/unit_tests/portfolio/test_portfolio.py
Added new function in AccountId to get the original account_id without issuer string. Useful in the adapter to refer original account_id.
Returns original string without issuer. Added in TestPortfolio as well.
=> AccountId function to return id without issuer string

nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/parsing/execution.py, nautilus_trader/model/identifiers.pxd, nautilus_trader/model/identifiers.pyx, tests/integration_tests/adapters/interactive_brokers/base.py, tests/unit_tests/portfolio/test_portfolio.py
This PR will make sure balances are returned for the intended account in case of multiple accounts on the TWS gateway. Also it will make sure the orders are placed to that intended account only. Furthermore this will add verification check that logged in account of the TWS/Gateway is same as expected, being logged into wrong account (account_id not matching with the Nautilus Config account_id) will Engine will not receive any account balances and orders will not be accepted by the Gateway.
Tested with TWS connectivity.
=> IB balances filter and placeOrder for intended account_id

nautilus_core/model/src/data/tick.rs, nautilus_trader/persistence/catalog/rust/reader.pxd, nautilus_trader/persistence/catalog/rust/reader.pyx
Fixes the ParquetReader class to free the rust memory.
tests/unit_tests/persistence/test_catalog_rust.py::test_parquet_reader_frees_rust_memory
The problem was identified by measuring the peak memory usage of the ParquetFileReader class during iteration.
=> Fix reader free

nautilus_trader/adapters/interactive_brokers/data.py
IB returns -1 as Volume value where not available i.e. Forex bars. The change will use zero as minimum quantity for compliance with Nautilus Quantity.
Minor fix. Bars return as expected.
=> Fix the Volume Quantity error

nautilus_trader/model/data/bar.pyx
This PR adds the property to BarSpecification to get timedelta which is quick helper function to compare different bar timeframes.
=> Add timedelta property to BarSpecification

nautilus_trader/adapters/interactive_brokers/parsing/instruments.py
Minor fix for base_currency and quote_currency of the IB's FX instrument i.e. EUR/USD have the EUR as base and USD as quote.
=> Fix IB FX Instrument base_currency and quote_currency

nautilus_trader/adapters/interactive_brokers/data.py
- Used NT create_task for activating subscription instead of relying on ib_insync which requires nest_loop and is incompatible with uvloop
- Improvements in on_historical_bar_update event
- Added error handling hook to IB
- Resubscribe the Bar subscriptions upon connection lost between Gateway and IB i.e error codes 1101 and 1102 which is lost otherwise
Live subscription with TWS/Gateway and disconnecting internet connectivity to reproduce connection lost events.
=> Improvements in IB Data Subscription

nautilus_core/Cargo.lock, nautilus_core/model/Cargo.toml, nautilus_core/model/src/events/order.rs, nautilus_core/model/src/orders/mod.rs
Refactor orders and events
Extract common field values into separate struct
impl Deref, From and Into where needed
Use derive_builder crate
Apart from ergonomic improvements having a common OrderMetaData struct with string values that are mostly unchanged between orders is a significant improvement on the memory footprint.
[x]: Refactor
Order tests were run and passed.
=> Refactor orders and events

.pre-commit-config.yaml, nautilus_core/common/src/clock.rs, nautilus_core/model/src/data/bar.rs, nautilus_core/model/src/types/price.rs, nautilus_core/model/src/types/quantity.rs, nautilus_trader/core/includes/model.h, nautilus_trader/core/rust/model.pxd, nautilus_trader/model/data/bar.pyx, nautilus_trader/model/objects.pyx
Add pre-commit checks for Rust and fix failing pre-commit lints
* remove explicit free function for structs that don't have any heap allocate fields
* potentially memory leaking implementation in clocks, skipped test for now as it might need larger refactor
pre-commit checks are passing. Rust tests are passing.
=> Add pre-commit hooks for Rust

examples/live/interactive_brokers_book_imbalance.py, examples/live/interactive_brokers_example.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/live/node.py
- Default to `start_gateway=False` in examples. Gateway has been quite flaky recently. 
- Fix ENV vars not being automatically picked up.
=> Couple of IB fixes

nautilus_trader/live/execution_client.py
When account reconciliation is enabled and TradingNode position doesn't match the actual positions with the Broker, TradingNode would halt and doesn't continue. This is the correct and expecte behavior.
However, if for some reason there is exception raised within any of the three reports, which is quit possible, TradingNode simply raises the exception but continues on treating `reconciliation=True`.
=> Halt Engine if Exception raised for generate_mass_status

nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_data_engine.py
This will allow the the Bar to be processed where timestamp is higher than last but flag is set revision.
Added the test.
=> Relax the validate_data_sequence

nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx
Adds the Optional `request_id` for the in Actor requests. This allow the requests to be tracked by Actor/Strategy and ease working with asyncio. Hope this will be common useful feature.
=> Optional `request_id` in Actor REQUESTS

nautilus_core/backtest/cbindgen_cython.toml, nautilus_core/backtest/src/engine.rs, nautilus_core/common/src/clock.rs, nautilus_core/common/src/timer.rs, nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, nautilus_trader/common/clock.pxd, nautilus_trader/common/clock.pyx, nautilus_trader/core/includes/backtest.h, nautilus_trader/core/includes/common.h, nautilus_trader/core/rust/backtest.pxd, nautilus_trader/core/rust/common.pxd
Use CVec to pass vector of TimeEventHandlers to Cython for consistency
Tests were run
=> Use CVec for Vec of TimeEventHandlers

nautilus_core/backtest/src/engine.rs, nautilus_core/common/src/timer.rs, nautilus_trader/common/clock.pyx, nautilus_trader/common/timer.pyx, nautilus_trader/core/includes/common.h, nautilus_trader/core/rust/common.pxd
TimeEvent `from_mem_c` was assigning memory rather than cloning. This was causing a double free.
Tests were run.
=> Time event tests

nautilus_core/persistence/benches/persistence_benchmark.rs, nautilus_core/persistence/src/lib.rs, nautilus_core/persistence/src/session.rs, nautilus_core/persistence/tests/test_catalog.rs
`DataCatalogBackend` => `DataBackendSession`
`PythonQueryResult` => `DataQueryResult`
This is a breaking change because it renames public API. But it is needed because the current names are leaky and confusing.
GitHub CI tests
=> Rename persistence classes

nautilus_trader/persistence/external/core.py, tests/unit_tests/persistence/test_catalog.py
Allow user to choose custom `basename_template` for Catalog. This allows grouping based on need for ease of management.
Also found the fix for #833 by adding additional flag to keep existing functionality as-is.
Functional testing.
=> Allow Catalog basename_template for Instruments

nautilus_trader/common/clock.pyx, nautilus_trader/core/datetime.pyx, nautilus_trader/persistence/loaders.py
In Pandas v2, timezone aware datetimeindexes return 'datetime.timezone.utc' for tzinfo. This fails comparison when checking for timezone aware indexes. Explicitly setting these datetimeindexes to pytz.utc allows support for both Pandas 1.5.x and Pandas 2.x
Non-breaking change that allows support for Pandas ^1.5.3 as set in pyproject.toml dependencies.
This appears it will also apply cleanly to master
Slightly unsure about the change to cimport in `nautilus_trader/core/datetime.pyx`
- [ x] Bug fix (non-breaking change which fixes an issue)
unit_tests and acceptance_tests have passed
=> Support Pandas v2

nautilus_core/model/src/orderbook/level_api.rs, nautilus_trader/model/orderbook/book.pyx
This fixes how CVec is being dropped for orderbook exposed C APIs
`test_orderbook.py` tests were run and passed
=> Orderbook C API CVec fixes

nautilus_core/network/src/websocket.rs
Allow websocket to send text messages to connection. 
It is exposed as a python method. Closes #1206
```rust
/// Send text data to the connection.
///
/// # Safety
/// - Throws an Exception if it is not able to send data
fn send_text<'py>(slf: PyRef<'_, Self>, data: String, py: Python<'py>) -> PyResult<&'py PyAny> {
```
Using library method
=> Expose send text method on websocket

nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/modules.pxd, nautilus_trader/backtest/modules.pyx, tests/unit_tests/backtest/test_exchange.py, tests/unit_tests/backtest/test_modules.py
Adds a `pre_process` hook to the SimulationModule and calls inside the BacktestEngine prior to passing through to the matching engines.
Should allow more complicated matching logic to be applied.
An example use case is custom fills for limit (passive) orders, which could look something like: 
```python
class PassiveFillModule(SimulationModule):
def pre_process(self, data):
if isinstance(data, TradeTick):
open_orders = [o for o in self.cache.orders_open(instrument_id=data.instrument_id) if isinstance(o, LimitOrder)]
for order in open_orders:
should_fill = (
(order.side == OrderSide.BUY and order.price >= data.price) or
(order.side == OrderSide.BUY and order.price <= data.price)
)
if should_fill:
matching_engine = self.exchange.get_matching_engine(data.instrument_id)
book = …
```
=> Add pre_process hook to SimulationModule

nautilus_core/network/src/lib.rs, nautilus_core/network/src/socket.rs, nautilus_trader/adapters/betfair/sockets.py
Add Tcp auto reconnect following a similar model as the websocket. Also add optional pre, post-reconnect and disconnect hooks for Tcp connection. 
An updated tcp socket disconnect and reconnect test.
=> Add auto-reconnect feature to Tcp socket connection

nautilus_trader/persistence/wranglers.pyx, tests/unit_tests/backtest/test_data_wranglers.py, tests/unit_tests/data/test_aggregation.py
Handle timestamps with nanosecond precision in the QuoteTickDataWrangler class.
Tests added:
test_data_wranglers.py::TestQuoteTickDataWrangler::test_process_handles_nanosecond_timestamps
=> handle wrangler nanosecond timestamps

nautilus_core/indicators/src/average/ama.rs, nautilus_core/indicators/src/average/ema.rs, nautilus_core/indicators/src/average/mod.rs, nautilus_core/indicators/src/average/sma.rs, nautilus_core/indicators/src/indicator.rs, nautilus_core/indicators/src/ratio/efficiency_ratio.rs, nautilus_core/indicators/src/ratio/mod.rs, nautilus_core/indicators/src/stubs.rs
- `AdaptiveMovingAverage` indicator with tests
- `EfficientRatio` indicator with tests
- `indicators` crate reorganization and stubs data file with parametrized fixtures
=> Add core Adaptive MA and Efficiency ratio indicators

nautilus_core/Cargo.lock, nautilus_core/indicators/Cargo.toml, nautilus_core/indicators/src/average/ama.rs, nautilus_core/indicators/src/average/dema.rs, nautilus_core/indicators/src/average/ema.rs, nautilus_core/indicators/src/average/mod.rs, nautilus_core/indicators/src/average/sma.rs, nautilus_core/indicators/src/indicator.rs, nautilus_core/indicators/src/momentum/mod.rs, nautilus_core/indicators/src/momentum/rsi.rs, nautilus_core/indicators/src/stubs.rs
- trait `MovingAverage` was implemented that exposed `update_raw` method
- implemented `RelativeStrengthIndex` struct in rust with tests
- new indicator module `momentum` was created where RSI indicator is placed
=> Add RelativeStrengthIndex(RSI) indicator for Rust

nautilus_core/core/src/serialization.rs, nautilus_core/model/src/data/bar_py.rs, nautilus_core/model/src/data/delta_py.rs, nautilus_core/model/src/data/order_py.rs, nautilus_core/model/src/data/quote_py.rs, nautilus_core/model/src/data/ticker_py.rs, nautilus_core/model/src/data/trade_py.rs, nautilus_core/model/src/instruments/crypto_perpetual.rs, nautilus_core/model/src/instruments/mod.rs, nautilus_core/model/src/lib.rs, nautilus_trader/test_kit/rust/instruments.py, nautilus_trader/test_kit/rust/types.py, tests/unit_tests/model/instruments/test_crypto_perpetual_pyo3.py
- created `from_dict_pyo3` generic rust function, and attached it to `from_dict` function for reuse
- finished `CryptoPerpetual` struct and added proper `pymethods` so that it can be used in python
- created rust testkit for instruments type
- pyo3 tests for `CryptoPerpetual`
=> Add CryptoPerpetual instrument for Rust

nautilus_trader/persistence/catalog/parquet.py
Write parquet data in row groups to reduce memory usage when reading it. Resolves #1253 
Writing data works
=> Write parquet data in row groups

nautilus_core/Cargo.lock, nautilus_core/model/Cargo.toml, nautilus_core/model/src/instruments/crypto_future.rs, nautilus_trader/test_kit/rust/instruments.py, tests/unit_tests/model/instruments/test_crypto_future_pyo3.py
-  pyo3 tests for CryptoPerpetual
- `CryptoFuture` struct with proper pymethods
=> Add CryptoFuture instrument for Rust 

nautilus_core/network/src/lib.rs, nautilus_core/network/src/websocket.rs, nautilus_trader/core/nautilus_pyo3.pyi, tests/integration_tests/network/test_websocket.py
Closes #1236 
The existing websocket python api has changed slightly because it takes a configuration object. Python tests have been updated.
Cargo test
=> Pass headers in websocket connection

nautilus_core/indicators/src/average/ama.rs, nautilus_core/indicators/src/average/dema.rs, nautilus_core/indicators/src/average/ema.rs, nautilus_core/indicators/src/average/mod.rs, nautilus_core/indicators/src/average/sma.rs, nautilus_core/indicators/src/average/wma.rs, nautilus_core/indicators/src/momentum/rsi.rs, nautilus_core/indicators/src/python/average/ama.rs, nautilus_core/indicators/src/python/average/dema.rs, nautilus_core/indicators/src/python/average/ema.rs, nautilus_core/indicators/src/python/average/mod.rs, nautilus_core/indicators/src/python/average/sma.rs, nautilus_core/indicators/src/python/average/wma.rs, nautilus_core/indicators/src/python/mod.rs, nautilus_core/indicators/src/python/momentum/mod.rs, nautilus_core/indicators/src/python/momentum/rsi.rs, nautilus_core/indicators/src/python/ratio/efficiency_ratio.rs, nautilus_core/indicators/src/python/ratio/mod.rs, nautilus_core/indicators/src/ratio/efficiency_ratio.rs, nautilus_core/indicators/src/stubs.rs, nautilus_core/pyo3/src/lib.rs
- `WeightedMovingAverage` indicator with tests and pyo3
- python submodule in indicator crate
=> Add WeightedMovingAverage indicator in rust

nautilus_trader/backtest/node.py
Validate that the end time is a timestamp larger than the start time when configuring a backtest with the `BacktestDataConfig`.
This throws an ValueError when running the code snippet of #1304.
=> data config: validate that the end time is set after the start time

nautilus_core/model/src/instruments/options_contract.rs, nautilus_core/model/src/python/instruments/options_contract.rs, nautilus_trader/test_kit/rust/instruments.py, nautilus_trader/test_kit/rust/types.py, tests/unit_tests/model/instruments/test_crypto_future_pyo3.py, tests/unit_tests/model/instruments/test_crypto_perpetual_pyo3.py, tests/unit_tests/model/instruments/test_currency_pair_pyo3.py, tests/unit_tests/model/instruments/test_options_contract_pyo3.py
- existing Python pyo3 tests for instruments refactoring for function based tests
- struct `OptionsContract` with pymethods and pyo3 python tests
=> Add OptionsContract in rust with pyo3

nautilus_core/model/src/ffi/identifiers/client_id.rs, nautilus_core/model/src/ffi/identifiers/instrument_id.rs, nautilus_core/model/src/identifiers/account_id.rs, nautilus_core/model/src/identifiers/client_id.rs, nautilus_core/model/src/identifiers/client_order_id.rs, nautilus_core/model/src/identifiers/component_id.rs, nautilus_core/model/src/identifiers/exec_algorithm_id.rs, nautilus_core/model/src/identifiers/instrument_id.rs, nautilus_core/model/src/identifiers/mod.rs, nautilus_core/model/src/identifiers/order_list_id.rs, nautilus_core/model/src/identifiers/position_id.rs, nautilus_core/model/src/identifiers/strategy_id.rs, nautilus_core/model/src/identifiers/stubs.rs, nautilus_core/model/src/identifiers/symbol.rs, nautilus_core/model/src/identifiers/trade_id.rs, nautilus_core/model/src/identifiers/trader_id.rs, nautilus_core/model/src/identifiers/venue.rs, nautilus_core/model/src/identifiers/venue_order_id.rs
- moved all stub data for `identifiers` to its own file `stub.rs`
- its better if they are all in one file, then its will be easier to import them across other modules with `use crate::identifiers::stubs::*;
`
=> Refactoring stub data model for identifiers

nautilus_core/common/src/clock.rs, nautilus_core/common/src/generators/client_order_id.rs, nautilus_core/common/src/generators/mod.rs, nautilus_core/common/src/lib.rs, nautilus_core/model/src/identifiers/strategy_id.rs, nautilus_core/model/src/identifiers/stubs.rs, nautilus_core/model/src/identifiers/trade_id.rs, nautilus_core/model/src/identifiers/trader_id.rs, nautilus_core/model/src/orders/stubs.rs
- remove `new` method from `Clock` trait
- created `IdentifierGenerator<T>` trait
- implemented `ClientOrderIdGenerator` with boxed trait object for `Clock` fully tested in Rust
- added `get_tag` function for `StrategyId` and `TraderId`
=> Implement ClientOrderIdGenerator in rust

nautilus_core/common/src/generators/client_order_id.rs, nautilus_core/common/src/generators/mod.rs, nautilus_core/common/src/generators/order_list_id.rs
- removed arc mutex from count variable in `ClientOrderIdGenerator` as trader and backtesting is single-threaded and we dont want to pay performance penalty introducing thread safe generators
- added `OrderListIdGenerator` with rust tests
=> Implement OrderListIdGenerator in rust

nautilus_trader/model/position.pyx, tests/unit_tests/model/test_position.py
- add missing `trader_id` to function `to_dict` for `Position` class
=> Trader ID missing in Position dict

nautilus_core/common/src/generators/client_order_id.rs, nautilus_core/common/src/generators/order_list_id.rs, nautilus_core/common/src/generators/position_id.rs
In rust ID generators `clock` type should basically mutable reference with lifetime specifier  on boxed trait object `&'a mut Box<dyn Clock>` .Clock object will be supplied from "above"  or borrowed here,which is the correct implementation, and not the owned value.
`
=> Refactor clock type in rust id generators

nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/data_pyo3.py, tests/unit_tests/indicators/rust/test_sma_pyo3.py
- update `nautilus_pyo3.pyi` with proper typing for `__init__` methods and other types
- `TestDataProviderPyo3` for testing rust pyo3 types from `model` crate `data` module
- Eventhough indicators are properly tested in rust, we still need to be sure that pyo3 methods and fields are correctly defined, so we need to test it from python side also. Added python tests for rust pyo3 `SimpleMovingAverage`
=> Test rust pyo3 SimpleMovingAverage from python

nautilus_core/persistence/src/backend/session.rs, nautilus_core/persistence/src/python/backend/session.rs, nautilus_core/persistence/tests/test_catalog.rs
Add tests for the Python interface to DataBackendSession. It shows that monotonicity is maintained across the pyo3 bindings to the session.
Tests passed
=> Add Python interface tests for DataBackendSession

.gitignore, Makefile, nautilus_core/Cargo.lock, nautilus_core/model/Cargo.toml, nautilus_core/model/src/identifiers/mod.rs, nautilus_core/persistence/Cargo.toml, nautilus_core/persistence/src/bin/drop_db.rs, nautilus_core/persistence/src/bin/init_db.rs, nautilus_core/persistence/src/db/database.rs, nautilus_core/persistence/src/db/schema.rs, nautilus_core/persistence/src/db/sql.rs, schema/sql/tables.sql
- added `*.env` files to gitignore, so they are not picked up by git if they are created locally in source code folders
- created schema folder structure for Nautilus SQL data model
- added two new actions to `Makefile` and that are `init-db` and `drop-db` that will initialize Nautilus SQL schema to connected database ( mostly Postgres here). We will need those actions to resync the latest schema with the database. Migrations of schema will not be currently supported
- added corresponding cargo target for this scripts
- added two utils functions `init_db_schema` and `setup_test_database` that will be used both by cargo targets and tests when initializing testing sqlite database
- initial design for `SqlCacheDatabase` with `general` table for storing custom keys and values
=> Nautilus SQL schema init folder structure, scripts and POC sql cache database

nautilus_core/network/src/websocket.rs, nautilus_trader/core/nautilus_pyo3.pyi
- renamed `message` in `WebSocketConfig` to `heartbeat_msg` as its more clear that this message  for heartbeat task
- added missing args type in `nautilus_pyo3.pyi` file
=> Renaming of heartbeat message and added types to pyi file

nautilus_core/common/src/factories.rs
Fix typos in unit test method names
GitHub Actions
=> factories: fix typos in unit test method names

nautilus_core/model/src/instruments/crypto_future.rs, nautilus_core/model/src/instruments/crypto_perpetual.rs, nautilus_core/model/src/instruments/currency_pair.rs, nautilus_core/model/src/instruments/equity.rs, nautilus_core/model/src/instruments/futures_contract.rs, nautilus_core/model/src/instruments/mod.rs, nautilus_core/model/src/instruments/options_contract.rs, nautilus_core/model/src/instruments/stubs.rs
- moved all instrument stubs to separate file with `stubs` feature so then can be reused in other modules
=> Reorganize instrument stubs in Rust

nautilus_core/model/src/events/order/rejected.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/rejected.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished order event `OrderRejected` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderRejected in Rust

nautilus_core/model/src/events/order/emulated.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/emulated.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderEmulated` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderEmulated in Rust

nautilus_core/model/src/events/order/released.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/released.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderReleased` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderReleased in Rust

nautilus_trader/accounting/accounts/base.pyx, nautilus_trader/adapters/_template/data.py, nautilus_trader/adapters/_template/execution.py, nautilus_trader/adapters/_template/providers.py, nautilus_trader/adapters/interactive_brokers/client/common.py, nautilus_trader/backtest/modules.pyx, nautilus_trader/cache/base.pyx, nautilus_trader/cache/facade.pyx, nautilus_trader/common/clock.pyx, nautilus_trader/common/providers.py, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/client.pyx, nautilus_trader/execution/client.pyx, nautilus_trader/indicators/average/moving_average.pyx, nautilus_trader/indicators/base/indicator.pyx, nautilus_trader/live/execution_client.py, nautilus_trader/live/factories.py, nautilus_trader/model/events/order.pyx, nautilus_trader/model/identifiers.pyx, nautilus_trader/model/orders/base.pyx, nautilus_trader/portfolio/base.pyx, nautilus_trader/risk/sizing.pyx, nautilus_trader/serialization/base.pyx
```
2023-12-03T13:11:47.021937001Z [ERR] FILIP-001.ExecClient-BYBIT: Failed to generate AccountState: method must be implemented in the subclass
```
For these type of errors it's hard to pinpoint the exact method where it happened and why it must be implemented.
- Attached method name to error string when raising not implemented error
=> Attach method name when raising not implemented error

nautilus_core/model/src/events/order/pending_update.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/pending_update.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderPendingUpdate` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderPendingUpdate in Rust

nautilus_core/model/src/events/order/pending_cancel.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/pending_cancel.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderPendingCancel` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderPendingCancel in Rust

nautilus_core/model/src/events/order/cancel_rejected.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/cancel_rejected.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderCancelRejected` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderCancelRejected in Rust

nautilus_trader/config/common.py
Fixes below msgspec error.
```
return msgspec.json.decode(raw, type=cls, dec_hook=msgspec_decoding_hook)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Type unions containing a custom type may not contain any additional types other than `None` - type `nautilus_trader.model.identifiers.InstrumentId | str` is not supported
```
- [X ] Bug fix (non-breaking change which fixes an issue)
StrategyConfig validation/decoding working fine now.
=> Fix unsupported union

nautilus_trader/common/component.pxd, nautilus_trader/common/component.pyx, nautilus_trader/risk/engine.pyx
Reset the state of the risk engine. Otherwise, all new orders are rejected when starting a new backtest.
Local  running of multiple backtests.
=> risk engine: reset the state when starting a new backtest

nautilus_trader/adapters/interactive_brokers/historic/client.py
The `InteractiveBrokersHistoricClient` does not support different log levels, which makes troubleshooting IB API issues difficult. This PR provides that functionality.
=> Add log level to InteractiveBrokersHistoricClient

nautilus_trader/adapters/binance/common/data.py, nautilus_trader/live/node_builder.py
Fix SandboxLiveExecClientFactory creation
- creation of SandboxLiveExecClientFactory from NodeBuilder expects Portfolio object
Has not beet tested.
Not tested.
SandboxLiveExecClient does not work with
<file:///home/dpetrov/develop/python/nautilus_trader/nautilus_trader/adapters/sandbox/factory.py>
`SandboxLiveExecClientFactory` takes portfolio upon creation.
```
portfolio : PortfolioFacade
The read-only portfolio for the client.
```
but `TradingNode.build_exec_clients` does not pass the portfolio
<file:///home/dpetrov/develop/python/nautilus_trader/nautilus_trader/live/node_builder.py>
The change was introduced the following commit:    f0370a767709e520313ba2eac231811ebfbca531
<a id="org7ae446b"></a>
<a …
=> Fix SandboxLiveExecClientFactory from NodeBuilder

nautilus_trader/serialization/arrow/schema.py
References #1441 . `"trigger_price"` is incorrectly set to data type `pa.float64()` instead of `pa.string()`.
Tested locally. Awaiting validation from others.
=> Fix OrderUpdated arrow serialization

nautilus_trader/config/common.py, tests/integration_tests/adapters/betfair/test_kit.py, tests/unit_tests/backtest/test_node.py, tests/unit_tests/config/test_common.py, tests/unit_tests/persistence/test_streaming.py
This PR addresses a typing inconsistency observed in the `ImportableStrategyConfig`, a subclass of `NautilusConfig`. The core functionality expected from these configurations is the ability to be stored and parsed as JSON/YAML files. However, it was identified that while loading the strategy configurations as part of `ImportableStrategyConfig`, they were not receiving the correct type assignments.
To resolve this issue, the PR implements a fix ensuring that the strategy configuration is correctly parsed with appropriate types when creating strategies using `StrategyFactory`. This enhancement aligns `ImportableStrategyConfig` with the intended design of being fully compatible and operable with JSON/YAML file formats, thereby improving reliability and consistency in configuration handling. …
=> Fix type assignment in StrategyFactory for ImportableStrategyConfig

nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, tests/integration_tests/adapters/interactive_brokers/test_parsing.py
Most exchanges have FUT / FOP contracts with expiration date as %Y%m%d format.
Some exchanges, (IPE, ICEEU, LMEOTC) have contracts with expiration date %Y%m%d %H:%M:%S %Z. These contracts error on `pd.to_datetime()` as the format argument is incorrect.
This change parses contracts with the alternate expiration date.
=> parsing multiple contract expiration timestring formats

nautilus_trader/adapters/interactive_brokers/client/account.py
Resolves #1474. A bug was introduced during the Interactive Brokers Client refactoring when the `position` function was renamed to `process_position`. `position` is an EWrapper override, so the function should not have been renamed.
Tested locally.
=> Fix InteractiveBrokers get account positions bug

nautilus_trader/adapters/binance/spot/execution.py
FIX `nautilus_trader/adapters/binance/spot/execution.py`
```text
AttributeError('BinanceSpotExecutionClient' object has no attribute '_update_account_state_async')
```
=> Fix Binance non-existing method name

nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/adapters/interactive_brokers/providers.py, tests/integration_tests/adapters/interactive_brokers/test_parsing.py
The current symbology approach, while effective for a broad range of securities, encounters limitations with certain exchanges due to varied naming conventions that are not compatible with our existing parsing method. To address this, we are introducing a `strict_symbology` flag within the `InteractiveBrokersInstrumentProviderConfig`. When enabled (set to True), this flag mandates strict adherence to the `localSymbol=secType.exchange` format as stipulated by Interactive Brokers. This ensures comprehensive compatibility and eliminates parsing discrepancies.
For instance, with `strict_symbology` set to `True`, the symbology for instruments strictly follows the format provided by InteractiveBrokers, such as **EUR.USD=CASH.IDEALPRO**. Conversely, when set to `False`, the system applies a …
=> Support optional strict_symbology for IB

nautilus_core/model/src/lib.rs, nautilus_core/model/src/orders/market.rs, nautilus_core/model/src/orders/stubs.rs, nautilus_core/model/src/position.rs, nautilus_core/model/src/stubs.rs
- created a new `TestOrderStubs` Rust struct which will generate orders instead of order factory
- uncommented and fixed all position tests after move to `model` crate
=> Finish position Rust tests

nautilus_trader/adapters/interactive_brokers/client/common.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py
User "d2b" in Discord reported the following error:
```
Error on `_run_internal_msg_queue`: AttributeError("'coroutine' object has no attribute 'keywords'")
```
The issue originates from a bug in the `historicalDataUpdate` EWrapper override method of the `InteractiveBrokersClientMarketDataMixin` class. The root cause  is the incorrect usage of a `functools.partial` object, which encapsulates the `subscribe_historical_bars` function. The `functools.partial` was being called rather than simply accessing the `keywords` attribute.
Tested locally.
=> Fix InteractiveBrokers historical bar data bug

nautilus_core/Cargo.lock, nautilus_core/model/Cargo.toml, nautilus_core/model/src/python/enums.rs, nautilus_core/model/src/python/macros.rs
- removed multiple-pymethods feature in `model` crate which cause MacOS build test errors
- added manually methods from `enum_for_python` macro across all model enums
- deleted `enum_for_python` macro
=> Unroll macro for python Rust enum

nautilus_trader/adapters/interactive_brokers/client/connection.py
When an IB connection was broken, the following error was being thrown:
```
02T21:11:30.288768001Z [ERROR] TESTER-001.InteractiveBrokersClient-002: Error on `_run_watch_dog`: TypeError('an integer is required')
```
Started a dummy strategy then killed IB gateway, which did not result in the exception above. After restarting IB gateway, NT reestablished the connection without user intervention.
=> Fix bug in IB connection error logging

nautilus_core/Cargo.lock, nautilus_core/network/tokio-tungstenite/Cargo.toml
Remove outdated hyper from tokio tungstenite
tokio-tungstenite and websocket tests were run
=> Remove major version outdated dependencies

nautilus_trader/common/component.pyx, tests/unit_tests/common/test_throttler.py
Fixes #1526 
The throttler is dropping messages even after a sufficiently long quiet period. Instead of using the timestamp of the latest message, and the clock instead.
Adding unit tests and ran a backtest.
=> throttler: fix the throttler when sending messages after messages are dropped

nautilus_core/accounting/Cargo.toml, nautilus_core/indicators/Cargo.toml
- We have missing `nautilus-core/python` and `nautilus-model/python` features in `accounting` and `indicator` crates
=> Fix missing python feature in some Rust crates

nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/connection.py, nautilus_trader/adapters/interactive_brokers/client/wrapper.py, nautilus_trader/adapters/interactive_brokers/factories.py
Hotfix related to #1532. The `InteractiveBrokersClient` would automatically startup because there was a call to `_reset()` in the constructor, but that is generally considered an antipattern, so now it needs to be explicitly started.
- All tests pass
=> Fix Interactive Brokers client start

nautilus_core/accounting/src/python/cash.rs, nautilus_core/accounting/src/python/margin.rs, nautilus_core/adapters/src/databento/python/historical.rs, nautilus_core/adapters/src/databento/python/live.rs, nautilus_core/adapters/src/databento/python/loader.rs, nautilus_core/model/src/python/instruments/mod.rs, nautilus_core/model/src/python/position.rs
- created new util function `convert_pyobject_to_instrument_type`  that gives enum `InstrumentType` for given `PyObject` based on the `instrument_type` property inside class
- refactor various python function that uses this pattern (in accounting + position)
- moved `convert_instrument_to_pyobject` from `adapters` crate to `model` crate
=> Conversion between instrument type and PyObject refactor

nautilus_core/model/src/python/events/order/accepted.rs, nautilus_core/model/src/python/events/order/cancel_rejected.rs, nautilus_core/model/src/python/events/order/canceled.rs, nautilus_core/model/src/python/events/order/denied.rs, nautilus_core/model/src/python/events/order/emulated.rs, nautilus_core/model/src/python/events/order/expired.rs, nautilus_core/model/src/python/events/order/filled.rs, nautilus_core/model/src/python/events/order/initialized.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/modify_rejected.rs, nautilus_core/model/src/python/events/order/pending_cancel.rs, nautilus_core/model/src/python/events/order/pending_update.rs, nautilus_core/model/src/python/events/order/rejected.rs, nautilus_core/model/src/python/events/order/released.rs, nautilus_core/model/src/python/events/order/submitted.rs, nautilus_core/model/src/python/events/order/triggered.rs, nautilus_core/model/src/python/events/order/updated.rs
- attached `order_event_type` attribute to all pyo3 order events
- create two utils function `convert_order_event_to_pyobject` and `convert_pyobject_to_order_event` to help with conversion
=> Order event from and to PyObject conversion

nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/schemas/ws.py, tests/integration_tests/adapters/bybit/test_ws_decoders.py
Add msgspec schema's for trade messages for spot and option instruments, due to the `L` field being unique to futures and `id` being unique to options.
Locally listening to trade and quote ticks for the Bybit exchange.
=> bybit: add trade spot and trade option websocket msgspec schemas

nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/schemas/ws.py, nautilus_trader/adapters/bybit/websocket/client.py, tests/integration_tests/adapters/bybit/test_ws_decoders.py
Refactor the data schema for the trade message using optional fields for futures and option messages.
Resubscribe to all subscription feeds when reconnecting. 
pre-commit and locally subscribing to the trade and quote ticks.
=> Refactor Bybit trade schema and improve websocket reconnects

nautilus_trader/adapters/sandbox/execution.py, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/exchange.pxd, nautilus_trader/backtest/exchange.pyx, nautilus_trader/backtest/matching_engine.pxd, nautilus_trader/backtest/matching_engine.pyx, nautilus_trader/backtest/models.pxd, nautilus_trader/backtest/models.pyx, tests/unit_tests/backtest/test_commission_model.py, tests/unit_tests/backtest/test_exchange_bitmex.py, tests/unit_tests/backtest/test_exchange_bracket_if_touched_entries.py, tests/unit_tests/backtest/test_exchange_cash.py, tests/unit_tests/backtest/test_exchange_contingencies.py, tests/unit_tests/backtest/test_exchange_l2_mbp.py, tests/unit_tests/backtest/test_exchange_margin.py, tests/unit_tests/backtest/test_exchange_stop_limits.py, tests/unit_tests/backtest/test_exchange_trailing_stops.py, tests/unit_tests/backtest/test_matching_engine.py, tests/unit_tests/execution/test_algorithm.py, tests/unit_tests/execution/test_emulator_list.py, tests/unit_tests/trading/test_strategy.py, tests/unit_tests/trading/test_trader.py
This PR introduces an enhancement to the CommissionModel, as outlined in issue #632, maintaining the default behavior while integrating a fixed price model. It further establishes a foundation for developing adapter-specific commission models.
Existing tests passed and new tests added.
=> Implement CommissionModel

nautilus_trader/persistence/wranglers.pyx, tests/unit_tests/persistence/test_wranglers.py
Implement `process_bar_data` in `TradeTickDataWrangler`.
Added test.
=> Implement TradeTickDataWrangler.process_bar_data

nautilus_trader/persistence/wranglers.pyx, tests/unit_tests/persistence/test_wranglers.py
Followup on previous PR to fix call to `_create_side_if_not_exist`.
=> Fix and Refine TradeTickDataWrangler.process_bar_data

nautilus_core/core/src/nanos.rs, nautilus_core/model/src/python/orders/limit_if_touched.rs, nautilus_core/model/src/python/orders/market.rs, nautilus_core/model/src/python/orders/market_if_touched.rs, nautilus_core/model/src/python/orders/market_to_limit.rs, nautilus_core/model/src/python/orders/mod.rs, nautilus_core/model/src/python/orders/stop_limit.rs, nautilus_core/model/src/python/orders/stop_market.rs, nautilus_core/model/src/python/orders/trailing_stop_limit.rs, nautilus_core/model/src/python/orders/trailing_stop_market.rs, nautilus_trader/core/nautilus_pyo3.pyi
- added `From<&str>` and `FromStr` traits for `UnixNanos`
- added remaining pyo3 orders and type them in `nautilus_pyo3.pyi` file
=> Finish missing pyo3 Rust Orders

nautilus_trader/backtest/models.pxd, nautilus_trader/backtest/models.pyx, tests/unit_tests/backtest/test_commission_model.py
This PR addresses a bug in the `FixedFeeModel` where a commission was incorrectly charged for every fill. The default behavior has now been corrected to charge a commission per order. Additionally, users can opt to set `charge_commission_once=True` to enable commission charges per fill.
Updated tests.
=> Fixed Commission Charging Behavior in FixedFeeModel

nautilus_trader/cache/cache.pxd, nautilus_trader/cache/cache.pyx, nautilus_trader/portfolio/portfolio.pyx, nautilus_trader/test_kit/stubs/data.py, tests/unit_tests/cache/test_data.py
Implement Fallback to Bar Price in Cache and Portfolio when Ticks unavailable as proposed in #1480.
Added tests.
=> Implement Fallback to Bar Price in Cache and Portfolio when Ticks unavailable

nautilus_trader/model/instruments/currency_pair.pyx
- in `CurrencyPair` class `lot_size` field should use `Quantity.from_raw_c` for the correct conversion
=> Fix method from_pyo3_c in Currency pair for lot_size conversion 

nautilus_core/model/src/python/orders/limit.rs, nautilus_core/model/src/python/orders/limit_if_touched.rs, nautilus_core/model/src/python/orders/market.rs, nautilus_core/model/src/python/orders/market_if_touched.rs, nautilus_core/model/src/python/orders/market_to_limit.rs, nautilus_core/model/src/python/orders/stop_limit.rs, nautilus_core/model/src/python/orders/stop_market.rs, nautilus_core/model/src/python/orders/trailing_stop_limit.rs, nautilus_core/model/src/python/orders/trailing_stop_market.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/model/orders/limit.pxd, nautilus_trader/model/orders/limit.pyx, nautilus_trader/model/orders/limit_if_touched.pxd, nautilus_trader/model/orders/limit_if_touched.pyx, nautilus_trader/model/orders/market.pxd, nautilus_trader/model/orders/market.pyx, nautilus_trader/model/orders/market_if_touched.pxd, nautilus_trader/model/orders/market_if_touched.pyx, nautilus_trader/model/orders/market_to_limit.pxd, nautilus_trader/model/orders/market_to_limit.pyx, nautilus_trader/model/orders/stop_limit.pxd, nautilus_trader/model/orders/stop_limit.pyx, nautilus_trader/model/orders/stop_market.pxd, nautilus_trader/model/orders/stop_market.pyx, nautilus_trader/model/orders/trailing_stop_limit.pxd, nautilus_trader/model/orders/trailing_stop_limit.pyx, nautilus_trader/model/orders/trailing_stop_market.pxd, nautilus_trader/model/orders/trailing_stop_market.pyx, nautilus_trader/model/orders/unpacker.pyx
- follow Cython convention and call function which are call from C code with `_c`, with that refactor which can add python functions `create` on orders classes
- add Rust `create` method and export it with pyo3
=> Refactor create method method in orders for Cython and Rust

nautilus_core/Cargo.lock, nautilus_core/Cargo.toml, nautilus_core/model/Cargo.toml, nautilus_core/model/src/instruments/crypto_future.rs, nautilus_core/model/src/instruments/crypto_perpetual.rs, nautilus_core/model/src/instruments/currency_pair.rs, nautilus_core/model/src/instruments/equity.rs, nautilus_core/model/src/instruments/futures_contract.rs, nautilus_core/model/src/instruments/futures_spread.rs, nautilus_core/model/src/instruments/mod.rs, nautilus_core/model/src/instruments/options_contract.rs, nautilus_core/model/src/instruments/options_spread.rs, nautilus_core/persistence/Cargo.toml
- finalize `Instrument` Rust trait so that it contains its union from all instrument struct fields and can later represent SQL table `instrument`
- implement `FromRow` sqlx trait for Postgres that will help with conversion from Postgres to native rust type
=> Finish Instrument trait and implement sqlx trait FromRow for instruments

.docker/docker-compose.yml, Makefile, docs/developer_guide/environment_setup.md, nautilus_core/Cargo.lock, nautilus_core/Cargo.toml, nautilus_core/cli/Cargo.toml, nautilus_core/cli/src/bin/cli.rs, nautilus_core/cli/src/database/mod.rs, nautilus_core/cli/src/database/postgres.rs, nautilus_core/cli/src/lib.rs, nautilus_core/cli/src/opt.rs, nautilus_core/common/build.rs, nautilus_core/core/build.rs, nautilus_core/infrastructure/src/sql/pg.rs, nautilus_core/model/build.rs, schema/tables.sql
- created a `docker-compose.yml` file in `.docker` directory to help bootstrap all the services used by nautilus system
- added new `Makefile` target `install-cli` that build and install `nautilus` CLI executable 
- updated `docs/developer_guide/environment_setup.md` with documentation around running services with `docker-compose`, how to build and use `nautilus` cli, and which commands are currently implemented
- created a new `cli` rust crate that contains Rust CLI design with target commands 
- fixed `build.rs` warning when running `install-cli` by conditionally importing std env based on FFI feature (to suppress warnings)
- WIP SQL Nautilus in `schema/tables.sql` that is being heavy developed 
You can use `docker-compose.yml` file located in `.docker` directory 
to bootstrap the …
=> Nautilus CLI

nautilus_trader/adapters/interactive_brokers/common.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/model/instruments/__init__.py, nautilus_trader/model/instruments/cfd.pxd, nautilus_trader/model/instruments/cfd.pyx, nautilus_trader/model/instruments/commodity.pxd, nautilus_trader/model/instruments/commodity.pyx, nautilus_trader/serialization/arrow/implementations/instruments.py
add CFD and Commodity support for Interactivebrokers;
fix the strict_symbology for parsing Instrument/contract of Interactivebrokers
Tested with "XAUUSD.IBCMDTY", "XAUUSD.IBCFD", "IBUS30.IBCFD", "TSLA.IBCFD", "EUD/USD.IBCFD" by live trading and historical data downloading. 
a doc that "IBCFD" and "IBCMDTY" used as venue (mapping to "SMART") might be updated.
Although it works with no bugs as far as i tested it, the cfd.pyx and commodity.pyx may need to be refined.
Thanks @rsmb7z for advice.
=> Add CFD and Commodity support for Interactive Brokers

nautilus_trader/adapters/betfair/execution.py
Reload venue order and client order id cache correctly after a reconnection event. Please see #betfair (discord) where the issue highlighted a bit better
[x] Bug fix
In production
=> Betfair bugfix: Reload cache as a dict of venue and client order ids

nautilus_trader/adapters/sandbox/execution.py, tests/integration_tests/adapters/sandbox/conftest.py
…ation
The account is initialized when creating a new SandboxExecutionClient. The account is needed in the strategy to set the leverage and determine if a margin or cash account is used.
- [x ] Bug fix (non-breaking change which fixes an issue)
Locally using the sandbox with the bybit data feed.
=> Fix sandbox account initialization

examples/live/interactive_brokers/sandbox.py, nautilus_trader/adapters/sandbox/factory.py, nautilus_trader/examples/strategies/ema_cross.py
Added example of Sandbox using IB.
=> Add Sandbox example with InteractiveBrokers

nautilus_trader/persistence/catalog/parquet.py
The docs for `ParquetDataCatalog` indicate that `fs_protocol` can be "s3", however this functionality wasn't actually supported.
All tests pass.
=> Support S3 parquet data catalog

nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/connection.py, tests/integration_tests/adapters/interactive_brokers/client/test_client.py, tests/integration_tests/adapters/interactive_brokers/conftest.py
This pull request addresses an issue with the Interactive Brokers (IBKR) reconnection mechanism. Previously, if the connection to the IB gateway or TWS was lost, either due to the nightly restart or a disrupted connection, the system was unable to successfully reestablish the connection. The changes introduced in this PR resolve this bug, ensuring that the connection can be properly restored after such interruptions.
Passes all integration tests. Also worked as anticipated while paper trading.
=> Fix IBKR reconnection after gateway/TWS disconnection

nautilus_trader/backtest/matching_engine.pyx, tests/unit_tests/backtest/test_exchange_glbx.py
Fixes following bug when there are only closed positions.
```
nautilus_trader\\backtest\\matching_engine.pyx:1261: in nautilus_trader.backtest.matching_engine.OrderMatchingEngine.iterate
???
nautilus_trader\\backtest\\matching_engine.pyx:1331: in nautilus_trader.backtest.matching_engine.OrderMatchingEngine.iterate
???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
>   ???
E   ValueError: invalid `PositionSide`, was FLAT
nautilus_trader\\model\\orders\\base.pyx:807: ValueError
```
Added test and resolved the exception.
=> Fix position closing on contract expiration

nautilus_core/common/src/timer.rs
Fix timer canceling when it is already expired.
Paper trading with a throttler ran into an issue as discussed on Discord. Error is now resolved.
=> Fix timer cancel when it is already expired

nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/connection.py, tests/integration_tests/adapters/interactive_brokers/client/test_client.py
As reported in the Interactive Brokers Discord channel, resubscribing to subscriptions after a reconnect only worked for 1 of multiple subscriptions. This PR fixes that issue and also refactors the lifecycle methods, which are synchronous functions that need to call asynchronous functions. 
Tests pass and validated with live trading.
=> Fix IBKR resubscribing after disconnection

nautilus_trader/adapters/interactive_brokers/client/order.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_order.py
Fix for IBOrder attributes assignment for incoming order update when request is not present.
Added test.
=> Fix IBOrder attributes assignment

nautilus_core/Cargo.lock, nautilus_core/infrastructure/Cargo.toml, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs
- we recently had problems with Postgres infrastructure e2e tests  which are run in a parallel manner and change the state of the database that all tests are using (in test you expect one state of the database but other parallel test running changes it independently) 
- the solution is to run the tests sequentially and design some mutex synchronization system, but `serial_test` library already does something like that and its perfect for this usecase
=> Add serial attribute in Postgres infrastructure tests

nautilus_core/core/src/deserialization.rs, nautilus_core/core/src/lib.rs, nautilus_core/model/src/events/order/accepted.rs, nautilus_core/model/src/events/order/cancel_rejected.rs, nautilus_core/model/src/events/order/canceled.rs, nautilus_core/model/src/events/order/expired.rs, nautilus_core/model/src/events/order/modify_rejected.rs, nautilus_core/model/src/events/order/pending_cancel.rs, nautilus_core/model/src/events/order/pending_update.rs, nautilus_core/model/src/events/order/rejected.rs, nautilus_core/model/src/events/order/triggered.rs, nautilus_core/model/src/events/order/updated.rs
Because of the Rust migration, some of these Rust structs have bool fields set as `u8` to be compatible with C representation of boolean with FFI. This can also happen pretty often in Cython <-> Rust conversion that is being done in Postgres adapter.
This poses some problems in deserialization from dicts or strings to these native Rust types. One way to handle this discrepancy is to create a custom deserializer that will convert bools to `u8` 
We also have to take into account that we can receive bool and normal integer
- created `BoolVisitor` which will be used as a deserializer with `serde`attribute `deserialize_with` on most of the `reconciliation` `u8` fields
=> Deserialize bool to u8 in Rust order events

nautilus_trader/adapters/sandbox/config.py, nautilus_trader/adapters/sandbox/execution.py, nautilus_trader/adapters/sandbox/factory.py
Add `bar_execution` option to the `SandboxExecutionClient` to disable processing internally aggregated bars by the matching engine.
The default is set to use the bars to be consistent with the current behaviour.
Locally running paper trading with the Bybit exchange. Subscribing to quote ticks, trade ticks and internally aggregated bars.
=> Add bar_execution option to SandboxExecutionClient (fixes #1645)

nautilus_core/model/src/python/events/order/accepted.rs, nautilus_core/model/src/python/events/order/cancel_rejected.rs, nautilus_core/model/src/python/events/order/canceled.rs, nautilus_core/model/src/python/events/order/denied.rs, nautilus_core/model/src/python/events/order/emulated.rs, nautilus_core/model/src/python/events/order/expired.rs, nautilus_core/model/src/python/events/order/filled.rs, nautilus_core/model/src/python/events/order/initialized.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/modify_rejected.rs, nautilus_core/model/src/python/events/order/pending_cancel.rs, nautilus_core/model/src/python/events/order/pending_update.rs, nautilus_core/model/src/python/events/order/rejected.rs, nautilus_core/model/src/python/events/order/released.rs, nautilus_core/model/src/python/events/order/submitted.rs, nautilus_core/model/src/python/events/order/triggered.rs, nautilus_core/model/src/python/events/order/updated.rs
After the recent changes https://github.com/nautechsystems/nautilus_trader/commit/2526448a5d9b2783b78d6468de31a81b7af992ef in order event  pyo3 conversion `getter` attribute was missing as you cannot use `.getattr` on function `type_str`. Instead of that we can use `__name__` or `__class__` attribute, and remove all `type_str` function from pyo3 classes
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PyErr
{ type: <class 'TypeError'>, 
value: TypeError("'builtin_function_or_method' object cannot be converted to 'PyString'"), 
traceback: None }
```
=> Fix order event object conversion

nautilus_core/persistence/src/backend/session.rs
Use `ORDER BY ts_init` in default sql query. Closes #1515 
By default datafusion reads row groups out of order for large files. The test files use in CI are small and don't show this so it was missed. From discussion in https://github.com/apache/datafusion/issues/10572, there are two ways to fix this and using ORDER BY clause is the recommended way.
Tested with sample data to ensure ordering is maintained.
=> Order by ts_init to read row groups in order

nautilus_trader/adapters/interactive_brokers/historic/client.py
Temporal fix for the bug that leads to endless loop at the end of day when downloading tick-level historical data from Interactive Brokers.
if min_timestamp.floor("S") == max_timestamp.floor("S"):
max_timestamp = max_timestamp.floor("S") + pd.Timedelta(seconds=1)
the original related code here only works in the following situation:
but doesn't work in the following situation:
Temporal fix. There must be better way than mine...
=> Fix IB tick level historical data downloading

nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/parsing/execution.py
Adds Support for Market On Close (MOC) and Limit On Close (LOC) Order Types in Interactive Brokers Adapter.
Tested live.
=> Add support for MOC and LOC order types in IB

tests/integration_tests/adapters/interactive_brokers/conftest.py, tests/integration_tests/adapters/interactive_brokers/mock_client.py, tests/integration_tests/adapters/interactive_brokers/test_execution_order_transform.py
This PR refines the mocking approach in the Interactive Brokers integration tests, enabling the creation of more sophisticated tests essential for all components of the Interactive Brokers adapter. Additionally, it includes new tests for order transformation.
=> Refactor mocks in Interactive Brokers integration tests

nautilus_trader/adapters/bybit/schemas/ws.py, tests/integration_tests/adapters/bybit/test_ws_decoders.py
The `parse_to_deltas` method was incorrectly storing the bids twice.
Subscribing to deltas live and storing in a catalog.
=> Fix parsing Bybit deltas

nautilus_trader/data/config.py, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/test_kit/stubs/data.py, tests/unit_tests/backtest/test_config.py, tests/unit_tests/data/test_engine.py
Buffer deltas until the F_LAST flag is set for a delta. This option is configurable and disabled by default to keep the current behavior.
Fixes #1578
Adding unit tests
=> Add DataEngine deltas buffering until F_LAST flag

nautilus_trader/adapters/sandbox/execution.py
The current implementation of the sandbox execution adapter depends on a global variable called SANDBOX_INSTRUMENTS
In the IBKR example it mentions that all the instruments must be from the same venue
Indeed this is true and the sandbox adapter will fail if you have adapters for more than one venue.
This is problematic for IBKR because the venues are often different e.g. NASDAQ, NYSE, CME etc.
I have modified the execution adapter when its loading to filter the global SANDBOX_INSTRUMENTS to just those instruments that match the venue the adapter is being configured for.
I have a local sandbox designed to work with IB that loads instruments on multiple venues (ARCA, NASDAQ) because it trades multiple stocks that …
=> Filter SANDBOX_INSTRUMENTS to match the execution venue

nautilus_trader/adapters/interactive_brokers/config.py
I've updated class parameter documentation in an attempt to clarify meanings. My assumption is that IB Gateway or TWS can be dockerized, and that the port used on the surface of the container to provide access to API services may vary, but that common defaults should be called out (4002/4001; 7497/7496).
This request may be updated as further information/changes are received from pending changes to the adapter config classes.
No code changes were made, so no testing was performed. Documentation changes were partially confirmed through [Discord chat](https://discord.com/channels/924497682343550976/949809536108228609/1247185313760022549), but should be verified for accuracy in interpretation.
=> Update InteractiveBrokersGatewayConfig docs

nautilus_core/persistence/src/backend/kmerge_batch.rs, nautilus_core/persistence/src/backend/session.rs
Choosing the right combination of query and config to achieve high perf with constant mem usage. This gives a 50% improvement over single and multi stream benchmarks.
Ran benchmarks and smaller tests in experiments repo[^1]. The best combination is no order by clause and turning off repartitioning.
| order | repartition | wall time (s) | memory (mb) | read sorted order |
| -- | -- | -- | -- | -- |
| true | true | 1.24 | 654 | ✅ |
| true | false | 1.65 | 944 | ✅ |
| false | false | 0.55 | 45 | ✅ |
| false | true | 0.41 | 151 | ❌ |
[^1]: https://github.com/nautechsystems/nautilus_experiments/tree/efficient-query
=> Fix streaming backend mem usage

nautilus_trader/adapters/bybit/providers.py, nautilus_trader/adapters/bybit/schemas/account/fee_rate.py
- added `baseCoin` field for `BybitFeeRate` struct
- target fee rate in Bybit instrument parsing now also searches for base coin check for options parsing
- after that fee rates for all instrument types are defined and can depend on symbol or base coin
- removed bybit option parsing log warning and skip and pushed it further in parse_option_instrument which will be done in later PRs
https://bybit-exchange.github.io/docs/v5/account/fee-rate
**All Bybit instrument fee rates**
**Option log warning**
=> Add base coin for fee rate parsing in Bybit adapter

docs/developer_guide/environment_setup.md
cargo performs frequent recompiles because of a difference in Python path between CLI and rust analyzer environments. [^1]
Ran cli cargo build and made then cargo check using rust analyzer in vs code, only relevant changes were compiled.
[^1]: https://github.com/PyO3/pyo3/issues/1708
=> Add PYO3_PATH configuration to reduce spurious compiles

nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/models/general.rs, nautilus_core/infrastructure/src/sql/models/types.rs, nautilus_core/infrastructure/src/sql/queries.rs, schema/tables.sql
It is a good practice to keep the same name for the primary key column, for example `id`. It keeps schema clean and organized, and follows best practices. This can also help later for possible parametrized queries or CRUD generators as you know `id` column name is reserved for the primary identifier name.
- refactor `general` and `currency` tables to have `id` as the primary column name and propagated these changes in Postgres rust code and tests
=> Change id as column name for primary key on all Postgres tables

RELEASES.md, docs/integrations/ib.md, examples/live/interactive_brokers/connect_with_dockerized_gateway.py, examples/live/interactive_brokers/connect_with_tws.py, examples/live/interactive_brokers/historic_download.py, examples/sandbox/interactive_brokers_sandbox.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/gateway.py, nautilus_trader/adapters/interactive_brokers/historic/client.py, nautilus_trader/examples/strategies/subscribe.py, tests/integration_tests/adapters/conftest.py, tests/integration_tests/adapters/interactive_brokers/client/test_client.py, tests/integration_tests/adapters/interactive_brokers/conftest.py, tests/integration_tests/adapters/interactive_brokers/mock_client.py, tests/integration_tests/adapters/interactive_brokers/test_gateway.py
The InteractiveBrokersGateway has been renamed to `DockerizedIBGateway` to better reflect its purpose. Additionally, the start parameter has been removed. This commit also updates how it manages the connection to TWS or Gateway, which now requires explicit connection parameters unless using `DockerizedIBGatewayConfig`. The documentation has been updated, and a simplified example has been added.
Existing tests pass and tested live.
=> Refactor InteractiveBrokers client and gateway configuration

nautilus_trader/adapters/interactive_brokers/providers.py
Fixes instrument loading using `load_contracts`  when there is no `load_ids` provided.
=> Improve InteractiveBrokersInstrumentProvider contract loading

nautilus_trader/adapters/interactive_brokers/factories.py
This caused the exec-client to stop working. (or any second client being created through the gateway). This made the bot completely nonfunctional.
The factories use `get_cached_ib_client`, but since the port value was being set only on the first run of the function (due to the global `GATEWAY` variable). On the second run of the function, e.g. if another factory tried to create a new client, it was causing the port to be set to the default value `None`. This caused that a different client_key was created with the port value being `None`, as a result the code creates a new `InteractiveBrokersClient` with the port `None`, this obviously fails and the bot can't start the execution client.
=> Fix Interactive Brokers multiple gateway clients

nautilus_core/common/src/testing.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs
- created function `wait_until_async` which waits for the result of some `Future` to return boolean result
- replaced `tokio` sleep function with proper condition in each Rust E2E Postgres tests
=> Add wait_until_async in Postgres cache E2E Rust tests

nautilus_core/common/src/cache/core.rs, nautilus_core/common/src/cache/database.rs, nautilus_core/infrastructure/src/python/sql/cache_database.rs, nautilus_core/infrastructure/src/redis/cache.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs
- changing the signature of Rust cache `load_*` types of functions to return `Option`, and refactoring corresponding functions to work in both Postgres and Redis cache database adapter
- switched to unbounded channel in `PostgresCacheDatabase` for inter-thread communication to use sync interface
- starting to implement trait `CacheDatabaseAdapter` for `PostgresCacheDatabase` which has sync interfaces compared to `PostgresCacheDatabase` which is using async `sqlx` methods
- removed `await` in Postgres Rust E2E tests
=> Refactor Postgres Rust cache database with sync pattern

nautilus_core/Cargo.lock, nautilus_core/infrastructure/Cargo.toml, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/pg.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs
Small cosmetical changes that include:
- adding the `Copy` trait to `PostgresCacheDatabase`
- introducing `derive_builder` and `Default` trait impl to `PostgresConnectOptions`
- moving factory functions `test_cache_database_postgres.rs` closer to project source in `sql/cache_database.rs` so that they can be resued by other E2E Rust pg tests
=> Refactor PSQL cache database test factory

nautilus_trader/adapters/binance/common/execution.py
fix bug for BinanceSymbol for live trading. 
_get_cache_active_symbols adds BinanceSymbol to active_symbols, when instantiating BinanceSymbol, BinanceSymbol was passed in instead of str type, which caused an error at checking symbol by `PyCondition.valid_string(symbol, "symbol")`
```python
TypeError(Argument 'argument' has incorrect type (expected str, got BinanceSymbol))
Traceback (most recent call last):
File "/Users/ross/miniconda3/lib/python3.11/site-packages/nautilus_trader/live/execution_client.py", line 467, in generate_mass_status
reports = await asyncio.gather(
^^^^^^^^^^^^^^^^^^^^^
File "/Users/ross/miniconda3/lib/python3.11/site-packages/nautilus_trader/adapters/binance/common/execution.py", line 502, in generate_fill_reports
response = await …
```
=> Fix Binance active_symbols type miss matching

nautilus_core/.config/nextest.toml, nautilus_core/Cargo.lock, nautilus_core/infrastructure/Cargo.toml, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs
Nextest supports test groups to specify concurrency and the number of threads to target test groups, basically mimicking serial execution of certain groups of tests. This is exactly what we need as Postgres Rust E2E tests are using shared resource and state with parallel tests execution might be different from what we expect
- created new file `.config/nextest.toml` in `nautilus_core` to add `serial-tests` test group
- removed `serial_test` crate and corresponding attribute in `test_cache_database_postgres`
- rename tests to `serial_tests` 
Running `cargo nextest show-config test-groups` now shows
=> Add serial test group to Rust nextest runner for Postgres E2E tests

nautilus_core/common/src/cache/core.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_postgres.rs
- added missing currencies reset in cache reset
- implement sync `load_orders` for `PostgresCacheDatabase` and corresponding PSQL query that fetches distinct client order ids
- created a new E2E test file `test_cache_postgres.rs` which will tests Rust cache with PSQL cache database adapter
- added `cache_instruments` and `cache_orders` Rust Cache tests
=> Add initial Rust cach tests in Postgres

nautilus_trader/backtest/matching_engine.pyx
…der books
When the strategy subscribes to both quote deltas and order book deltas, the matching engine applies both quotes as well as deltas to the order book which is incorrect.
In case of the Bybit venue, quote ticks are pushed at a higher frequency than deltas. Hence, some strategies would like to get the latest top of the book quotes, and also build indicators on top of the full order book.
The matching engine should use a L1_MBP order book when subscribing to both quotes and deltas, because the quotes are sent earlier introducing a lookahead bias.
Locally running backtests
=> Fix OrderMatchingEngine processing by book type for quotes and deltas

nautilus_core/network/src/socket.rs, nautilus_core/network/src/websocket.rs
Fixes #1732 : Network clients can use AtomicBool instead of <Arc<Mutex<bool>>
`make pre-commit`
=> Enhancement: Changed <Arc<Mutex<bool>> to AtomicBool

nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/mod.rs, nautilus_core/infrastructure/src/sql/models/accounts.rs, nautilus_core/infrastructure/src/sql/models/mod.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/model/src/accounts/any.rs, nautilus_core/model/src/orders/any.rs, nautilus_core/model/src/types/currency.rs, nautilus_core/model/src/types/money.rs, schema/tables.sql
- added new `DatabaseQuery` command for Postgres Cache adapter `AddAccount`
- implement sync cache database interface `add_account` and `load_account`
- introduces new tables `account` and `account_event` in PSQL schema
- implemented `FromRow` trait on `AccountEventModel` for correct transformation of Postgres item to native Rust struct
- added new `test_add_account` in `test_cache_database_postgres.rs` tests
- type change to owner `String` in impl `Deserialize for `Money` and `Currency`
=> Implement PSQL Rust cache database adding accounts

nautilus_core/common/src/cache/core.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_postgres.rs, nautilus_core/model/src/accounts/any.rs, nautilus_core/model/src/accounts/cash.rs
- cache `add_*` method should also register correct indexes what is missing in current Rust Cache implementation, see https://github.com/nautechsystems/nautilus_trader/blob/dddfd4cef8b592554e654be242dcb4545d7f173c/nautilus_trader/cache/cache.pyx#L1403
- added few unit Rust cache tests around accounts
- implemented sync `load_accounts`
- added `test_cache_accounts` to `test_cache_postgres.rs`
=> Implement and test Rust cache_accounts

nautilus_core/infrastructure/src/sql/queries.rs, schema/tables.sql
- added an idempotent query to create potential records in `trader` table if it doesn't exist
- make `trader_id` column reference/foreign key in `order_event` table
- it helps strengthen the referential integrity of PSQL schema and adds the possibility of cascade delete on account events
- later these two new transactions which were added to check if both `trader` and `account` exist in add functions can be dropped and substituted with ids creation at node startup (so we don't have to try to create them at every account or order event save)
=> Make trader_id foreign key in order_events table

nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/model/src/accounts/any.rs, nautilus_core/model/src/accounts/stubs.rs, nautilus_core/model/src/events/account/stubs.rs
- added bool `updated` to `AddAccount` query command to signal that command should also check if initial record in `account_event` exists
- tested in Rust E2E if works
- some changes in cash account fixture
=> Implement PSQL Rust cache database updating accounts

nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/adapters/interactive_brokers/providers.py, tests/integration_tests/adapters/interactive_brokers/test_kit.py, tests/integration_tests/adapters/interactive_brokers/test_parsing.py
Fixes Future Options support in Interactive Brokers adapter.
Added test.
=> Add support for options on futures in Interactive Brokers adapter

nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/schemas/ws.py, tests/integration_tests/adapters/bybit/test_ws_decoders.py
Explicitly set the quote price, quote size, trade price and trade size precisions for the Bybit venue.
Subscribing to live trade data for the bybit venue. Asserting in strategy that the correct prize and size precision are used for all ticks and adding a unit test.
=> Fix Bybit parsing of trade and quote ticks for websocket messages

nautilus_core/infrastructure/src/sql/models/enums.rs, nautilus_core/infrastructure/src/sql/models/instruments.rs, nautilus_core/infrastructure/src/sql/queries.rs, schema/tables.sql
- refactored the `AssetClass` enum definition in PSQL schema to screaming snake case notation
- created a wrapper `AssetClassModel` on the enum `AssetClass` and implemented sqlx traits `Decode`, `Encode` and `Type`
- added target enum casting in INSERT enum query
=> Implement native PSQL enum mapping on AssetClass

nautilus_core/backtest/src/matching_engine.rs
- implemented event generators for `OrderMatchingEngine` in Rust
- implemented `generate_trade_ids` and `generate_trade_ids_str` for identifier generators
=> Add event generators to OrderMatchingEngine in Rust

nautilus_core/infrastructure/src/sql/models/enums.rs, nautilus_core/infrastructure/src/sql/models/orders.rs, nautilus_core/infrastructure/src/sql/queries.rs, schema/tables.sql
- added the `TrailingOffsetType` enum definition in PSQL schema
- created a wrapper `TrailingOffsetTypeModel` on the enum `TrailingOffsetType` and implemented sqlx traits `Decode`, `Encode`, and `Type`
- added target enum casting in INSERT query
=> Implement native PSQL enum mapping on TrailingOffsetType

nautilus_core/common/src/cache/database.rs, nautilus_core/infrastructure/src/redis/cache.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/mod.rs, nautilus_core/infrastructure/src/sql/models/data.rs, nautilus_core/infrastructure/src/sql/models/enums.rs, nautilus_core/infrastructure/src/sql/models/mod.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, schema/tables.sql
- added new function `load_trades` in `CacheDatabaseAdapter ` trait
- added new variant `AddTrade` in `DatabaseQuery` enum
- implemented `add_trade` and `load_trades` for `PostgresCacheAdapter`
- tested in `test_cache_database_postgres.rs`
=> Implement trade tick schema with PSQL cache database in Rust

nautilus_trader/common/component.pxd, nautilus_trader/common/component.pyx, nautilus_trader/data/engine.pyx, tests/unit_tests/msgbus/test_bus.py
The order book subscription is kept alive forever instead of closed on request. The actor is subscribing to the order book deltas, but also the data engine which is maintaining it's own order book. So there are 2 subscribers. The DataEngine._setup_order_book  sets up the subscription, but doesn't unsubscribe from the subscription later.
The message bus exposes the number of subscriptions for a certain topic, and during the unsubscription process, the data engine checks if the internal order book subscription is the last one.
During development of dYdX adapter. The unsubscribe_order_book_deltas() was not called by the DataEngine.
=> Fix unsubscribing from order book deltas

nautilus_core/adapters/src/databento/decode.rs, nautilus_core/common/src/cache/database.rs, nautilus_core/data/src/aggregation.rs, nautilus_core/infrastructure/src/redis/cache.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/models/data.rs, nautilus_core/infrastructure/src/sql/models/enums.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/model/src/data/bar.rs, nautilus_core/model/src/data/stubs.rs, nautilus_core/model/src/python/data/bar.rs, nautilus_core/persistence/src/arrow/bar.rs, schema/tables.sql
- added new function `load_bars` in `CacheDatabaseAdapter ` trait
- added new variant `AddBar` in `DatabaseQuery` enum
- implemented `add_bar` and `load_bars` for `PostgresCacheAdapter`
- new enums in PSQL schema related to bar aggregation and price type
- tested in `test_cache_database_postgres.rs`
=> Implement bar schema with PSQL cache database in Rust

nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_engine.py
Add assertions to validate that the subscriptions have been removed at client level and create fix for unsubscribing to order book snapshots.
Unit tests
=> Fix unsubscribing to order book snapshots

nautilus_core/common/src/msgbus/mod.rs, nautilus_core/common/src/msgbus/stubs.rs, nautilus_core/common/src/python/handler.rs
The idea was to test if an appropriate message handler was called with generic `&dyn Any` message object, for example in 
the messagebus `send` method.  To do that custom `CallCheckMessageHandler` was defined which sets the flag to true if the handler is invoked. The most problem I faced was into downcasting to `Any`
- created the `stub` file which will contain these testing message handlers which will be used by other components across codebase
-  modified `MessageHandler` so that it inherits from `Any` trait,  which allows for type casting using `Any`'s methods like `downcast_ref`
- with that change, we better support type casting through `Any` and provide an `as_any` method for easier type casting.
=> Improve message handler invoked testing

nautilus_core/Cargo.lock, nautilus_core/backtest/Cargo.toml, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/common/src/msgbus/mod.rs, nautilus_core/common/src/msgbus/stubs.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/model/src/events/order/any.rs, nautilus_core/model/src/instruments/any.rs, nautilus_core/model/src/instruments/futures_contract.rs, nautilus_core/model/src/instruments/mod.rs, nautilus_core/model/src/instruments/stubs.rs
- changed even type in `generate_order_*` functions to `OrderEventAny`
- defined constant `EXPIRING_INSTRUMENT_TYPES`
- bootstrapping `process_order` trading command function with order exists check, activation and expiration check
- created test suite with stub `OrderMatchingEngine` in Rust with tests `test_order_matching_engine_instrument_already_expired` and `test_order_matching_engine_instrument_not_active`
- added generic message handler `MessageSavingHandler` which saves messages in list
=> Bootstrapping process_order for OrderMatchingEngine in Rust

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/model/src/orders/any.rs
- precision checks for quantity, price, and trigger price in `process_order` function with correct events generated
- `OrderMatchingEngine` test reorganization - wanted to keep tests cleaner and shorted, so fixtures and utils getter function are separated
=> Implement precision checks in OrderMatchingEngine in Rust

nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/infrastructure/tests/test_cache_postgres.rs, schema/tables.sql, tests/integration_tests/infrastructure/test_cache_database_postgres.py
- make column  `instrument_id` in `order_events` table reference to `instrument` table
- fix psql cache tests as instrument now needs to be inserted before order events
=> Make instrument_id foreign key in order_events table

nautilus_core/common/src/cache/database.rs, nautilus_core/common/src/cache/mod.rs, nautilus_core/infrastructure/src/python/sql/cache_database.rs, nautilus_core/infrastructure/src/redis/cache.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/models/general.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/infrastructure/tests/test_cache_postgres.rs, schema/tables.sql
- changed signature of `add_order` in trait `CacheDatabaseAdapter` to accept optional `client_id`
- implemented `load_index_order_client` function of cache database
- added `OrderEventOrderClientIdCombination` struct to help with parsing distinct order client ids query
- created new PSQL table `client` and put and foreign key column `client_id` in table `order_event`
=> Implement load_index_order_client in Postgres cache database 

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/model/src/orders/any.rs
- added position initialization if it exists in `process_order`
- added a check for not shorting an equity without a MARGIN account and generating corresponding `OrderRejected` event
- test `test_order_matching_engine_error_shorting_equity_without_margin_account`
- bootstrapped target order processing functions
=> Check short selling Equity without MarginAccount in OrderMatchingEngine

nautilus_trader/persistence/catalog/parquet.py
Fixed creation of instrumend_id folder when writing PyO3 bars in catalog.
Fixed by checking an object has a bar_type instead of checking it's a Bar, the new check emcompasses both types of bars (cython and pyo3).
Can be checked using the code in the linked issue:
https://github.com/nautechsystems/nautilus_trader/issues/1811
=> Fix creation of instrumend_id folder when writing PyO3 bars in catalog

nautilus_trader/persistence/writer.py, tests/integration_tests/adapters/betfair/test_kit.py, tests/unit_tests/persistence/test_streaming.py
As described in this issue below errors could happen in a backtest with the high-level API when using StreamingFeatherWriter with only one custom data type. 
https://github.com/nautechsystems/nautilus_trader/issues/1804
This was because the writer was still trying to write every types at run time, because a check now added was missing.
Tested on my own code and added a new test.
=> Fix handling include_types option in StreamingFeatherWriter

nautilus_core/network/src/http.rs, nautilus_core/network/src/python/http.rs
Set an optional timeout for HTTP requests instead of using no timeout. 
When an HTTP server does not respond, a live execution cannot be stopped by pressing CTRL-C. With a timeout, the request times out, and the live execution exits as expected. This also gives the possibility to retry requests from the adapter side.
By calling HTTP endpoints of dYdX. The testnet is very slow and sometimes never responds.
=> Add optional timeout for HTTP requests in Rust

nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_streaming.py
Added the function convert_stream_to_data in ParquetDataCatalog that allows to convert some streamed data to backtest data. This is useful when custom data is produced by an actor for example so it can be reused in other backtests.
Related to this issue https://github.com/nautechsystems/nautilus_trader/issues/1796
Tested on my own code as well as added a new test
=> Add conversion function of streamed data to backtest data

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/model/src/orders/any.rs, nautilus_core/model/src/orders/stubs.rs
- added new util function `market_order_reduce` in `TestOrderStubs` for market reduce orders, 
- implemented `is_reduce_only` , `is_buy` and `is_sell` in `OrderAny`
- added reduce only checks in `process_order` for order matching engine
- tested in `test_order_matching_engine_reduce_only_error`
=> Add reduce only checks in OrderMatchingEngine

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/common/src/cache/mod.rs, nautilus_core/model/src/orders/any.rs
- changed the type of `cache` in `OrderMatchingEngine` to `Rc<RefCell<Cache>>`
- created a scope for borrowing `cache` in `process_order` as later we need to drop this borrowed cache as later `process_*_order` need to have mutable access to self
- implemented contingent order checks
- simulated OTO order rejected in `test_order_matching_engine_contingent_orders_errors`
=> Add contingent order check for order processing in OrderMatchingEngine

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/execution/src/matching_core.rs, nautilus_core/model/src/orders/any.rs, nautilus_core/model/src/orders/stubs.rs
- implemented linked orders check for  `OrderMatchingEngine` in Rust and test `test_process_order_when_closed_linked_order`
- `engine_config` fixture in tests
=> Add linked orders check in OrderMatchingEngine

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/execution/src/matching_core.rs
- finished `process_market_order` with checks if the market is initialized 
- bootstrapped others missing methods
- tested in `test_process_market_order_no_market_rejected`
=> Implement process_market_order in OrderMatchingEngine

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/lib.rs, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/backtest/src/models/fee.rs, nautilus_core/backtest/src/models/latency.rs, nautilus_core/backtest/src/modules/mod.rs
- created `SimulatedExchange` Rust struct with the same methods as Cython counterpart, and implemented `add_instrument` function with correct order matching engine creation and initialization
- constructor method `new` on `OrderMatchingEngineConfig`
- `FeeModelAny` with two variants: `Fixed` and `MakerTaker`
- created empty struct for `LatencyModel` and trait `SimulationModule`
- changed the type of msgbus in `OrderMatchingEngine` to `Rc<RefCell<MessageBus>>`
=> Bootstrap SimulatedExchange in Rust

nautilus_trader/model/custom.py, tests/unit_tests/model/test_custom_data.py
Improved customdataclass constructor to be able to use positional arguments after ts_event and ts_init
Modified one test to check it's working as expected. Checked on my own code as well.
=> Improve customdataclass constructor to use positional arguments 

nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/core/data.pyx, nautilus_trader/persistence/writer.py, tests/unit_tests/common/test_actor.py
Added functionalities to be able to use Signals in actors. Subscribe signal allows to subcribe to all or one signal of a given name which will be received by the on_data callback in an actor. is_signal is a method of Data to check that a received data in on_data is a signal or a signal of a give name.
Also added more possible basic value types to SignalData.
- New feature (non-breaking change which adds functionality
Tested on my own code and added tests
=> Implement subscribe SignalData for Actor

docs/integrations/dydx.md, nautilus_trader/adapters/dydx/execution.py
- Use an alias for the gRPC `Order` and import the Nautilus `Order` class for type-checking which was causing a naming conflict.
- Typo in the documentation
Unit tests and running a live example on the testnet.
=> Use an alias for Order in the dYdX adapter

nautilus_trader/adapters/dydx/http/client.py
Catch HttpError and HttpTimeoutError exception when performing HTTP requests for the dYdX adapter instead of a catch-all exception.
Using the live example.
=> Catch HttpError and HttpTimeoutError exception when performing HTTP requests for the dYdX adapter 

nautilus_core/common/src/cache/mod.rs, nautilus_core/data/src/aggregation.rs, nautilus_core/data/src/client.rs, nautilus_core/data/src/engine/mod.rs, nautilus_core/indicators/src/stubs.rs, nautilus_core/infrastructure/src/sql/queries.rs, nautilus_core/model/src/data/bar.rs, nautilus_core/model/src/data/mod.rs, nautilus_core/model/src/data/stubs.rs, nautilus_core/model/src/ffi/data/bar.rs, nautilus_core/model/src/python/data/bar.rs, nautilus_core/persistence/tests/test_catalog.rs, nautilus_trader/backtest/matching_engine.pyx, nautilus_trader/cache/cache.pyx, nautilus_trader/core/includes/model.h, nautilus_trader/core/rust/model.pxd, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/engine.pyx, nautilus_trader/model/data.pxd, nautilus_trader/model/data.pyx, tests/unit_tests/data/test_aggregation.py, tests/unit_tests/model/test_bar.py
Refactor BarType for aggregating bars into other bars
A usage example is 
```python
bar_type = BarType.from_str(f"ESU4-2-MINUTE-LAST-INTERNAL@ESU4-1-MINUTE-LAST-EXTERNAL")  
self.subscribe_bars(bar_type)
```
My own code and tests
I haven't updated the doc yet
=> Refactor BarType for aggregating bars into other bars 

docs/integrations/dydx.md, nautilus_trader/adapters/dydx/common/common.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/grpc/order_builder.py
Use a `DYDXOrderTags` dataclass to add additional order attributes following the `IBOrderTags` class.
dYdX makes a distinction between short-term orders and long-term orders (or stateful orders). 
Strategies can construct these 2 types of orders by attaching a tag to an order using `DYDXOrderTags`.
Testing using the testnet for both short-term and longterm orders.
=> Implement stateful orders for dYdX

nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/grpc/account.py
Implement submit_order_list for the dYdX adapter and ensure that the sequence number of the wallet is corrected when a transaction fails by using the gRPC account method.
Using live example and submitting an order list with the example volatity strategy
=> Implement submit_order_list for dYdX

nautilus_trader/adapters/dydx/http/client.py, nautilus_trader/adapters/dydx/providers.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py
- Catch AioRpcError connection errors in the instrument provider. These errors sometimes occur when the DataEngine request an update of the instruments (which runs every hour).
- Fix exception message when a HttpError occurs
- Add assertions to unit test for parsing deltas
Using the live example
=> Catch AioRpcError connection errors in dYdX instrument provider

nautilus_core/model/src/python/data/bar.rs, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, tests/unit_tests/data/test_aggregation.py, tests/unit_tests/model/test_bar_pyo3.py
Make recent addition of aggregation of bars into bars in line with existing implementation, which will facilitate the aggregation of bars using other Aggregators (based on volume for example).
Add new composite methods for BarType to PyO3 integration (which was super easy compared to with cython and FFI)
Using tests
=> Update composite bars and refactor bar aggregation

nautilus_core/model/src/data/bar.rs, nautilus_core/model/src/ffi/data/bar.rs, nautilus_core/model/src/python/data/bar.rs, nautilus_trader/core/includes/model.h, nautilus_trader/core/rust/model.pxd, nautilus_trader/model/data.pyx, tests/unit_tests/data/test_aggregation.py, tests/unit_tests/model/test_bar.py, tests/unit_tests/model/test_bar_pyo3.py
The new BarType has a string representation of:
`"BTCUSDT-PERP.BINANCE-2-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL"`
Removed BarType.from_bar_types function as it could cause invalid states, or require more error management.
Tested with tests
=> Refactor composite BarType removing unattainable states

nautilus_trader/common/actor.pyx, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_aggregation.py
Allows aggregation of composite bars. For example:
```python
bar_type = BarType.from_str(f"ESU4-2-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL")
self.subscribe_bars(bar_type)
bar_type2 = BarType.from_str(f"ESU4-4-MINUTE-LAST-INTERNAL@2-MINUTE-INTERNAL")
self.subscribe_bars(bar_type2)
```
Also emitted bars from composite aggregations are now standard bars meaning without "@" only the left side is emitted as bar type.
On personal prototype, don't know how to test this feature in a test yet as it involves various parts of the system (engine, time aggregator, actor, message bus).
=> Allow chained internal bar aggregation

nautilus_core/infrastructure/src/python/sql/cache_database.rs, nautilus_core/infrastructure/src/sql/cache_database.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/network/src/python/mod.rs
- Move load PSQL cache function to trait with blocking implementation
- tests for `load` function already exist in Rust and Python
=> Move PSQL cache load function impl

nautilus_trader/model/custom.py, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/model/test_custom_data.py
Add date field to custom data decorator for partitioning
Also add **kwargs to convert_stream_to_data in order to be able to use catalog.write_data options for example `partitioning=['date'], existing_data_behavior='overwrite_or_ignore'`
Own prototype and tests
=> Add date field to custom data decorator for partitioning

nautilus_trader/adapters/dydx/execution.py, tests/integration_tests/adapters/dydx/conftest.py, tests/integration_tests/adapters/dydx/test_execution.py
Use custom client order IDs set by the strategy and fallback to generating new integers for dYdX
Unit test and live example with both custom and client order IDs generated by NT
=> Use custom client order IDs for dYdX

nautilus_trader/adapters/dydx/execution.py
Implement batch_cancel_orders for the dYdX adapter
Updating the live example to send a batch of orders to cancel.
=> Implement batch_cancel_orders for the dYdX adapter

nautilus_trader/model/custom.py, tests/unit_tests/model/test_custom_data.py
Adds an extra date field only for to_arrow serialisation used for catalogs.
Space impact of extra field is minimal with parquet as columns are compressed.
Improved an existing test
=> Add date field with customdataclass only when using to_arrow

nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, tests/unit_tests/data/test_aggregation.py
Update other aggregators than time aggregator to work with composite bars ("ESU4.GLBX-2-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL" for example) With previous refactorings only _apply_update_bar needed to be implemented for each aggregator.
For the value aggregator, the average price of open, high, low and close is used instead of price when using trades or quotes for aggregation.
Many tests have been added, similarly to existing ones
=> Update remaining aggregators to work with composite bars

.github/workflows/build.yml, poetry.lock, pyproject.toml
Pin the version of v4-proto to fix the warnings that the generated C++ proto files are out of date.
Running the live example
=> Pin v4-proto dependency for dYdX

nautilus_trader/adapters/dydx/common/enums.py, nautilus_trader/adapters/dydx/execution.py, tests/integration_tests/adapters/dydx/test_parsing.py
Filter the orders by order type and side when creating a OrderStatusReport dYdX
Unit tests and live example
=> Filter orders for dYdX OrderStatusReports

nautilus_trader/common/actor.pyx, nautilus_trader/data/engine.pyx
Some functions in Actor and Engine need to call bar_type.standard() instead of bar_type when using composite bars
- Bug fix (non-breaking change which fixes an issue
Tested on EmaCross strategy, tests existing as well
=> Fix request for composite bars

nautilus_trader/data/aggregation.pyx, tests/unit_tests/data/test_aggregation.py
Modified price value to average of high low close instead of open high low close in the ValueBarAggregator when using bars as source data.
This is to avoid having the close value being used a second time in the next open value, also similarly to the VWAP price.
Tests have been updated to reflect the new formula.
Such syntax needed to be used in order to compare decimal numbers because of dividing by 3.
```
expected = Decimal("40001.11")
assert (
aggregator.get_cumulative_value().quantize(expected, rounding=ROUND_HALF_UP) == expected
)
```
=> Update average price in ValueBarAggregator when using bars

nautilus_core/infrastructure/src/sql/pg.rs, schema/functions.sql
- added `functions.sql` which will store Postgres functions written in procedural `plpgsql` language. These functions can be later used by the Postgres related Rust code and the other queries
- refactor `init_postgres` function to also account for these functions when splitting with the target delimiter 
- changed logging from `tracing` to `log`
=> Introduce PSQL functions to Postgres schema and Nautilus CLI

nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/persistence/config.py, nautilus_trader/persistence/writer.py, nautilus_trader/system/kernel.py, tests/unit_tests/backtest/test_config.py, tests/unit_tests/common/test_actor.py
This PR adds file rotation functionality to the StreamingFeatherWriter class and improves time management and file naming. #1945 
Key changes include:
Implementation of file rotation based on size, time interval, and scheduled dates.
Use of a Clock object for time management, improving flexibility and testability.
Addition of timestamps to filenames for better organization and identification.
Tracking of file sizes and creation times to support rotation functionality and provide more information.
Addition of methods to query current file information and next rotation time.
The code undergoes testing in both live trading and backtesting processes. It functions correctly in live trading. However, in backtesting, there is an issue with the initialization …
=> Improve StreamingFeatherWriter to support file rotation and better me management

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/core/src/correctness.rs, nautilus_core/model/src/ffi/orderbook/book.rs, nautilus_core/model/src/orderbook/aggregation.rs, nautilus_core/model/src/orderbook/book.rs, nautilus_core/model/src/python/orderbook/book.rs
- implemented `best_bid_price` , `best_ask_price`  and `process_quote_tick` in `SimulatedExchange`
- implemented `process_quote_tick` in `OrderMatchingEngine`
- added tests `test_venue_mismatch_between_exchange_and_instrument`, `est_cash_account_trading_futures_or_perpetuals` and `test_exchange_process_quote_tick` 
- added `Display` trait bound in `check_equal` function
- pushed two orderbook aggr function `update_book_with_quote_tick` and `update_book_with_trade_tick`, `update_book_bid` and `update_book_ask` inside `Orderbook` struct
=> Implement quote tick processing for SimulatedExchange

nautilus_core/common/src/logging/logger.rs, nautilus_core/common/src/logging/writer.rs
Use unbuffered stdout/err logger for smooth terminal output and remove explicit flushes
Tests were run
=> Use unbuffered stdout/err logger

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/execution/src/matching_core.rs, nautilus_core/model/src/data/bar.rs
- implements `process_bar` function of `SimulatedExchange' and same function in `OrderMatchingEngine`
- added test `test_exchange_process_bar_last_bar_spec` with the last price aggregated bar testing and test `test_exchange_process_bar_bid_ask_bar_spec` with bid/ask aggregated bars
=> Implement bar processing for SimulatedExchange

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/websocket/client.py
- Log error when the message_id is not increasing for dYdX
- The `message_id` is not strictly monotonically increased when subscribing to multiple instruments or multiple data streams (deltas/trade ticks). However, it must be strictly increasing for the same instrument and data type.
- Add `handler_reconnect` (not yet in use)
- Add `is_connected` and `is_disconnected` public methods to websocket client
- Do not remove the deltas symbol from the internal list of subscriptions when resubscribing to the order book
- Reconnect the websocket client when a ping frame has not been received for at least 40 seconds
Live example
=> Refine message handling for dYdX

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/websocket/client.py
Fix resubscribing to orderbooks for dYdX and fix reconnecting 
Live example
=> Fix resubscribing to orderbooks for dYdX

examples/backtest/databento_option_greeks.py, nautilus_trader/adapters/databento/data_utils.py, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/risk/greeks.py, tests/unit_tests/persistence/test_catalog.py
Add mode option to ParquetDataCatalog.write_data. This allows for example to download new historical data and append or prepend it to an existing catalog. The existing file will be loaded in memory, then written again followed or preceded by the new data. The default write_data_mode is the same behaviour as before, called "overwrite".
- New feature (non-breaking change which adds functionality
on prototype, add write_data_mode="append" here https://github.com/nautechsystems/nautilus_trader/blob/develop/examples/backtest/databento_option_greeks.py#L60 
Added test
=> Add mode option to ParquetDataCatalog.write_data

nautilus_core/network/src/websocket.rs
Cleanup websocket running tasks (hearbeat) on disconnect command even if inner client is not alive. Closes #1980 
Needs verification
=> Cleanup websocket tasks on disconnect if it is not alive

nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/grpc/account.py
Fix generating cancel rejections for dYdX
pre-commit and live example
=> Fix generating cancel rejections for dYdX

README.md, docs/integrations/betfair.md, docs/integrations/binance.md, docs/integrations/bybit.md, docs/integrations/polymarket.md
=> Docs update

nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/model/greeks.py, nautilus_trader/risk/greeks.py
Add in the money probability field to GreeksData
This is a useful common information for knowing the relative position of the spot of the underlying of a vanilla option (call or put) with respect to the strike of an option.
Local test on prototype databento_option_greeks.py in examples/backtest
=> Add in the money probability field to GreeksData

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs
Implemented orderbook delta processing in Rust `SimulatedExchange` struct
Added new test `test_exchange_process_orderbook_deltas` in Simulated exchange Rust file
=> Implement orderbook deltas processing for SimulatedExchange

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/execution/src/matching_core.rs
In `iterate` function of `OrderMatchingEngine` we must also update `bid` and `ask` values in `OrderMatchingCore`.
Added test `test_matching_core_bid_ask_initialized`  which checks that after bid and ask orderbook delta processing, we set the correct values of bid and ask in order matching core
=> Update bid and ask in matching engine iteration

nautilus_trader/adapters/dydx/websocket/client.py
Add docs and fix rate limiting for websockets of dYdX
Live example
=> Add docs and fix rate limiting for websockets of dYdX

nautilus_trader/backtest/matching_engine.pyx
- missing `self.oms_type` in oms type checking
=> Fix check for OmsType in OrderMatchingEngine

nautilus_core/Cargo.lock, nautilus_core/model/tests/test_order_book.rs, nautilus_core/persistence/Cargo.toml, nautilus_core/persistence/tests/test_catalog.rs, nautilus_core/test_kit/src/common.rs
- refined test data getters path to use unified get test data function
- added possibility of optional `TEST_DATA_ROOT_PATH` env which can be put in `.cargo/config.toml` if test data is located somewhere else
- Run `make cargo-test` and they are working and correctly mapping the test data dir
=> Refine test data getters in Rust

nautilus_core/adapters/src/tardis/csv.rs, tests/integration_tests/adapters/tardis/test_loaders.py
- Modified the CSV parsing logic in `load_depth10_from_snapshot5` and `load_depth10_from_snapshot25` functions to use `StringRecord` for reading records.
- The current default deserialization process is quite strict. Any non-numeric characters or deviations from the expected format can result in a failure to parse, yielding None. To address this, I first read the CSV line by line into a StringRecord and then deserialize it into the TardisOrderBookSnapshot5Record struct to ensure proper parsing and handling of the data.
- Added detailed assertions for fields in both python and rust tests.
- `make cargo-test`
- `make pytest`
=> Fix TardisCSVDataLoader for snapshot5 and snapshot25

nautilus_core/backtest/src/matching_engine.rs, nautilus_core/common/src/cache/mod.rs
- implement `get_position_id` for `OrderMatchingEngine` in Rust for Hedgin Oms type
- test `test_get_position_id_hedging_with_existing_position` checks that engine correctly returns the position id which is already present in the cache
- test `test_get_position_id_hedging_with_generated_position` checks that engine correctly regenerates position id
=> Implement position getter for hedging Oms in OrderMatchingEngine

nautilus_core/cli/src/database/postgres.rs, nautilus_core/infrastructure/src/sql/cache.rs, nautilus_core/infrastructure/src/sql/pg.rs
- motivation was that `nautilus` cli should also be run without `.env` file (now it fails if file doesn't exists as envs will be null)
- we should use default development values which are hardcoded everywhere
- added logs of the Postgres connection URL used in CLI to see which database is running on
- changed the signature of `get_postgres_connect_options` if defaults are supplied, no need to return Result, as config will always exist without errors
- add `default_administrator` with root `postgres` user value, nautilus CLI will get the default values from there if no envs are found in environment
=> Improve Postgres config

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- finish `get_position_id` for `OrderMatchingEngine` in Rust for netting OMS engine type calculation
- tested in `test_get_position_id_netting`
=> Implement position getter for netting Oms in OrderMatchingEngine

nautilus_core/common/src/cache/database.rs, nautilus_core/infrastructure/src/python/sql/cache.rs, nautilus_core/infrastructure/src/redis/cache.rs, nautilus_core/infrastructure/src/sql/cache.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs
- in the trait `CacheDatabaseAdapter`, we have relaxed the signature of some functions to use immutable references. This change is possible because the `load_*` functions are read-only, and the `add_*` functions just are send data into the channel, so nothing is mutated from this function
- the exceptions are load_currencies and load_positions because the `con.keys` function from Redis requires a mutable reference.
=> Remove mutable reference in cache database trait in Rust

nautilus_core/infrastructure/src/sql/cache.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/infrastructure/tests/test_cache_postgres.rs
- removed `reset_pg_database` function as truncate/flush is doing the exact functionality
- clearing of db is removed from  `get_pg_cache_database` factory, so that users are responsible for cleaning it after usage
- as we have mutable and immutable function on `PostgresCacheDatabase` and there is no async drop in Rust currently, so we must properly clean and close the connection at the end of each test
=> Improve Postgres testing

nautilus_trader/live/node.py
Add raise_exception optional parameter to TradingNode.run in order to be able to get call stack when an error happens, defaults to False, so no default behaviour change.
- New feature (non-breaking change which adds functionality
Exsiting tests pass
=> Add raise_exception optional parameter to TradingNode.run

nautilus_trader/adapters/dydx/schemas/account/fills.py, tests/integration_tests/adapters/dydx/test_http_endpoints.py, tests/test_data/dydx/http/v4_fills.json
The fills HTTP endpoint has introduced a new field called `affiliateRevShare`.
Add unit test and live example.
=> Fix decoding fill HTTP messages for dYdX

nautilus_trader/data/aggregation.pyx, tests/unit_tests/data/test_aggregation.py
Add monthly and weekly aggregations, also taking into account historical aggregations. Similar logic by analogy to regular time intervals, monthly steps are taken using pd.Timedelta which circumvents irregular time intervals.
Added some tests
=> Add monthly and weekly bar aggregations

examples/backtest/databento_test_request_bars.py, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/config.py, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/system/config.py, nautilus_trader/system/kernel.py, tests/unit_tests/backtest/test_config.py, tests/unit_tests/data/test_aggregation.py
+ Add optional time origins for aggregation of time bars. 
Also changed default behaviour of get_start_time when aggregation step exceeds the next time frame. Now get_start_time tries to start as closely as possible to now instead of as far as possible when now was not a multiple of step. This makes more sense to me, the logic is more predictable in terms of when a bar starts. Although aggregating with a number of steps exceeding the next time frame should be an edge case.
+ Allow several catalogs in data engine for queries
+ Refine time bar aggregation's logic: improved logic around _build_on_next_tick which is used to avoid race conditions between data update and the timer, ensure that the next bar effectively falls within previous interval. Avoid creating bar when no update has …
=> Add optional time origins for time bar aggregation

nautilus_trader/adapters/dydx/endpoints/account/perpetual_positions.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/http/account.py, nautilus_trader/adapters/dydx/http/client.py, nautilus_trader/adapters/dydx/schemas/ws.py, tests/integration_tests/adapters/dydx/test_http_client.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py, tests/test_data/dydx/websocket/v4_accounts_channel_data_affiliate_rev_share.json
- Fix reconcile open orders for dYdX
- Fix the get_perpetual_positions status type
- Fix parsing account websocket messages
Live example and unit tests
=> Fix reconcile open orders and account websocket message for dYdX

nautilus_core/network/src/python/websocket.rs, nautilus_core/network/src/websocket.rs
Keep retrying to establish a websocket connection, even when the reconnection initially fails. The current behaviour is that the while loop exists, and the connection is broken completely.
Live example, turning on and off the network connecting.
=> Implement websocket reconnection retries

nautilus_trader/adapters/bybit/http/client.py
Some responses that do not have `time` field.
Such as:
- https://bybit-exchange.github.io/docs/v5/account/account-info
=> Make `BybitResponse.time` field optional

nautilus_trader/adapters/dydx/config.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/grpc/order_builder.py, nautilus_trader/adapters/dydx/websocket/client.py, nautilus_trader/core/nautilus_pyo3.pyi
… stop limit and stop market orders
Add max_reconnection_tries to data client config for dYdX and implement stop limit and stop market orders.
Live example. Submitting limit stop orders and market stop orders needs more testing. Therefore, not updating the documentation yet.
=> Add max_reconnection_tries to data client config for dYdX

nautilus_trader/adapters/dydx/common/enums.py, nautilus_trader/adapters/dydx/schemas/ws.py, tests/integration_tests/adapters/dydx/test_parsing.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py
Fix account balance and order status parsing for dYdX
Unit tests
=> Fix account balance and order status parsing for dYdX

nautilus_trader/adapters/dydx/common/enums.py, nautilus_trader/adapters/dydx/grpc/account.py, tests/integration_tests/adapters/dydx/test_parsing.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py
Fix parsing best effort opened order status for dYdX
Unit tests
=> Fix parsing best effort opened order status for dYdX

nautilus_core/Cargo.lock, nautilus_core/analysis/src/python/statistics/long_ratio.rs, nautilus_core/analysis/src/statistics/long_ratio.rs, nautilus_core/common/src/cache/mod.rs, nautilus_core/common/src/xrate.rs, nautilus_core/model/src/accounts/any.rs, nautilus_core/model/src/accounts/base.rs, nautilus_core/model/src/accounts/cash.rs, nautilus_core/model/src/events/order/any.rs, nautilus_core/model/src/events/position/mod.rs, nautilus_core/portfolio/Cargo.toml, nautilus_core/portfolio/src/manager.rs, nautilus_core/portfolio/src/portfolio.rs, nautilus_core/risk/src/engine/config.rs, nautilus_core/risk/src/engine/mod.rs
=> Port Portfolio to Rust

nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/schemas/ws.py, nautilus_trader/adapters/dydx/websocket/client.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py, tests/test_data/dydx/websocket/v4_block_height_channel_data.json, tests/test_data/dydx/websocket/v4_block_height_subscribed.json
Listen to block height websocket messages for dYdX
Instead of requesting the block height from the venue when submitting an order, keep the latest block height in a local cache to reduce the latency when placing and canceling orders.
Unit tests and live example
=> Subscribe to block height ws messages for dYdX

examples/live/databento/databento_historical_data.py, nautilus_core/adapters/src/databento/python/historical.rs, nautilus_trader/adapters/_template/data.py, nautilus_trader/adapters/betfair/data.py, nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/okx/data.py, nautilus_trader/adapters/polymarket/data.py, nautilus_trader/adapters/tardis/data.py, nautilus_trader/backtest/data_client.pyx, nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/data/client.pxd, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/live/data_client.py
Add ability to request and subscribe to databento bbo-1m and bbo-1s quotes
Also refactor of request, subscribe and unsubscribe functions to include metadata information containing a params dictionary for extra parameters in the implementation of some client methods
Added notebook example for requests. Not tested for subscribe, although here it uses a function that already is used for various schemas.
=> Add specific params for data subscriptions and requests

nautilus_trader/common/math.pyx, nautilus_trader/model/greeks.py, tests/unit_tests/common/test_math.py
- Adds missing decorator and fixes typo InterestRateCurveData
- Fixes binary search helper function used for interest rate curve interpolation 
- Added unit tests for `quadratic_interpolation`
- Tested visually
=> Fix interest rate curve custom data and interpolation

.github/workflows/build-wheels.yml, .github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/release.yml
Use `sccache` to speedup CI
- https://github.com/mozilla/sccache
Execution stats in task `Post Run sccache-cache`.
When using GitHub Actions cache as the storage for sccache, sccache frequently hits the service's rate limit, resulting in the following error: `Failed to restore: Cache service responded with 429`。
=> Add sccache in CI

nautilus_trader/adapters/dydx/common/enums.py, nautilus_trader/adapters/dydx/execution.py, tests/integration_tests/adapters/dydx/test_parsing.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py
Fix order handling for BEST_EFFORT_CANCELED messages of dYdX
Live example and unit tests
=> Fix order handling for BEST_EFFORT_CANCELED messages of dYdX

nautilus_trader/adapters/bybit/http/client.py
In some cases, `response.body` is not a JSON string, which will trigger `msgspec.DecodeError: JSON is malformed: invalid character (byte 0)`.
=> Refine BybitHttpClient error handling

nautilus_trader/adapters/bybit/websocket/client.py
During reconnection, the code creates two asynchronous tasks concurrently: `authentication` and `_subscribe_all`.
These two operations are executed in parallel.
This can result in the re-subscription request being sent before authentication is completed, leading to a `Request not authorized` error.
=> Fix Bybit WebSocket private channel reconnect

nautilus_trader/adapters/bybit/common/enums.py, tests/integration_tests/adapters/bybit/test_parsing.py
Refine `BybitEnumParser` for Bybit.
Tests added.
=> Refine `BybitEnumParser` for Bybit

nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/dydx/config.py
Add `max_ws_reconnection_tries` to exec client config for Bybit.
=> Add `max_ws_reconnection_tries` to exec client config for Bybit

examples/live/bybit/bybit_ema_cross.py, examples/live/bybit/bybit_ema_cross_bracket_algo.py, examples/live/bybit/bybit_ema_cross_stop_entry.py, examples/live/bybit/bybit_ema_cross_with_trailing_stop.py, examples/live/bybit/bybit_market_maker.py, nautilus_trader/adapters/bybit/common/constants.py, nautilus_trader/adapters/bybit/common/enums.py, nautilus_trader/adapters/bybit/common/urls.py, nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/factories.py, nautilus_trader/adapters/bybit/http/account.py, nautilus_trader/adapters/bybit/schemas/ws.py, nautilus_trader/adapters/bybit/websocket/client.py, tests/integration_tests/adapters/bybit/resources/ws_messages/private/ws_position.json, tests/integration_tests/adapters/bybit/test_ws_decoders.py
This PR introduces the ability to trade on Bybit using the [WebSocket API](https://bybit-exchange.github.io/docs/v5/websocket/trade/guideline).
The implementation is controlled by the following parameters in `BybitExecClientConfig`:
- `use_ws_trade_api` : bool, default False
- Enable or disable the use of the WebSocket API for trading. Use WS API if `True` else HTTP API.
- `use_http_batch_api` : bool, default False
- Bybit's WebSocket trading API currently does not support batch operations, only single-order handling. This parameter provides a toggle to use the HTTP batch API for order batch operations instead of the WebSocket API.
- `ws_trade_timeout_secs` : float, default 5.0
- Specifies the timeout in seconds to wait for `ACK` message from the WebSocket trading API.
- …
=> Add WebSocket API trading support for Bybit

nautilus_trader/data/engine.pyx
Bug fix, params was used instead of metadata for "bars_market_data_type"
=> Fix request_aggregated_bars

docs/getting_started/backtest_high_level.ipynb
Getting started notebook ` backtest_high_level.ipynb `needed some small updates in phase of loading data, because it was failing on some warning / errors as reported Discord: https://discord.com/channels/924497682343550976/924499913386102834/1321253768855162963
=> Fix demo notebook backtest_high_level

examples/backtest/databento_test_request_bars.py, nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_engine.py
Allow bar aggregators to persist after request_aggregated_bars for future subscriptions
- Breaking change: change of argument name from update_existing_subscriptions to update_subscriptions
Existing tests
=> Allow bar aggregators to persist after request_aggregated_bars 

nautilus_core/common/src/msgbus/mod.rs, nautilus_trader/common/component.pyx, tests/unit_tests/msgbus/test_bus.py
Improve `nautilus_trader.common.component.is_matching` exact match performance as suggested in #2150.
Also adds some more test cases.
Bug fix (non-breaking change which fixes an issue)
Existing tests are almost sufficient.
For completeness, I have also added some more tests for
1. `?` pattern which we do support
2. `[seq]` and `[!seq]` pattern which do NOT support
=> Improve message bus topic matching performance

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/schemas/ws.py
Refine parsing candles for dYdX
Unit tests
=> Refine parsing candles for dYdX

nautilus_trader/adapters/bybit/common/enums.py, nautilus_trader/adapters/bybit/common/parsing.py, nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/endpoints/account/fee_rate.py, nautilus_trader/adapters/bybit/endpoints/account/position_info.py, nautilus_trader/adapters/bybit/endpoints/account/wallet_balance.py, nautilus_trader/adapters/bybit/endpoints/asset/coin_info.py, nautilus_trader/adapters/bybit/endpoints/endpoint.py, nautilus_trader/adapters/bybit/endpoints/market/instruments_info.py, nautilus_trader/adapters/bybit/endpoints/market/klines.py, nautilus_trader/adapters/bybit/endpoints/market/server_time.py, nautilus_trader/adapters/bybit/endpoints/market/tickers.py, nautilus_trader/adapters/bybit/endpoints/market/trades.py, nautilus_trader/adapters/bybit/endpoints/trade/amend_order.py, nautilus_trader/adapters/bybit/endpoints/trade/batch_amend_order.py, nautilus_trader/adapters/bybit/endpoints/trade/batch_cancel_order.py, nautilus_trader/adapters/bybit/endpoints/trade/batch_place_order.py, nautilus_trader/adapters/bybit/endpoints/trade/cancel_all_orders.py, nautilus_trader/adapters/bybit/endpoints/trade/cancel_order.py, nautilus_trader/adapters/bybit/endpoints/trade/open_orders.py, nautilus_trader/adapters/bybit/endpoints/trade/order_history.py, nautilus_trader/adapters/bybit/endpoints/trade/place_order.py, nautilus_trader/adapters/bybit/endpoints/trade/set_trading_stop.py, nautilus_trader/adapters/bybit/endpoints/trade/trade_history.py, nautilus_trader/adapters/bybit/factories.py, nautilus_trader/adapters/bybit/http/asset.py, nautilus_trader/adapters/bybit/http/market.py, nautilus_trader/adapters/bybit/loaders.py, nautilus_trader/adapters/bybit/providers.py
Refine imports for type hints in Bybit.
=> Refine imports for type hints in Bybit

nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_streaming.py
Update `convert_stream_to_data` to allow converting `live` data and dir structure data types (`trade_tick`, `orderbook_deltas`).
Test added.
=> Handle directory and live streams to catalog

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/schemas/account/address.py
Refine margin balance report for dYdX
Live example and existing unit tests
=> Refine margin balance report for dYdX

nautilus_trader/adapters/dydx/common/types.py, nautilus_trader/adapters/dydx/data.py
- Add DYDXInternalError data type for dYdX. The data indexer regularly throws internal errors resulting in incorrect order books.
This gives the strategy the opportunity to halt trading and wait until a new snapshot arrives.
- Add a custom DYDXOraclePrice data type for dYdX. The oracle price is used to determine funding rates.
Live example
=> Add data types for dYdX

nautilus_trader/adapters/binance/config.py, nautilus_trader/adapters/binance/futures/execution.py, nautilus_trader/adapters/binance/futures/schemas/user.py
1. Add `use_trade_lite` option to `BinanceExecClientConfig`
2. Add convert from `BinanceFuturesTradeLiteMsg` to `BinanceFuturesOrderData`
3. Add calc of commissions based on event info and cached instrument
=> Implement Binance TradeLite message support

nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/config.py, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, tests/test_data/large/checksums.json, tests/unit_tests/backtest/test_config.py, tests/unit_tests/data/test_aggregation.py
Add time_bars_skip_first_non_full_bar to DataEngineConfig config
Added test
=> Add time_bars_skip_first_non_full_bar to DataEngineConfig

nautilus_core/Cargo.lock, nautilus_core/persistence/Cargo.toml, nautilus_core/persistence/src/backend/catalog.rs, nautilus_core/persistence/src/python/catalog.rs, nautilus_core/persistence/tests/test_catalog.rs, nautilus_core/serialization/src/parquet.rs
Add catalog option to write to custom path
Tested
=> Add catalog helper functions to export data

nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/http/account.py, nautilus_trader/adapters/bybit/schemas/ws.py, nautilus_trader/adapters/bybit/websocket/client.py
Add `execution.fast` support for Bybit.
There are fewer order fill events, so there isn’t enough data for a highly accurate comparison. 
However, based on the limited sample size available, `execution.fast` is approximately `6%` faster than `execution`.
=> Add `execution.fast` support for Bybit

nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/schemas/account/address.py, nautilus_trader/adapters/dydx/schemas/ws.py, tests/integration_tests/adapters/dydx/test_http_endpoints.py
Fix account balance for dYdX
Unit tests and live example
=> Fix account balance for dYdX

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/performance.yml, .github/workflows/release.yml, build.py
Refine sccache for CI.
This update replaces the `GHA mode` in sccache with `local mode`, storing the entire cache generated by sccache in the GHA cache. This approach prevents frequent writes to the GHA cache, which could otherwise lead to 429 errors. However, it does come at the cost of using more GitHub Actions storage space.
If use `GHA mode` and the GHA cache doesn’t trigger 429 errors or if an S3-like service is used, the cache can be utilized to its full potential, resulting in a higher cache hit rate. However, the network I/O involved might increase the total execution time and incur higher monetary costs.
Given these trade-offs, storing the entire sccache cache in the GHA cache currently seems to be the most optimal solution.
`4h 46m 35s` -> `3h 40m 49s` …
=> Refine sccache for CI

nautilus_trader/trading/config.py, nautilus_trader/trading/strategy.pxd, nautilus_trader/trading/strategy.pyx, tests/unit_tests/trading/test_strategy.py
Add `enable_event_logging` for `StrategyConfig`.
In high-frequency trading strategies, `<--[EVT]` type events can be particularly noisy. To address this, a toggle switch has been added for better control.
=> Add `enable_event_logging` for `StrategyConfig`

nautilus_trader/backtest/matching_engine.pyx
- fixes small typo in docs of function `fill_order` parameter in Cythons OrderMatchingEngine
=> Fix docstring typo for fill_order function in OrderMatchingEngine

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs, nautilus_core/backtest/src/models/fee.rs
- `FeeModel` was missing in the order matching engine, so adding it to the struct with the default variant of `MakerTakerFeeModel` in tests
=> Add fee model to OrderMatchingEngine in Rust

examples/backtest/databento_test_request_bars.py, nautilus_trader/backtest/config.py, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/exchange.pxd, nautilus_trader/backtest/exchange.pyx, nautilus_trader/backtest/matching_engine.pxd, nautilus_trader/backtest/matching_engine.pyx, nautilus_trader/backtest/node.py, nautilus_trader/data/aggregation.pxd, tests/unit_tests/backtest/test_config.py, tests/unit_tests/backtest/test_matching_engine.py, tests/unit_tests/trading/test_strategy.py
Add adaptive_bar_ordering to BacktestVenueConfig
Executes Low before High if Low is closer to Open, and vice versa
Attempted to add a test in test_matching_engine.py, left it as comment for further work
=> Add adaptive_bar_ordering to BacktestVenueConfig

nautilus_core/backtest/src/matching_engine/ids_generator.rs, nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- ids generation is only clearly defined and isolated functionality in `OrderMatchingEngine` that can be separated into its own struct called `IdsGenerator`. This approach is easier to maintain and tests
=> Implement ids generator for OrderMatchingEngine in Rust

docs/concepts/backtesting.md
Docs were update on both topics - as I promised.
- Docs updated: Choosing data: Cost vs. Accuracy
- Docs updated: Order of OHLC in bar processing
=> Add docs on choosing data and bars processing

nautilus_trader/adapters/dydx/config.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/http/errors.py, nautilus_trader/adapters/dydx/websocket/client.py
Use retry manager when sending websocket messages for dYdX
Live example
=> Use retry manager when sending websocket messages for dYdX

docs/concepts/backtesting.md
Docs updated:
1. Docs: Added **research** behind OHLC ordering in simulation
2. Docs: New info about **volume** in processing bar's OHLC prices
=> Update docs for bar OHLC ordering in backtests

nautilus_trader/backtest/engine.pyx
Fix backtest start and end time validation assertion
When running a backtest with a streaming catalog, it can happen that the last batch of data contains just 2 ticks. If these 2 ticks have the same ts_init, then the validation fails.
Running a backtest
=> Fix backtest start and end time validation assertion

docs/getting_started/data-migration-guide.md, nautilus_core/persistence/src/bin/to_json.rs, nautilus_core/persistence/src/bin/to_parquet.rs
Add data migration script and guide
Tested a round trip
=> Data migration script and guide

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- porting limit order flow in `OrderMatchingEngine`
=> Port limit order filling for OrderMatchingEngine in Rust

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- implement function `process_stop_market_order` in `OrderMatchingEngine`
- added `orderbook_delta_sell` fixture value which is heavily used in order matching engine tests for simplicity and smaller tests
- refactor how `price` is calculated in `determine_market_price_and_volume`, immediately setting the price as aggressively as possible.
=> Port stop market order filling for OrderMatchingEngine in Rust

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs, nautilus_core/model/src/orders/any.rs
- implement `process_stop_limit_order` function in `OrderMatchingEngine` in Rust with tests
=> Port stop limit order processing for OrderMatchingEngine in Rust

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs, nautilus_core/execution/src/matching_core.rs, nautilus_core/model/src/orders/any.rs
- added `process_trading_command` in `SimulatedExchange` and scaffold command function in `OrderMatchingEngine` with todos
- implemented and tested from in `process_cancel` function in `OrderMatchingEngine`
- added `get_order` in `OrderMatchingCore`
- added `is_inflight` and `is_open` for `LimitOrderAny` and `PassiveOrderAny`
=> Port process cancel for OrderMatchingEngine in Rust 

nautilus_core/backtest/src/matching_engine/tests.rs, nautilus_core/model/src/data/stubs.rs
- created `OrderBookDeltaTestBuilder` to help with test data building
- refactored tests in `OrderMatchingEngine` with this tests builder(instead of static fixture) for better visibility of test related values
=> Improve OrderMatchingEngine tests with delta builder

nautilus_core/portfolio/src/portfolio.rs, nautilus_trader/portfolio/portfolio.pyx, tests/unit_tests/portfolio/test_portfolio.py
Fix realized pnl bug in Portfolio.
Fixing: https://github.com/nautechsystems/nautilus_trader/issues/2236
Modified some tests about realized pnls
=> Fix realized pnl bug in Portfolio

nautilus_core/common/src/cache/mod.rs, nautilus_core/common/src/cache/tests.rs
- cache contains owned values which should be updated after every `update_order` call
- added a few status checks in cache tests to validate that the order was correctly updated inside cache order hashmap
=> Fix update order in Rust cache

docs/tutorials/databento_overview.ipynb
Convert Raw cells to Markdown cells in Jupyter notebook after discovering `Raw` cells were not correctly rendering in final documentation output (they are treated as classic `Markdown` cells). This ensures proper display of all content.
Just documentation formatting update.
✅ pre-commit passed
✅ checked output visually in JupyterLab
=> Improve Databento tutorial formatting

examples/backtest/synthetic_data_pnl_test.py, nautilus_core/portfolio/src/portfolio.rs, nautilus_core/risk/src/engine/mod.rs, nautilus_trader/execution/config.py, nautilus_trader/portfolio/portfolio.pxd, nautilus_trader/portfolio/portfolio.pyx, nautilus_trader/system/kernel.py, tests/unit_tests/backtest/test_config.py, tests/unit_tests/common/test_actor.py, tests/unit_tests/portfolio/test_portfolio.py
Add support for bars in Portfolio.
Subscribing to External bars only which should be the most granular as less granular bars aggregated from bars or quote ticks would probably be internal.
Fixing: https://github.com/nautechsystems/nautilus_trader/issues/2236
Added one test for bars in Portfolio
=> Add bar support to compute Portfolio pnls

nautilus_trader/execution/messages.pxd, nautilus_trader/execution/messages.pyx, nautilus_trader/trading/strategy.pxd, nautilus_trader/trading/strategy.pyx
Add optional params to order strategy functions
Doesn't change any functionality, just adds flexbility to handle arguments specific to execution clients if needed
=> Add optional params dict to order strategy functions

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- implement ` process_batch_cancel` command in `OrderMatchingEngine` with the test scenario
=> Port batch cancel command in OrderMatchingEngine in Rust

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs, nautilus_core/model/src/orders/any.rs
- Implemented the `expire_order` function in the `OrderMatchingEngine` with a test scenario where an order is expired after a tick with a higher timestamp appears.
- Added several utility functions to the orders struct.
=> Port order expire for OrderMatchingEngine in Rust

nautilus_trader/adapters/polymarket/config.py, nautilus_trader/adapters/polymarket/data.py
Allow user to configure the delay of non-initial Polymarket WS connection per #2238
This is to avoid overwhelming polymarket by establishing many WS at once, since polymarket will throw 429 at us.
We separate out the initial delay and the non-initial delay just in case users wanting more fine-grained control about the delay.
N.B. `ws_connection_delay_secs` has a new meaning now - this is no longer the config for the initial delay but for non-intiial WS connection delay - this might need to be communicated to end users.
Built and ran locally against polymarket.
=> Group polymarket subscriptions by configurable delay

nautilus_core/backtest/src/exchange.rs, nautilus_core/execution/src/client.rs, nautilus_core/model/src/types/money.rs
- implemented account initialization and added missing starting balances for `SimulatedExchange`
- tested that proper `AccountState` event is emitted on `Portfolio.update_account` endpoint
- added constructor for `ExecutionClient`
- added `zero` constructor for `Money` type
=> Port generate account state for SimulatedExchange in Rust

nautilus_core/analysis/src/analyzer.rs, nautilus_core/backtest/src/exchange.rs, nautilus_core/model/src/accounts/any.rs, nautilus_core/model/src/accounts/base.rs, nautilus_core/model/src/accounts/cash.rs, nautilus_core/model/src/accounts/margin.rs
- added `balance` function to accounts so that it can query `AccountBalance` by the target `Currency`
- implemented `adjust_account` in `SimulatedExchange`
- refactored test `test_initialize_account` to `test_accounting` to also include testing of  account adjustment flow
=> Port adjust account for SimulatedExchange in Rust

nautilus_trader/backtest/models.pyx
Hi Chris,
I would like to enable setting zero commistion during backtest.
There are 4 reasonable use cases:
1. Testing pure strategy logic - helps verify if core idea works before adding friction
2. Comparing pure edge of various strategies without impact of various commission from different brokers
3. Parameter optimization - find optimal settings first, then add real costs to see degradation for various commision schemes
4. If user simply wishes (from any reasons) to backtest his strategy with zero commission, that should allowed as many other backtesting platforms allow to set any (even zero) commission in backtests.
Of course, everyone should use realistic commissions for final testing, but setting up zero commission if user intentionally wants that for specific use-case, that should …
=> Allow zero commission for PerContractFeeModel

docs/getting_started/index.md
I extended the primary **Getting started** section and added overview of **example locations** in repository,
so we do not have to answear the same questions: "Where to look for examples" again and again on the Discord.
Extending documentation.
✅ pre-commit checks passed
✅ markdown rendering checked locally
=> Add docs overview of example locations in repository

Makefile, README.md
Use make target `distclean` instead of clean to run git clean. Make target `clean` now only removes intermediate build files.
The `clean` target previously deleted non-committed files, which might not be expected of this make target from the description on https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html
Tried it locally.
=> Use make target distclean instead of clean to run git clean

nautilus_core/network/src/ratelimiter/mod.rs
Fix hang in rate limiter. 
Break when the condition is met to prevent an infinite loop.
Add test for await_keys_ready function
=> Fix hang in rate limiter

nautilus_trader/adapters/betfair/data.py, nautilus_trader/adapters/betfair/providers.py, tests/integration_tests/adapters/betfair/conftest.py
Remove market_id subscriptions via instrument_ids (use only instrument provider) 
Removing code only.
=> Betfair cleanup market id orderbook subscribe

nautilus_trader/adapters/bybit/config.py
Removed unused `max_ws_reconnection_tries` for Bybit configs.
=> Remove unused `max_ws_reconnection_tries` for Bybit configs

nautilus_trader/backtest/engine.pyx
Based on [Discord discussion](https://discord.com/channels/924497682343550976/924506736927334400/1337380339194265612) with @faysou,
I have updated documentation to be more specific about what really happens under the hood
regarding the `streaming` parameter in `BacktestEngine.run(..., streaming=True)`.
🥇  Credit for this goes to: @faysou
@cjdsellers, feel free to modify the wording if there are any inconsistencies / inaccuracies, please 🙏 
Code documentation refined.
✅ pre-commit passed
=> Refine streaming parameter description

nautilus_trader/adapters/_template/data.py, nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/okx/data.py, nautilus_trader/adapters/polymarket/data.py, nautilus_trader/adapters/tardis/data.py, nautilus_trader/backtest/data_client.pyx, nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/data/client.pxd, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/data/messages.pxd, nautilus_trader/data/messages.pyx, nautilus_trader/live/data_client.py, nautilus_trader/live/data_engine.py, nautilus_trader/test_kit/mocks/data.py, tests/unit_tests/data/test_client.py, tests/unit_tests/data/test_engine.py, tests/unit_tests/data/test_messages.py, tests/unit_tests/live/test_data_engine.py
Refactor data interfaces into messages
Updated existing tests
=> Refactor data request interfaces into messages

crates/execution/src/matching_core/handlers.rs, crates/execution/src/matching_core/mod.rs, crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs, crates/model/src/orders/base.rs
- implemented `update_limit_order` in `OrderMatchingEngine`
- changed the interface for `is_limit_matched` function in `OrderMatchingCore` to also accept optional `Price` parameter which will be used in updating commands where price is not read from
- added manual order applying in `generate_order_updated` so that new updated prices is reflected in the order object( with TODO so remove when updating is done inside execution engine msgbus handlers)
- added order transition case when order status is `Accepted` and it receives `OrderUpdated` event, which is not currently a match and we receive an invalid transition error. Order status should remain `Accepted` in that case
- added `test_update_limit_order_post_only_matched` which checks target `OrderModifyRejected` event was emitted if …
=> Implement update_limit_order in OrderMatchingEngine

crates/execution/src/matching_core/mod.rs, crates/execution/src/matching_engine/engine.rs
- change the function signature of `is_limit_matched` and `is_stop_matched` to only accept order side and price
- this change removes unnecessary cloning from `OrderAny` to `LimitOrderAny` and `StopOrderAny` when calling this functions
- we immediately panic if price is not supplied in limit or stop limit orders
=> Refactor matching functions for OrderMatchingCore

crates/common/src/clock.rs, crates/core/src/datetime.rs, crates/data/src/aggregation.rs, crates/data/src/engine/mod.rs, crates/model/src/data/bar.rs, nautilus_trader/data/aggregation.pyx
Refine rust bar aggregators
I've also done some changes to TestClock and LiveClock in order to be able to update a time alert without having to pass again a callback, which would be tricky if an object needs to pass a callback to itself.
Existing tests pass
=> Refine bar aggregators in Rust

nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/model/greeks.pyx, nautilus_trader/model/greeks_data.py
Refine greeks computation
+ Allow other asset classes than futures, by just using a multiplier of 1 for non futures
+ Also we make the assumption american options are european for ease of computation, this is still a good approximation in most cases.
+ Added support for a flat dividend rate or a dividend curve stored in the cache with a name equal to the instrument id as string of the underlying of the option. If dividend curve is present or divident rate is not None, then the cost of carry  used to computed the implied volatility and the greeks is interest_rate - dividend_yield, else it's 0 for options on futures.
Tested databento_option_greeks.py notebook is still working
=> Refine greeks computation

docs/concepts/advanced/emulated_orders.md
Docs extended - added many user-friendly explanations.
Just docs updated.
✅  Read
✅  pre-commmit passed
🎯  @cjdsellers will quickly read and double check - TODO
=> Improve docs for emulated orders

crates/execution/src/matching_core/mod.rs, crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs
- added `is_touch_triggered` function in `OrderMatchingCore`
- added full implementation for processing and updating of the market if touched orders in `OrderMatchingEngine` with two test cases
=> Port handling of market-if-touched order for matching engine in Rust

crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs
- implemented `process_limit_if_touched_order` and `update_limit_if_touched_order` functions in `OrderMatchingEngine` in Rust
- wrote test cases `test_process_limit_if_touched_order_immediate_trigger_and_fill` and `test_update_limit_if_touched_order_valid`
=> Port limit-if-touched order handling for matching engine

examples/backtest/databento_test_request_bars.py, nautilus_trader/data/engine.pyx
Fix composite bars subscription
Thanks @stefansimik for finding something wasn't working while testing an example he is writing.
Using databento_test_request_bars.py
=> Fix composite bars subscription

nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/okx/data.py, nautilus_trader/data/engine.pyx
Fixed command bugs in adapters
Some subscribe calls were using the old signatures without commands.
Also checked all subscribes, unsusubcribes and requests in all adapters are fine now.
Only checked that commands have correct syntax
=> Fix command bugs in adapters

nautilus_trader/adapters/databento/data.py
Add possibility to choose which instrument ids to request in request_instrument_ids for example [""ES.OPT", "ES.FUT""] as instrument_ids
Uses the params feature that makes it very easy to customize adapters
Not tested, uses the fact that get_range_instruments can take a list as argument
=> Refine databento request_instruments granularity

crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs, crates/infrastructure/src/sql/queries.rs, crates/model/src/events/order/any.rs, crates/model/src/orders/any.rs, crates/model/src/orders/base.rs, crates/model/src/python/events/order/mod.rs, nautilus_trader/backtest/matching_engine.pyx
- implemented function `process_market_to_limit_order` in `OrderMatchingEngine` and tested
- removed `PartiallyFilled` variant in `OrderEventAny`
- To account for valid scenario when processing market to limit orders, and correct sequence of emmited events:
1. `OrderUpdated` - order was updated to new limit price where market order stopped filling
2. `OrderFilled` - market order which was filled emits filled event
3. `OrderAccepted` - remaining quantity of market order is accepted as limit order in the book
To account for this scenarios, two new order state transitions were aded:
-  `(Self::Submitted, OrderEventAny::Updated(_)) => Self::Submitted` order is submitted and we are first updating new limit price, order state after this event stays `Submitted` (we didnt fill it or accept it in …
=> Implement processing of market-to-limit orders in matching engine

examples/backtest/databento_option_greeks.py, nautilus_trader/adapters/databento/data_utils.py, nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/persistence/catalog/types.py, nautilus_trader/persistence/loaders.py, tests/unit_tests/data/test_engine.py, tests/unit_tests/persistence/test_catalog.py
Add "new_file" catalog write mode
- Allows to append data to a catalog by creating a new file when using write_data without the partitioning optional argument , which uses the _fast_write function
- Also modified the update_catalog argument of data requests in actors to update_catalog_mode so a catalog write mode can be passed as argument
- Can be useful if you have data of various quality types and don't want to take the risk to degrade the quality of some existing data by appending/concatenating new data
Added a test, also tested with own code
=> Add catalog write modes

nautilus_trader/adapters/binance/websocket/client.py
As explained in issue #2367, the adapter creates a new connection for each subscription. I changed this so that the adapter will reuse the same connection until there are 200 connections. Once the limit is reached, a new connection will be made.
- [O] New feature (non-breaking change which adds functionality)
- [O] This change requires a documentation update
I have many pairs to trade in Binance, just like #2367. I test approximately 250 instruments. Before the change, it was heavily rate limited and had connection problems. After the change, I confirmed that it was not rate-limited and works with over 250 instruments.
=> Improve Binance websocket connections management

nautilus_trader/adapters/binance/config.py, nautilus_trader/adapters/binance/futures/execution.py, nautilus_trader/adapters/binance/futures/http/account.py, nautilus_trader/adapters/binance/futures/schemas/account.py
Binance Futures [initial leverage](https://developers.binance.com/docs/derivatives/usds-margined-futures/trade/rest-api/Change-Initial-Leverage). 
Tested manually on Binance Testnet.
=> Add initial leverage config for Binance Futures

examples/backtest/example_06_using_cache/README.md, examples/backtest/example_06_using_cache/run_example.py, examples/backtest/example_06_using_cache/strategy.py
New beginner's friendly example about how to use `Cache`.
✅  pre-commit passed (I had to use `# noqa: S301 (safe pickle usage)` to make ruff happy here `strategy.py: 94+99`
✅ strategy was ran and terminal output is as expected
=> Add backtest cache example

nautilus_trader/adapters/_template/execution.py, nautilus_trader/adapters/betfair/execution.py, nautilus_trader/adapters/binance/execution.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/okx/execution.py, nautilus_trader/adapters/polymarket/execution.py, nautilus_trader/adapters/sandbox/execution.py, nautilus_trader/execution/messages.pxd, nautilus_trader/execution/messages.pyx, nautilus_trader/live/execution_client.py, nautilus_trader/live/execution_engine.py, nautilus_trader/test_kit/mocks/exec_clients.py, tests/integration_tests/adapters/betfair/test_betfair_execution.py
Refactor order report interfaces into messages
Similar refactor as for data messages.
Using messages makes it clearer to understand where interfaces between component are located.
This also opens up the way to call execution client's order report functionalities from other components through messages if necessary in the future.
- Refactor
Adapted existing tests
=> Refactor reconciliation interfaces into messages

examples/backtest/databento_option_greeks.py, nautilus_trader/model/greeks.pyx, nautilus_trader/model/greeks_data.py
Add pnl information to greeks data
This way GreeksData contains a unified view of an instrument or portfolio greeks and prices
Tested on databento_option_greeks.py using logs of each instrument greeks
=> Add pnl information to greeks data

examples/backtest/databento_option_greeks.py, nautilus_trader/model/greeks.pyx
Refine underlying filtering in portfolio_greeks
Allows to filter several underlyings for portfolio_greeks which is useful for beta-weighted portfolio greeks.
test on databento_option_greeks.py example
=> Refine underlying filtering in portfolio_greeks

examples/backtest/example_01_load_bars_from_custom_csv/run_example.py
fix example_01_load_bars_from_custom_csv\run_example.py runtime errors when run this file.
nautilus_trader\examples\backtest\example_01_load_bars_from_custom_csv> python .\run_example.py
get errors like below：
2025-02-28T17:27:32.197954500Z [INFO] BACKTEST_TRADER-001.BacktestEngine: Added SimulatedExchange(id=XCME, oms_type=NETTING, account_type=MARGIN)
Traceback (most recent call last):
File "U:\xxx\nautilus_trader\examples\backtest\example_01_load_bars_from_custom_csv\run_example.py", line 60, in <module>
engine.add_instrument(EURUSD_FUTURES_INSTRUMENT)
File "nautilus_trader/backtest/engine.pyx", line 587, in nautilus_trader.backtest.engine.BacktestEngine.add_instrument
raise InvalidConfiguration( …
=> Fix example load bars from custom CSV

nautilus_trader/adapters/interactive_brokers/client/market_data.py
Fix wrong ts_init and ts_event value for  Day/week/month historical bar data from IBKR #2379
IB only return date for Day/week/month historical bar. For week and month bar, the date represents the end period, not start of period, which is different from other type of bar
wrote a script similar to https://github.com/nautechsystems/nautilus_trader/blob/master/examples/live/interactive_brokers/historical_download.py to inspect output for weekly and day bar:
Before code change:
Nautilus Return:
open    high     low   close     volume             ts_event  \
2  476.25  476.36  464.61  468.45  274518743  1704412800000000000   
3  467.70  478.60  466.13  475.65  268167290  1705017600000000000   
4  474.25  482.75  469.87  482.64  253556992  1705622400000000000   
5  483.67  485.99  482.78  485.97 …
=> Fix bar timestamps for IB

nautilus_trader/test_kit/providers.py, tests/unit_tests/model/test_time_bar_aggregation.py
With @faysou , we made an excellent team today and divided the tasks between us.
* while @faysou was focusing on the fix [PR#2930](https://github.com/nautechsystems/nautilus_trader/pull/2390)
* I prepared the test in the meantime, that should ensure any similar problem will detected easily in the future
This test fails and indicates problem when composite bars aggregation stops working.
Just new test
* **before** @faysou's fix - the test "successfully" fails and indicates that there's any problem with bar aggregation that stopped working
* **after** @faysou's fix - the test runs smoothly
=> Add test for time-bar aggregation

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/endpoints/endpoint.py, nautilus_trader/adapters/dydx/endpoints/market/orderbook.py, nautilus_trader/adapters/dydx/http/market.py, nautilus_trader/adapters/dydx/schemas/ws.py, nautilus_trader/adapters/dydx/websocket/client.py
Request order books snapshots with HTTP for dYdX to improve robustness when subscribing to order books or quotes.
Internally, the venue uses an HTTP request as well when requesting a snapshot via the websocket. However, that request often fails resulting in "internal errors". Now we can use retries in case of failed requests.
Live example
=> Request order books snapshots with HTTP for dYdX

examples/backtest/databento_option_greeks.py, nautilus_trader/persistence/catalog/parquet.py
Refine base_template behaviour in parquet write_data
So the same base_template name can be used when using partitioning or not when using catalog write_data.
Previously ".parquet" wasn't appended to the base_template when using partitioning so it had to be used inside the base template provided by the user which is a different behaviour from the default behaviour used most of the time.
tested with databento_option_greeks.py
=> Refine base_template behaviour in parquet write_data

examples/backtest/example_08_cascaded_indicator/README.md, examples/backtest/example_08_cascaded_indicator/run_example.py, examples/backtest/example_08_cascaded_indicator/strategy.py
New tutorial style example for beginners - how to use cascaded indicators
New example added.
✅  Strategy generates expected output in Terminal
✅  pre-commit passed
=> Add cascaded indicators example

examples/backtest/example_09_custom_event_with_msgbus/README.md, examples/backtest/example_09_custom_event_with_msgbus/run_example.py, examples/backtest/example_09_custom_event_with_msgbus/strategy.py
New tutorial style example for beginners -Hhow to use: Custom event with msgbus.
I have used standard `@dataclass` and it works without visible problems.
Is that OK, or is there any motivation and benefits using `@customdataclass` instead.
As it is now in the example, probably no data are serialized (they live just in memory),
so this implementation looks like a quick & easy way how to publish/subscribe data/events,
when there is no need for serialization... (or is it always required to handle serialization in all cases?)
I got some hints from @faysou , that `@customdataclass` should be used to allow serialization
like here: https://nautilustrader.io/docs/nightly/concepts/data/#option-greeks-example,
but is this increased complexity always required, or is it completely OK use this …
=> Add custom event with msgbus example

docs/integrations/ib.md
Fixed invalid link in IB docs - solves [issue 2399](https://github.com/nautechsystems/nautilus_trader/issues/2399)
Just changed the link to real existing examples - as old link was obsolete.
✅  New links refers to the real examples
✅  precommit - passed
=> Fix invalid link in IB docs

crates/backtest/src/exchange.rs, crates/common/src/cache/mod.rs, crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs, crates/model/src/orders/any.rs
- removed obsolete processing of `QueryOrder` command from matching engine (it's not present in Cython implementation and doesn't need to be here as its used mainly for inflight live orders)
- add missing indexing of `Venue` and `PositionId`  indexing in cache function `add_position_id`
- full contingent order handling, in both updating and processing orders functions
- tested in `test_updating_of_contingent_orders`
=> Contingent orders handling for order matching engine

nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/common/enums.py, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/data/messages.pyx, nautilus_trader/persistence/catalog/base.py, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/data/test_engine.py
Refine mixed catalog client requests
- Allow to extend a catalog after its last datetime or before its first date time
- Automatic determination of append and prepend catalog write mode
- Note: to avoid creating holes in the data, priviledge only using start date and not end date in data requests when updating the catalog as well. Update: I've added a condition enforcing not using both end and update_catalog_mode at the same time.
Existing tests passing, more tests needed, possibly after a merge. Found and fixed bugs to make existing tests work. Also the key logic is concentrated in _handle_date_range_request and is easy to understand.
=> Refactor mixed catalog client requests

examples/backtest/example_10_messaging_with_actor_data/README.md, examples/backtest/example_10_messaging_with_actor_data/run_example.py, examples/backtest/example_10_messaging_with_actor_data/strategy.py
New example: Messaging with Actor & Data
New example added
✅  Strategy works - there is expected output in Terminal
✅  precommit issues fixed
=> Add example messaging with actor & data

docs/concepts/messaging_styles.md
New documentation: Messaging styles
Created based on hints from @faysou , @cjdsellers , @demonkoryu  🙏 
Thank you all guys.
New documentation
New documentation added
✅  precommit passed
( @cjdsellers  )
1. New link should be placed **after the existing** "message_bus.md" file since it builds upon those concepts while introducing additional messaging patterns.
2. Double check please and make proper corrections, where needed 🙏 
The navigation structure would look like:
```
- Architecture
- Actors
- Backtesting
- Data
- Message Bus
- **Messaging Styles** (new content)
- Strategies
- ...
```
**Why this placement?**
1. The content directly relates to both the message bus and actor concepts - serving as a bridge between these topics.
2. The existing "Message Bus" documentation focuses primarily …
=> Add docs for messaging styles

crates/backtest/src/exchange.rs, crates/backtest/src/execution_client.rs, crates/backtest/src/lib.rs, crates/execution/src/client/base.rs, crates/execution/src/client/mod.rs, crates/execution/src/engine/mod.rs, crates/execution/src/messages/mod.rs, crates/execution/src/messages/reports.rs
- created various reports structs in execution crate: `GenerateOrderStatusReport`, `GenerateOrderStatusReports` ,  `GenerateFillReports ` and `GeneratePositionReports `
- refactored current `ExecutionClient` struct to be a trait and rename it to `BaseExecutionClient`, which will be used by both backtesting and live execution clients
-  `ExecutionClient` trait specifies trading commands and its supertype `LiveExecutionClient` adds additional generating reports functions for reconciliation
- created `BacktestExecutionClient` which contains base exec client and implements `ExecutionClient` trait in `backtest` crate
-  adapted execution engine to work with new `ExecutionClient` trait
=> Execution client design in Rust

crates/backtest/src/exchange.rs, crates/backtest/src/execution_client.rs, crates/execution/src/messages/mod.rs, crates/execution/src/messages/submit_list.rs, crates/execution/src/models/latency.rs, crates/model/src/orders/list.rs
- added latency simulation to backtest exchange for more realistic order processing with supplied latency model with proper testing
Introduced `InflightCommand` structure to represent delayed commands with: 
1. Timestamp for execution
2. Counter for ordering same-timestamp commands
3. Target trading command
4. Custom ordering implementation for BinaryHeap (earliest timestamp first)
Added two command queues to SimulatedExchange:
- `message_queue`: Standard FIFO queue for immediate processing
- `inflight_queue`: Priority queue (BinaryHeap) for latency-delayed commands
Implemented `send` method with three modes:  
1. Immediate processing (`use_message_queue` = false)
2. Queue-based processing (standard `message_queue`)
3. Latency-based processing (using `inflight_queue` with `LatencyModel`) …
=> Implement latency modeling for SimulatedExchange in Rust

crates/data/src/aggregation.rs, nautilus_trader/data/aggregation.pyx
Solves issues encountered in Bar constructor for example `Condition.is_true(high._mem.raw >= close._mem.raw, "high was < close")`
Thank you to @hjander for helping on debugging this.
Existing tests should still pass, the code change makes it like the update function used for quotes and trades.
=> Fix update_bar aggregation function

nautilus_trader/adapters/bybit/execution.py
Fix unbound variable issue for Bybit and optimize with local variable for better performance.
=> Fix unbound variable for Bybit

examples/backtest/databento_option_greeks.py, nautilus_trader/data/engine.pyx, nautilus_trader/persistence/catalog/parquet.py
- Added consolidation functions for market data directories containing several parquet files added with the NEWFILE option. The consolidation ensures that merged data is ordered chronologically.
- Also added min_max_from_parquet_metadata function that returns the min and max of a parquet column efficiently by reading the metadata information explicitly.
Tested in databento_option_greeks.py
=> Add catalog consolidation functions of several parquet files into one

nautilus_trader/adapters/bybit/data.py
Catch BybitErrors when updating instruments for ByBit. When a BybitError `invalid request, please check your server timestamp or recv_window param.` occurs, the task tries again in 1 hour instead of canceling completely.
Live example
=> Catch BybitErrors when updating instruments for ByBit

docs/concepts/message_bus.md
Minor change that fixes a link in markdown to example code for messaging.
I checked the folder names to ensure correctness.
=> Fix link to messaging example in docs

nautilus_trader/adapters/bybit/common/enums.py, nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/endpoints/account/switch_mode.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/http/account.py
Add initial leverage & margin_mode & position_mode config for Bybit.
=> Add initial leverage & margin_mode & position_mode config for Bybit

Cargo.lock, crates/adapters/tardis/src/replay.rs, crates/persistence/Cargo.toml, crates/persistence/src/backend/catalog.rs, crates/persistence/src/python/catalog.rs, crates/persistence/tests/test_catalog.rs, crates/serialization/Cargo.toml, crates/serialization/src/parquet.rs, tests/test_data/large/checksums.json
Update rust parquet catalog with recent features
Added different kinds of adding data to an existing parquet file as well as the ability to consolidate several parquet files into one to match what is already done in python, and timestamp_bound
Not tested yet
=> Update Rust parquet catalog with recent features

nautilus_trader/adapters/bybit/data.py, nautilus_trader/common/providers.py
Catch Exceptions when loading the instruments.
This is a follow up from https://github.com/nautechsystems/nautilus_trader/pull/2437. The state variable `self._loading` needs to be reset to `False`. Hence, the previous fix still resulted in the fact that the instruments were not being reloaded when a Bybit error occured.
Live example
=> Improve InstrumentProvider error handling when loading

nautilus_trader/adapters/dydx/data.py
Catch unexpected errors when fetching the orderbooks for dYdX
Yesterday the indexer of dYdX was down resulting in errors such as `DecodeError('JSON is malformed: invalid character (byte 0)')`. This change ensures that the orderbook fetching task keeps running when unexpected errors occur.
Live example
=> Catch unexpected errors when fetching the orderbooks for dYdX

crates/backtest/src/engine.rs, crates/backtest/src/exchange.rs, crates/backtest/src/execution_client.rs, crates/execution/src/client/base.rs, crates/execution/src/matching_engine/adapter.rs, crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs, crates/system/src/kernel.rs
- removed the local msgbus dependency and used a global approach for order matching engine and simulated exchange, and fixed tests where each test needed to call `register_message_bus` function
- initialized cace, clock and exec engine in `NautilusKernel`
- changed clock type for order matching engine and fix tests where ES instrument is used (setting the test clock current time to be higher than ES activation ns)
- implemented `add_venue` for `BacktestEngine`
- added TODO comment in `iterate` function of `OrderMatchingEngine` were generic clock were introduced and we lost `set_time` function which needs to be added later
=> Implement add venue for BacktestEngine

Cargo.lock, crates/adapters/tardis/src/replay.rs, crates/persistence/Cargo.toml, crates/persistence/src/backend/catalog.rs, crates/persistence/src/python/catalog.rs, crates/persistence/tests/test_catalog.rs, crates/serialization/Cargo.toml, crates/serialization/src/enums.rs, crates/serialization/src/lib.rs, crates/serialization/src/parquet.rs, crates/serialization/src/python/enums.rs, crates/serialization/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/test_kit/mocks/data.py, tests/unit_tests/persistence/test_catalog_pyo3.py
Refine rust catalog file operations
Made it work in python
Added python tests
=> Refine Rust catalog file operations

crates/model/src/accounts/any.rs, crates/model/src/accounts/mod.rs, crates/model/src/instruments/any.rs, crates/model/src/instruments/mod.rs, crates/model/src/orders/any.rs, crates/model/src/orders/mod.rs
- change the trait specification of `enum_dispatch` macro attribute to be applied on the target enum
- this is advised per [enum_dispatch docs](https://docs.rs/enum_dispatch/latest/enum_dispatch)
```
#[enum_dispatch]
trait KnobControl {
//...
}
#[enum_dispatch(KnobControl)]
enum Knob {
LinearKnob,
LogarithmicKnob,
}
```
This change also help IDE better index these properties and can us it for better autocomplete
**Before**
**After**
=> Refactor enum dispatch

crates/backtest/src/config.rs, crates/backtest/src/data_client.rs, crates/backtest/src/engine.rs, crates/backtest/src/exchange.rs, crates/data/src/client.rs, crates/data/src/engine/mod.rs, crates/execution/src/engine/mod.rs, crates/persistence/Cargo.toml, crates/system/src/config.rs, crates/system/src/kernel.rs
- added `Default` trait for `BacktestEngineConfig` and `NautilusKernelConfig`
- implemented `new` constructor for `BacktestDataClient`
- implemented `add_instrument` in `BacktestEngine` with proper testing 
- changed clock type for `DataClientAdapter`
- continue `NautilusKernel` initialization 
- fixed correct features in `nautilus-persistence` crate dependencies
=> Implement add instrument for BacktestEngine

nautilus_trader/adapters/dydx/endpoints/endpoint.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/http/errors.py
- Refine conditional orders for dYdX: submit stop limit or stop market orders without setting dYdX specific order tags
- Retry HTTP requests when JSONDecodeError occurs to malformed JSON messages
- Fix unbound venue_order_id and client_order_id when creating an OrderStatusReport
- Fix submitting stop_market orders
Live example
=> Fix submitting stop market orders and OrderStatusReport for dYdX

nautilus_trader/adapters/dydx/endpoints/endpoint.py, nautilus_trader/adapters/dydx/http/errors.py
Fix retrying HTTP calls when a DecodeError occurs for dYdX
Live example
=> Fix retrying HTTP calls when a DecodeError occurs for dYdX

nautilus_trader/adapters/interactive_brokers/client/order.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_order.py
Interactive Brokers adapter : 
Changing one parameter of cancel_order method 
manual_cancel_order_time is replaced with IB API's OrderCancel object
fix bug #2474
Tested in paper mode on develop branch
=> Fix error on cancel order for IB

docs/concepts/backtesting.md
Docs updated / fixed on topic of partial fills.
@cjdsellers 
Chris feel free to modify the wording or make it more precise, if not fully correct.
Primarily this part is of interest: `Partial fills are supported with **L2/L3 order book** data`.
Just docs update
✅  pre-commit formatting OK
✅ @cjdsellers (Chris will do quick 1 sec double check of the information 🙏 )
=> Clarify partial fills in backtesting docs

crates/adapters/databento/src/loader.rs, nautilus_trader/adapters/databento/config.py, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/databento/loaders.py, nautilus_trader/adapters/databento/providers.py
Refine databento venue dataset mapping
+ Add DatabentoDataClientConfig.venue_dataset_map which allows to use another dataset than the default for a venue
+ Retain first dataset in the databento publishers.json file as default dataset for a venue
Not tested, but will likely work, someone with a databento live access should test it
=> Refine databento venue dataset mapping

examples/backtest/databento_option_greeks.py, nautilus_trader/backtest/config.py, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/node.py, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/persistence/catalog/types.py, nautilus_trader/persistence/funcs.py, tests/unit_tests/backtest/test_config.py
Refine BacktestDataConfig with instrument_ids and bar_types
+ Allow to reduce the number of required queries to backtest catalog data and sorting data several times in the backtest engine.
+ Added instrument_ids and bar_types to BacktestDataConfig
+ Made the feature work with rust sessions and pyarrow queries
Tested manually in databento_option_greeks.py for chunk_size = None and not None (I think chunk_size should be renamed to something better like batch_data_size else it's hard to know what it's doing except by looking at the code)
=> Add instrument_ids and bar_types for BacktestDataConfig

crates/adapters/coinbase_intx/src/websocket/client.rs, crates/network/src/python/websocket.rs, crates/network/src/websocket.rs
Allow websockets to have Python callback style consumer or Rust stream style consumers
Tests passing
=> Add consumer for WebSocketClient

crates/common/src/enums.rs, crates/common/src/logging/logger.rs
- color was not showing because key value store was empty for default logging, so we should get the color from log level instead (it was defaulting to `Normal`, which is without color or grey)
=> Fix colored logging 

nautilus_trader/adapters/binance/common/enums.py
Add new SymbolFilterType for Binance.
Fix:
```
BinanceFuturesInstrumentProvider: Failed to load instruments
ValidationError(Invalid enum value 'POSITION_RISK_CONTROL' - at `$.symbols[0].filters[7].filterType`)
```
=> Add new SymbolFilterType for Binance

crates/common/src/greeks.rs, crates/model/src/data/greeks.rs
Refine greeks functions in rust
+ Added PortfolioGreeks::from<GreeksData>
=> Refine greeks functions in Rust

nautilus_trader/adapters/dydx/common/enums.py, nautilus_trader/adapters/dydx/common/types.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/websocket/client.py, tests/integration_tests/adapters/dydx/test_types.py
Handle websocket errors for dYdX. When an internal error occurs, the websocket is not subscribed to the channel. Hence, the client tries to subscribe again after a delay.
Live example
=> Handle websocket errors for dYdX

docs/concepts/backtesting.md
The issue was fixed by @faysou a few months ago, so this limitation is not true anymore.
Simple docs update - old obsolete info removed.
✅ precommit passed
=> Remove obsolete bar limitations in portfolio docs

crates/persistence/src/backend/catalog.rs, docs/concepts/data.md, docs/tutorials/databento_data_catalog.ipynb, nautilus_trader/persistence/catalog/parquet.py
Remove catalog basename_template argument
This argument is not used in general and can cause problems if modified wih update_catalog in data requests, so better to remove it.
Existing test passing
=> Remove catalog basename_template argument

nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/websocket/client.py
Improve reconnection robustness for Bybit private/trading channels.
=> Improve reconnection robustness for Bybit private/trading channels

RELEASES.md, nautilus_trader/adapters/bybit/common/enums.py, nautilus_trader/adapters/bybit/endpoints/trade/amend_order.py, nautilus_trader/adapters/bybit/endpoints/trade/batch_amend_order.py, nautilus_trader/adapters/bybit/endpoints/trade/batch_cancel_order.py, nautilus_trader/adapters/bybit/endpoints/trade/cancel_order.py, nautilus_trader/adapters/bybit/endpoints/trade/place_order.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/http/account.py, nautilus_trader/adapters/bybit/schemas/order.py, nautilus_trader/adapters/bybit/schemas/ws.py, nautilus_trader/adapters/bybit/websocket/client.py
- Add WebSocket batch order operations for Bybit.
- Improve event generation for abnormal order states to reduce inconsistencies in cached order statuses.
=> Add WebSocket batch order operations for Bybit

Makefile, build.py
Inconsistent environment variables cause frequent re-builds between
* make build-debug
* rust analyzer cargo check
* rust analyzer cargo test
* pre-commit
* cargo in cli
```
0.359245532s  INFO prepare_target{force=false package_id=pyo3-build-config v0.24.1 target="build-script-build"}: cargo::core::compiler::fingerprint:     dirty: EnvVarChanged { name: "VIRTUAL_ENV", old_value: None, new_value: Some("/home/twitu/Code/nautilus_trader/.venv") }
Dirty pyo3-build-config v0.24.1: the env variable VIRTUAL_ENV changed
[pyo3-build-config 0.24.1] cargo:rerun-if-env-changed=VIRTUAL_ENV
```
This PR adds a dry run feature that sets the appropriate environment variables in the terminal using `make build-dry-run`. It also prints the appropriate settings for vscode rust analyzer that can be set …
=> Improve consistency of environment variables for build

Makefile, crates/model/src/defi/block.rs, crates/model/src/defi/mod.rs, crates/model/src/defi/rpc.rs
- added `defi` feature in Makefile cargo tests
- implemented `Block` struct with correct parsing of all the relevant fields (hex number, UnixNanos timestamps, etc) with helper `rpc` wrappers
- tested on data from live RPC node for blockchains Ethereum, Base, Polygon, Arbitrum
=> Implement Block primitive for blockchain domain model

nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/binance/futures/data.py
Binance futures support of `Strategy::subscribe_mark_prices` and `Strategy::on_mark_price`.
It was tested manually on Binance
=> Add mark price subscription for Binance Futures

crates/model/src/defi/block.rs, crates/model/src/defi/hex.rs, crates/model/src/defi/mod.rs, crates/model/src/defi/rpc.rs, crates/model/src/defi/transaction.rs
- moved functions `deserialize_hex_number` and `deserialize_hex_timestamp` into separate `hex` file
- implemented `RpcNodeHttpResponse` struct for HTTP raw request responses wrapping  and renamed `RpcNodeResponse` to `RpcNodeWssResponse` 
- Implemented `Transaction` blockchain primitive with parsing tests with raw data from ETH blockchain
- https://github.com/nautechsystems/nautilus_trader/issues/1335
=> Implement Transaction primitive for blockchain domain model

nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_engine.py
Fix RequestInstrument in query_catalog
Query catalog was returning a list for instrument requests instead of a single instrument as implemented by live market data clients.
Tested on prototype, updated test
=> Fix RequestInstrument in query_catalog

crates/model/src/orders/limit_if_touched.rs
Standardized validations for `LimitIfTouchedOrder` (fixes #2529)
* **Implemented `new_checked`** for `LimitIfTouchedOrder`, bringing it in line with `MarketOrder` and `LimitOrder`.
* Added complete domain‑level validations:  
* positive `quantity`, `price`, `trigger_price`  
* optional `display_qty` ≤ `quantity`  
* `TimeInForce::Gtd` → non‑zero `expire_time` required  
* side/trigger rule (`BUY ⇒ trigger ≥ limit`, `SELL ⇒ trigger ≤ limit`)
* Legacy `new` now wraps `new_checked`, preserving the old panic‑on‑error behaviour for external callers.
* Added a concise `Display` implementation.
* **Unit‑tests** (4) live in the same module and cover happy‑path plus every validation failure.
* Inline rust‑doc comments for clarity.
* `cargo test -p nautilus-model --lib limit_if_touched --features …
=> Improve validations for LimitIfTouchedOrder

crates/model/src/orders/market_if_touched.rs
This PR hardens the `MarketIfTouchedOrder` construction path and tightens several related invariants:
* **New validation layer** – extracted a `new_checked` constructor that returns `anyhow::Result<Self>` and performs all semantic checks (`check_positive_quantity`, `check_positive_price`, GTD expiry present, `display_qty ≤ quantity`, etc.).  
* The existing `new` constructor is now a thin wrapper that calls `new_checked` and panics on failure, preserving the ergonomic API for quick-and-dirty tests while providing a fall-through path for production code that wants explicit error handling.
* **Cleaner failure semantics** – Leveraged `nautilus_core::correctness::{check_predicate_false, FAILED}` so that violations propagate meaningful messages instead of opaque panics.
* **API hygiene** – …
=> Improve validations for MarketIfTouchedOrder

.github/workflows/build.yml
Adds a top-level `concurrency` block to `.github/workflows/build.yml` so that any older run on the same branch or pull-request is automatically aborted when a newer commit is pushed.
* **`concurrency.group`** → `${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}`  
* one group per workflow file × branch/PR number  
* **`cancel-in-progress: true`** → GitHub immediately stops the previous run when a new one is queued
* No other job logic or pins were modified
* Saves runner minutes and queue time
* Keeps the Checks/Actions tab clean—only the run for the latest commit remains
* Avoids publishing artefacts or notifications from obsolete builds
* 📄 **GitHub docs – Using concurrency**  
<https://docs.github.com/en/actions/using-jobs/using-concurrency>
=> Improve CI to cancel superseded workflow runs with concurrency

crates/model/src/ffi/data/mark_price.rs, crates/model/src/ffi/data/mod.rs, crates/persistence/src/python/backend/session.rs, nautilus_trader/core/includes/model.h, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/core/rust/model.pxd, nautilus_trader/model/data.pxd, nautilus_trader/model/data.pyx, nautilus_trader/persistence/catalog/parquet.py
Mark price loading from data catalog
Manually
=> Add support for MarkPriceUpdate streaming from catalog

nautilus_trader/adapters/binance/futures/data.py, nautilus_trader/adapters/binance/futures/schemas/market.py
Binance sends empty trade tick messages from time to time. This leads to error messages and noise in logs: `Error handling trade tick message b'{"stream":"xrpusdt@trade","data":{"e":"trade","E":1746194730699,"T":1746194730699,"s":"XRPUSDT","t":2332526925,"p":"0","q":"0","X":"NA","m":false}}', 'size' not a positive integer, was 0`
Such messages should have `DEBUG` level in logs.
Manually
=> Improve zero size trade logging for Binance Futures

crates/model/src/orders/market_to_limit.rs
* Adds **`new_checked`** (returns `anyhow::Result<Self>`) with full validation.
* Updates the existing `new` constructor to delegate to `new_checked`, preserving the old panic-on-failure behaviour for backwards-compatibility.
* Enforces:
* `quantity > 0`
* `display_qty > 0` **and** `display_qty ≤ quantity`
* `expire_time` is supplied when `time_in_force == GTD`
* Fills out the **`market_to_limit.rs`** doc-comment and removes outdated TODOs.
* Adds a dedicated **test-suite** (`crates/model/src/orders/market_to_limit.rs`) covering the happy path plus each new validation branch.
Issue **nautechsystems/nautilus\_trader#2529** highlighted that `MarketToLimitOrder` lacked the strict invariants now applied to all order types.
Bringing these checks in-line:
* Eliminates a class of runtime panics …
=> Improve validations for MarketToLimitOrder

crates/model/src/orders/stop_limit.rs
* **Implemented `new_checked`** for `StopLimitOrder`, bringing it in line with `MarketOrder`, `LimitOrder`, `LimitIfTouchedOrder`, and `MarketToLimitOrder`.
* **Dropped the side-specific trigger/limit inequality**
*BUY* orders may now use either `trigger ≥ limit` **or** `trigger ≤ limit`; the mirror applies to *SELL*.
This unblocks “limit-if-touched” and similar strategies that were previously rejected.
* Added complete **domain-level validations**:
* quantity > 0
* price > 0
* trigger\_price > 0
* optional `display_qty ≤ quantity`
* `TimeInForce::Gtd` ⇒ non-zero `expire_time` required
* **Legacy `new` now wraps `new_checked`**, preserving the historical *panic-on-error* behaviour for external callers.
* Extended rust-doc explaining the two legal stop-limit styles (break-out vs. …
=> Improve validations for StopLimitOrder

crates/model/src/orders/stop_limit.rs, crates/model/src/orders/stop_market.rs
This PR introduces **stronger domain-level correctness checks** for `StopMarketOrder` construction in `crates/model/src/orders/stop_market.rs`, adds comprehensive unit tests, and performs a minor cleanup in `stop_limit.rs` test code.
* **`StopMarketOrder::new_checked`** – new fallible constructor that enforces invariants *before* the order is initialised:
* `quantity` must be strictly positive (`check_positive_quantity`)
* `display_qty` (when present) cannot exceed `quantity`
* `expire_time` is mandatory and non-zero when `time_in_force` = `GTD`
* **`StopMarketOrder::new`** now delegates to `new_checked` and panics on failure (`expect(FAILED)`), preserving the original infallible API for existing callers.
* **Unit-test suite** extended with four rstest cases that assert:
* successful …
=> Improve validations for StopMarketOrder

crates/model/src/orders/trailing_stop_limit.rs
Strengthen *server-side* validation for `TrailingStopLimitOrder`.
* Introduced `new_checked`, a fallible constructor that enforces:
* **Quantity must be positive** (`check_positive_quantity`).
* **display_qty ≤ quantity**.
* **GTD orders require a non-zero `expire_time`**.
* Existing `new` now delegates to `new_checked` and panics on failure, preserving the public API while centralising validation.
* Added 4 focused unit tests in `trailing_stop_limit.rs` to cover the happy path and each new invariant.
* Updated docs/comments to reflect the new behaviour.
These checks eliminate an entire class of runtime errors where an invalid order could slip through initialisation and fail deep in the matching or execution layers.
***
Related: https://github.com/nautechsystems/nautilus_trader/issues/2529 …
=> Improve validations for TrailingStopLimitOrder

examples/backtest/model_configs_example.py, nautilus_trader/backtest/config.py, nautilus_trader/backtest/models.pyx, nautilus_trader/backtest/node.py, tests/unit_tests/backtest/test_config.py
Add support for Fill, Latency and Fee models in BacktestNode
Added example showing how to use the model configs
=> Add support for Fill, Latency and Fee models in BacktestNode

.github/actions/common-setup/action.yml, Cargo.lock, crates/adapters/blockchain/Cargo.toml, crates/adapters/blockchain/README.md, crates/adapters/blockchain/bin/watch_hypersync_live_blocks.rs, crates/adapters/blockchain/bin/watch_rpc_live_blocks.rs, crates/adapters/blockchain/src/config.rs, crates/adapters/blockchain/src/data.rs, crates/adapters/blockchain/src/hypersync/client.rs, crates/adapters/blockchain/src/hypersync/mod.rs, crates/adapters/blockchain/src/hypersync/transform.rs, crates/adapters/blockchain/src/lib.rs, crates/adapters/blockchain/src/rpc/chains/arbitrum.rs, crates/adapters/blockchain/src/rpc/chains/base.rs, crates/adapters/blockchain/src/rpc/chains/ethereum.rs, crates/adapters/blockchain/src/rpc/chains/polygon.rs, crates/adapters/blockchain/src/rpc/core.rs, crates/adapters/blockchain/src/rpc/mod.rs, crates/model/src/defi/hex.rs
- Implemented `HyperSyncClient`, which initializes the official `hypersync-client` Rust client from URL endpoint received from `Chain`.  It can subscribe to live new blocks by creating a task that monitors new blocks archived and sends new blocks to the data client through the channel
- separated the processing of RPC and HyperSync messages in the `BlockchainDataClient`
- renamed bin `live_blocks` to `live_blocks_rpc` and added new bin `live_blocks_hypersync` which initializes blockchain adapter with only HyperSync connection to watch for live data blocks updates
- created transform function `transform_hypersync_block` which converts hypersync block to Nautilus native `Block` struct
- renamed `BlockchainRpcMessage` to `BlockchainMessage`, to be independent from the  data source
- …
=> Introduce HyperSync client to blockchain adapter

crates/model/src/orders/mod.rs, crates/model/src/orders/stop_market.rs, crates/model/src/orders/trailing_stop_limit.rs, crates/model/src/orders/trailing_stop_market.rs
Strengthen server-side validation for **TrailingStopMarketOrder**.
Introduced `new_checked`, a fallible constructor that enforces:
Quantity must be positive (`check_positive_quantity`).
`display_qty ≤ quantity`.
`GTD` orders require a non-zero `expire_time`.
Existing `new` now delegates to `new_checked` and panics on failure, preserving the public API while centralising validation.
Pulled shared helpers (`check_display_qty`, `check_time_in_force`) into `orders/mod.rs` and refactored `StopMarketOrder` & `TrailingStopLimitOrder` to reuse them.
Added 4 focused unit tests in `trailing_stop_market.rs` to cover the happy path and each new invariant.
Removed redundant imports and updated docs/comments for clarity.
These checks eliminate an entire class of runtime errors where an invalid order …
=> Improve validations for TrailingStopMarketOrder

crates/model/src/orders/limit.rs, crates/model/src/orders/list.rs
Add `LimitOrder::new_checked(...)` — a fully-validated constructor that wraps the existing `new` method.
This makes the distinction between **checked** and **unchecked** order creation explicit, paving the way for stricter compile-time guarantees and safer call-sites (resolves #2529).
* **Scope**: `crates/model/src/orders/limit.rs` (+57 / −0)
* **API impact**: purely additive; no breaking changes.
* **Next steps**: migrate callers that rely on pre-validated inputs to `new_checked`; consider deprecating direct use of `new` in a follow-up.
=> Improve validations for LimitOrder

crates/model/src/orders/any.rs, crates/model/src/orders/limit_if_touched.rs, crates/model/src/orders/market_if_touched.rs, crates/model/src/orders/market_to_limit.rs, crates/model/src/orders/stop_market.rs, crates/model/src/orders/trailing_stop_limit.rs, crates/model/src/orders/trailing_stop_market.rs
<h4>1&nbsp;|&nbsp;Motivation</h4>
<ul>
<li>
<p>Several order variants (<code inline="">MarketIfTouched</code>, <code inline="">MarketToLimit</code>, <code inline="">StopMarket</code>, <code inline="">TrailingStopLimit</code>, and <code inline="">LimitIfTouched</code>) still printed fallback <em>Debug</em> output (⁎<code inline="">{:?}</code>⁎) in user‑facing logs and diagnostics.</p>
</li>
<li>
<p>An incomplete <code inline="">Display</code> cascade also meant that <code inline="">OrderAny::Display</code> returned inconsistent strings, breaking log parsing and making snapshots brittle.</p>
</li>
<li>
<p>TODO comments littered the codebase since <strong>v0.8.0</strong> (“// TODO: Implement”) and prevented the public API from being marked stable.</p>
</li>
<li>
<p>While touching the files …
=> Implement remaining Display for orders

crates/indicators/src/average/ama.rs
| Concern | Python / Cython (source of truth) | **Rust (before)** | **Rust (after this PR)** |
|---------|-----------------------------------|-------------------|--------------------------|
| **Parameter validation** | ✔ Positive ints, `slow > fast` | ✘ | **✔** identical asserts |
| **`count` increments** | ✔ | ✘ | **✔** now increments + tested |
| **`prior_value` reset** | ✔ | ✘ (left stale) | **✔** cleared in reset |
| **Comments accurate** | n/a | ✘ (misleading) | **✔** fixed |
| **Test coverage** | full | partial | **full parity** |
---
```mermaid
flowchart TD
A[call<br>AdaptiveMovingAverage::new] --> B{Validate arguments}
B -->|any zero| P1[[panic]]
B -->|slow ≤ fast| P2[[panic]]
B --> C[Construct fields<br>+ alpha_fast/slow<br>+ EfficiencyRatio::new]
C --> D[[Ready instance]]
``` …
=> Improve AMA indicator parity with Cython

Cargo.lock, crates/common/Cargo.toml, crates/common/benches/matching.rs, crates/common/src/msgbus/mod.rs, crates/common/src/msgbus/tests.rs
The message bus using pattern matching to identify subscribed topics to publish to. Message bus is on the hot path since each data item travels through it to respective strategies and components so performance and correctness is critical.
This PR adds regex based testing to validated matching logic with randomized testing. It also introduces an iterative algorithm with improves upon current implementation by 100x.
Using criterion shows that
* is_matching takes 2.5 us per match and scales linearly to 2.5 ms for 1000 topics
* regex takes 45 us to create dfa but scales almost constant time to 90 us for 1000 topics
* is_matching_backtracking does a whopping 25 ns per match …
=> Optimize message bus topic-matching logic by 100×

crates/indicators/src/average/ema.rs
**Improve EMA indicator parity with Cython**
Restores *feature-parity* and *behavioural equivalence* between the **Rust `ExponentialMovingAverage` (EMA)** implementation and the canonical Python/Cython reference.
---
| **Correctness ⇄ Consistency** | Mixed Python (quant research) + Rust/WASM (execution) stacks must produce *identical* indicator values or silent PnL drift creeps in. |
| **Predictable warm-ups & resets** | Edge-cases (e.g., period = 1, `reset()` after `NaN`) previously left the indicator in an undefined state. |
| **Baseline for SIMD hot-paths** | Before vectorising we need a byte-for-byte port; this PR closes the last gaps. |
---
| Concern | Python/Cython (🏆 truth) | Rust **before** | Rust **after** (this PR) | …
=> Improve EMA indicator parity with Cython

crates/indicators/src/average/hma.rs
Restores feature-parity and behavioural equivalence between the Rust **HullMovingAverage (HMA)** implementation and the canonical Python/Cython reference.
---
| **Correctness ⇄ Consistency** | Mixed Python (quant research) + Rust/WASM (execution) stacks must emit *identical* indicator values; divergence silently bleeds PnL. |
| **Predictable warm-ups & resets** | Edge-cases (e.g. `period = 1`, `reset()` after `NaN`) previously left the indicator in an undefined state. |
| **Baseline for SIMD hot-paths** | Before vectorising we need a byte-for-byte port; this PR closes the last functional gaps. |
---
| Concern | Python/Cython (🏆 truth) | Rust **before** | Rust **after** *(this PR)* | …
=> Improve HMA indicator parity with Cython

crates/indicators/src/average/rma.rs
Restores **feature-parity and behavioural equivalence** between the Rust `WilderMovingAverage` implementation and the canonical Python/Cython reference.
---
| Theme                           | Why it matters                                                                                                                                    |
|---------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
| **Correctness ⇄ Consistency**   | Mixed Python (quant research) + Rust/WASM (execution) stacks must emit identical indicator values; silent divergence leaks P n L.                 |
| **Predictable warm-ups & resets**| Edge-cases (e.g. `period = 1`, `reset()` after …
=> Improve RMA indicator parity with Cython

crates/indicators/src/average/rma.rs, crates/indicators/src/average/sma.rs
> This PR eliminates the last observable divergences between the Rust `SimpleMovingAverage`
> and the canonical Python/Cython reference by re-implementing state-handling, validating inputs,
> and—most importantly—adding a *fully mirrored, edge-case-heavy* test-suite.  
> We now hit **100 % line & branch coverage** on the SMA module.
---
| **Correctness ⇄ Consistency** | Mixed Python (research) + Rust/WASM (execution) stacks must emit identical averages; silent drift → mis-sized positions. |
| **Predictable warm-ups & resets** | Undefined init/reset paths previously delayed strategy start-up and left hidden state. |
| **Foundation for SIMD** | Before vectorising we need byte-for-byte parity; SMA was still off on several branches. |
| …
=> Improve SMA indicator parity with Cython 

crates/indicators/src/average/vidya.rs
Restores feature-parity and behavioural equivalence between the Rust `VariableIndexDynamicAverage` implementation and the canonical Python/Cython reference.
---
| **Correctness ⇄ Consistency** | Mixed Python (quant research) + Rust/WASM (execution) stacks must emit identical VIDYA values; silent divergence leaks P ∿ L. |
| **Predictable warm-ups & resets** | Edge-cases (e.g. `period = 1`, `reset()` after `NaN`) previously left the indicator in an undefined state. |
| **Baseline for SIMD hot-paths** | Before vectorising we need a byte-for-byte port; this PR closes the last functional gaps. |
| **Safety-first API** | Panics with descriptive messages before UB occurs, mirroring Python checks. |
| **Test-driven culture** | Full parity …
=> Improve Variable Index Dynamic Average (VIDYA) indicator parity with Cython 

crates/adapters/coinbase_intx/src/fix/client.rs, crates/adapters/demo/src/big_brain_actor.rs, crates/adapters/demo/src/lib.rs, crates/backtest/src/exchange.rs, crates/common/benches/matching.rs, crates/common/src/actor/data_actor.rs, crates/common/src/actor/tests.rs, crates/common/src/greeks.rs, crates/common/src/msgbus/core.rs, crates/common/src/msgbus/matching.rs, crates/common/src/msgbus/mod.rs, crates/common/src/msgbus/switchboard.rs, crates/common/src/msgbus/tests.rs, crates/common/src/python/msgbus.rs, crates/common/src/throttler.rs, crates/data/src/engine/book.rs, crates/data/src/engine/mod.rs, crates/data/tests/engine.rs, crates/execution/src/client/base.rs, crates/execution/src/engine/mod.rs, crates/execution/src/matching_engine/engine.rs, crates/execution/src/order_emulator/adapter.rs, crates/execution/src/order_emulator/emulator.rs, crates/execution/src/order_manager/manager.rs, crates/portfolio/src/portfolio.rs, crates/risk/src/engine/mod.rs
Use phantom types for Topic pattern for a more ergonomic and concise api. It also draws from design principle that both types have the same physical representation but have different validation properties. Also merged endpoints and topics since they are physically and functionally the same.
#2646
=> Improve ergonomics of messaging topics, patterns, and endpoints

crates/indicators/src/average/vidya.rs, crates/indicators/src/average/vwap.rs
Restores feature-parity and behavioural equivalence between the Rust `VolumeWeightedAveragePrice` implementation and the canonical Python/Cython reference.
---
| **Correctness ⇄ Consistency** | Mixed Python (quant research) + Rust/WASM (execution) stacks **must emit identical VWAP values**; silent divergence leaks `P ∿ L`. |
| **Predictable day roll-overs & resets** | Intraday VWAP re-seeds had undefined behaviour at the 00:00 UTC boundary and when timestamps went backwards. |
| **Robust zero-/neg-volume handling** | Division-by-zero or sign mistakes corrupt the price stream and cascade into downstream signals. |
| **Safety-first API** | Panics with descriptive messages before UB occurs; mirrors Python checks. |
| **Test-driven …
=> Improve Volume Weighted Average Price (VWAP) indicator parity with Cython

nautilus_trader/adapters/binance/config.py, nautilus_trader/adapters/binance/futures/enums.py, nautilus_trader/adapters/binance/futures/execution.py, nautilus_trader/adapters/binance/futures/http/account.py, nautilus_trader/adapters/binance/futures/schemas/account.py
`/fapi/v1/marginType` endpoint was added to change margin type from crossed to isolated and vice versa
It was tested manually on Binance Testnet and Mainnet.
=> Binance Futures margin type

Cargo.lock, crates/indicators/Cargo.toml, crates/indicators/src/average/sma.rs, crates/indicators/src/momentum/bias.rs, crates/indicators/src/momentum/macd.rs
`SimpleMovingAverage` slides over a window whose length (`period`) is *known up-front*.  
With the existing `std::collections::VecDeque` the queue can still **grow past that length**: each `push_back` that exceeds `capacity` triggers a heap re-allocation and mem-copy. `VecDeque` is explicitly documented as “a double-ended queue implemented with a **growable** ring buffer”.
Those reallocations are (a) wasted work—because we immediately `pop_front` afterwards—and (b) a latency spike on the trading hot-path.
`arraydeque::ArrayDeque`, on the other hand, is “a circular buffer with **fixed capacity** … [that] can be stored directly on the stack”.  
Its capacity is a *const generic* baked into the type, so pushes **never allocate** and never exceed the logical window.
---
| Aspect | `VecDeque` | …
=> Change VecDeque for fixed-capacity ArrayDeque in SMA

crates/indicators/src/momentum/amat.rs
| --- | --- |
| **Correctness ⇄ Consistency** | Quant-research (Python/Cython) and execution (Rust/WASM) pipelines must emit identical AMAT signals; silent drift leaks P ∿ L. |
| **Memory predictability** | The old `VecDeque` could silently grow and re-allocate, undermining latency guarantees; fixed-capacity `ArrayDeque` removes that risk. |
| **Defensive programming** | Construction-time assertions now guard against zero/invalid periods and out-of-range `signal_period`, surfacing config errors early. |
| **Simpler mental model** | A single `DEFAULT_MA_TYPE = Exponential` constant replaces scattered `unwrap_or(Simple)` calls; trend logic is condensed and explicit. |
| **Test-driven culture** | Test matrix grows from 8 → 34 cases, achieving 100 % line & branch …
=> Improve AMAT indicator parity with Cython

crates/data/src/aggregation.rs, examples/backtest/databento_test_request_bars.py, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/config.py, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, tests/unit_tests/backtest/test_config.py, tests/unit_tests/data/test_aggregation.py
+ Add bar_build_delay as params for SubscribeBars and request_aggregated_bars
Set through data engine config
Can be useful in a live context to account for network delays.
Can be useful in a backtest context when aggregating interal bars (themselves aggregated).
Allows a delay when aggregating bars to ensure they are received.
Refactors existing code to allow this.
Set through data engine config
subscribe_bars has a default value of 0
request_aggregated_bars has a default value of 15 and used only when aggregating bars from internal bars (INTERNAL@INTERNAL)
+ Also rename of time_bars_origin to time_bars_origin_offset
- New feature (non-breaking)
**Ensure new or changed …
=> Add bar_build_delay to data engine config

crates/model/src/defi/dex.rs
Add two `impl From<Pool>` blocks:
* `Pool → CurrencyPair`
* `Pool → InstrumentAny`
* Downstream services (price-feed, risk, matching) already speak `CurrencyPair`/`InstrumentAny`.
* Reduces boilerplate in adapters: `CurrencyPair::from(pool)` vs manually building IDs, symbols, increments.
=> Implement From<Pool> → CurrencyPair & InstrumentAny

RELEASES.md, nautilus_trader/indicators/rsi.pyx, tests/unit_tests/indicators/test_rsi.py
It fixes this issue: https://github.com/nautechsystems/nautilus_trader/issues/2673
It sets the previous indicator value for next iteration in case of division by 0
https://github.com/nautechsystems/nautilus_trader/issues/2673
I've tested code by running extensive backtest and comparing results.
=> Fix last value updating for RSI indicator

nautilus_trader/common/signal.py, tests/unit_tests/common/test_signal.py
=> Refine signal serialization and tests

RELEASES.md, nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/connection.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_connection.py
When IBKR connection is broken or not connected on the first try, it fails to reconnect.
Many exceptions are thrown during this process. Logic is not working correctly.
The number of threads/tasks doing reconnection simultaneously is growing over time, making many attempts per second.
If anybody wishes to comment on proposed changes, it would be great.
I tested manually connection/reconnection
=> Fix gateway/TWS reconnect process for IBKR

docs/integrations/ib.md, nautilus_trader/adapters/interactive_brokers/common.py, nautilus_trader/adapters/interactive_brokers/providers.py
Added optional "options_chain_exchange" parameter to IBcontract. Change option chain request to use this new parameter as exchange for options, if this parameter is not set will use underlying's exchange. 
This allow using a different exchange than the underlying's,  be it "SMART" or others.
ib doc updated accordingly
Close issue #2622 
- [X ] Breaking change (impacts existing behavior)
- [X ] Documentation update
Before : by default for US markets, "SMART" was applied as exchange for options. Use of ANY other exchange, including US ones was impossible
Now : Those who wish "SMART" exchange, or an exchange different from the underlying's have to specify it with …
=> Fix Interactive Brokers options chain issue

RELEASES.md, nautilus_trader/adapters/sandbox/execution.py, tests/integration_tests/adapters/sandbox/test_execution.py
This PR adds support for submitting order lists when using the sandbox execution client.
N/A
I attempted to add a unit test in the `tests/integration_tests/adapters/sandbox/test_execution.py` file, however, the current unit tests around sandbox execution are WIP, so I am not sure if my test case makes sense.
=> Add submit order list support for sandbox

nautilus_trader/adapters/interactive_brokers/client/connection.py
Thanks @faysou for advice!
Fix the issue "Failed to receive server version information." when connecting IB-TWS 10.30.1w/u on Chinese or maybe more different languages.
=> Fix IB-TWS connection issue with international languages

crates/model/src/instruments/mod.rs
| **Cython / Python Method**              | **Rust Method in `Instrument`** | **Notes on Parity**                              |
|----------------------------------------|---------------------------------|--------------------------------------------------|
| `symbol` (property)                    | `symbol(&self) -> &str`         | Same return semantics (borrowed `&str`).         |
| `venue` (property)                     | `venue(&self) -> &str`          | Same return semantics.                           |
| `get_cost_currency()`                  | `cost_currency(&self) -> &Currency` | Renamed for Rust style; logic identical.    |
| `make_price(value)`                    | `make_price(&self, value: f64)` | Rounds using instrument price-precision.         |
| `make_qty(value, …
=> Improve implementation, validations and testing for Rust instruments

nautilus_trader/accounting/manager.pyx, tests/unit_tests/portfolio/test_portfolio.py
Under certain scenarios when running backtests with a margin account I would end up with a negative balance, which was then unhandled and caused:
```
File "nautilus_trader/portfolio/portfolio.pyx", line 504, in nautilus_trader.portfolio.portfolio.Portfolio.update_order
File "nautilus_trader/accounting/manager.pyx", line 145, in nautilus_trader.accounting.manager.AccountsManager.update_balances
File "nautilus_trader/accounting/manager.pyx", line 473, in nautilus_trader.accounting.manager.AccountsManager._update_balance_single_currency
File "nautilus_trader/model/objects.pyx", line 1631, in nautilus_trader.model.objects.AccountBalance.__init__
File …
```
=> Gracefully handle negative balances

crates/persistence/src/backend/catalog.rs, nautilus_trader/persistence/catalog/parquet.py
https://github.com/nautechsystems/nautilus_trader/issues/2731
=> Fix catalog identifier matching to exact match

crates/common/src/clock.rs
This pull request introduces a new feature to handle cases where a time alert is set for the exact current time in the `TestClock` implementation. It ensures that such alerts fire immediately and includes corresponding unit tests to validate this behavior.
* [`crates/common/src/clock.rs`](diffhunk://#diff-f55837cf1da7013b6444193e26e0a1c72e2e6efa2c94aff0877d4e89eeb8858dR466-R469): Modified the `TestTimer::new` invocation to include a new `fire_immediately` parameter, which is set to `true` when the alert time equals the current time. This ensures immediate firing of the alert.
* [`crates/common/src/clock.rs`](diffhunk://#diff-f55837cf1da7013b6444193e26e0a1c72e2e6efa2c94aff0877d4e89eeb8858dR1649-R1668): Added a new test case, …
=> Add immediate firing capability for time alerts and corresponding test

Makefile
This pull request updates the `Makefile` to align with the latest Docker CLI syntax. The changes replace the deprecated `docker-compose` command with the newer `docker compose` command.
* **Updated Docker CLI commands**:
* Replaced `docker-compose` with `docker compose` for starting development services in the `start-services` target. (`Makefile`, [MakefileL271-R275](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L271-R275))
* Replaced `docker-compose` with `docker compose` for stopping development services in the `stop-services` target. (`Makefile`, [MakefileL271-R275](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L271-R275))
=> Update Makefile to use new docker compose syntax

crates/execution/src/matching_core/mod.rs, crates/execution/src/matching_engine/engine.rs, crates/execution/src/order_emulator/emulator.rs, crates/execution/src/trailing.rs, crates/model/src/orders/any.rs, crates/model/src/orders/mod.rs, crates/model/src/orders/trailing_stop_limit.rs, crates/model/src/orders/trailing_stop_market.rs
| # | Concern / Feature                                                   | Cython status (prod.) | Rust status *after* PR | Rust unit-tests present? |
|---|---------------------------------------------------------------------|-----------------------|------------------------|-------------------------|
| 1 | `activation_price` field on **TrailingStopMarketOrder**             | ✅ (#2610)            | ✅ (struct field, getter, `has_activation_price`) | ✅ (`trailing_stop_market` init tests) |
| 2 | `activation_price` field on **TrailingStopLimitOrder**              | ✅                   | ✅                    | ✅ (`trailing_stop_limit` init tests) |
| 3 | `is_activated` + `set_activated()` logic on both trailing types     | ✅                   | ✅ (new flag & method) | ✅ (activation path …
=> Add trailing stop orders activation_price support for Rust

RELEASES.md, nautilus_trader/accounting/manager.pyx, tests/unit_tests/accounting/test_cash.py, tests/unit_tests/portfolio/test_portfolio.py
The previous sequence was
Order accepted -> Lock capital / margin init -> fill order using *free* capital -> release locked capital / margin init
This PR changes the calculations on order fill to use the proper balance.
--
Not breaking.
PR introduces new test cases.
=> Fix balance updates on fill

nautilus_trader/adapters/dydx/common/enums.py, tests/integration_tests/adapters/dydx/test_parsing.py
Resolves KeyError in Nautilus Trader DYDX adapter by adding missing enum mappings for TAKE_PROFIT and TAKE_PROFIT_MARKET order types to prevent execution reconciliation failures.
***
=> Fix dYdX Take Profit order type mapping error

.docker/docker-compose.yml, Makefile, README.md, crates/infrastructure/TESTS.md, tests/integration_tests/infrastructure/README.md
- Add `init-services` target to initialize containers and database schema
- Add `purge-services` target to remove containers and volumes
- Update `start-services` and `stop-services` comment for clarity
- Add comprehensive infrastructure integration test documentation with Python and Rust examples
This improves the developer experience by providing clear, chainable make targets for managing integration test services with proper initialization and cleanup workflows.
=> Add integration test service management targets

crates/core/src/datetime.rs, crates/infrastructure/src/sql/models/enums.rs, crates/model/src/enums.rs, nautilus_trader/model/data.pxd, nautilus_trader/model/data.pyx, tests/integration_tests/adapters/binance/test_parsing_common.py, tests/unit_tests/data/test_aggregation.py, tests/unit_tests/model/test_bar.py
- Add YEAR aggregation type to BarAggregation enum across Rust, Cython, and SQL models
- Add year-based datetime manipulation functions (add_n_years, subtract_n_years) in core
- Implement comprehensive bar specification step validation for time-based aggregations
- Add get_interval_ns() method
- Enhance BarSpecification documentation with comprehensive examples and usage notes
- Add BarIntervalType enum (LEFT_OPEN, RIGHT_OPEN) for future aggregation refactorization
- Update tests to use valid bar specification steps, add validation coverage and interval_ns/timedelta coverage
Bar specifications with invalid steps for time-based aggregations will now raise ValueError on construction.
The YEAR bar aggregation is not fully implemented yet. This is preparation for a future refactorization.
=> Add YEAR aggregation and bar specification validation

crates/persistence/src/backend/catalog.rs, crates/persistence/src/backend/catalog_operations.rs, crates/persistence/src/backend/session.rs, crates/persistence/tests/test_catalog.rs, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_catalog_pyo3.py
- Fixed bug where tables in a parquet.py backend_session could have the same name when querying multiple instruments. Now an identifier information is also used in the table name as well as timestamp information start and end from the file name used for a table.
Thank you @lisiyuan656
https://github.com/nautechsystems/nautilus_trader/pull/2772
=> Fix catalog query of multiple instruments of same type

Makefile, tests/conftest.py
- Add memory tracking fixture to pytest that monitors RSS memory usage and tracemalloc
- Configure via environment variables:
- MEMORY_TRACKING_ENABLED_PY (default: false)
- MEMORY_LEAK_THRESHOLD_BYTES_PY (default: 1024 * 1024 * 10 bytes)
- Add parallel `make pytest-memory-tracking` target to run tests with tracking enabled
- Report memory leaks with initial, final, increase in MB, tracemalloc stats and snapshot with a test failure
- New feature for tests
=> Add Python memory leak detection for tests

crates/adapters/blockchain/src/rpc/http.rs
- added `Content-Type` header of `application/json` in all RPC requests from  `BlockchainHttpRpcClient`, which should be mandatory for most providers JSON-RPC endpoints
=> Fix RPC client content type header

crates/adapters/blockchain/src/cache/rows.rs, crates/adapters/blockchain/src/contracts/base.rs, crates/adapters/blockchain/src/data.rs, crates/adapters/blockchain/src/lib.rs, crates/common/src/actor/tests.rs, crates/data/tests/client.rs, crates/data/tests/engine.rs, crates/model/src/defi/amm.rs, crates/model/src/defi/mod.rs, crates/model/src/defi/validation.rs, crates/model/src/identifiers/instrument_id.rs, crates/model/src/identifiers/venue.rs
- added `is_dex` function in `Venue` to check if venue is DEX
- moved `validation.rs` from blockchain adapter package to the `model` crate in `defi` module
- finish `InstrumentId` validation to account for `{address}.{Chain}:{Dex}` methodology
- refactored `create_instrument_id` function to `Pool` to account for the new symbol in address format
- added tests
=> Standardize symbol validation for DEX pool InstrumentId

nautilus_trader/backtest/config.py
Allow to avoid requiring instrument_id or bar_spec in BacktestDataConfig for Bar queries as the code works without them.
Tested on databento_option_greeks.py
=> Refine BacktestDataConfig allowed queries for Bars

crates/adapters/blockchain/bin/node_test.rs, crates/adapters/blockchain/src/config.rs, crates/adapters/blockchain/src/contracts/erc20.rs, crates/adapters/blockchain/src/data/core.rs, crates/adapters/blockchain/src/python/config.rs, crates/adapters/blockchain/src/python/mod.rs
Added configurable filtering for DEX pools through the new `DexPoolFilters` struct, which defines the pool universe that the blockchain data client will monitor. 
The first filter `remove_pools_with_empty_erc20fields` (defaults to true) excludes pools containing tokens with missing name or symbol metadata - addressing edge cases from non-conforming ERC20 implementations, proxy contracts, or deprecated tokens. 
The configuration integrates with `Erc20Contract` through the `enforce_token_fields` parameter for conditional validation, and is fully exposed to Python bindings.
=> Introduce initial DEX Pool Filtering Configuration

crates/adapters/blockchain/src/contracts/erc20.rs, crates/adapters/blockchain/src/data/core.rs, crates/adapters/blockchain/src/factories.rs, docs/integrations/blockchain.md
This PR enhances the blockchain adapter's ability to handle non-standard ERC20 tokens commonly found in production environments. The changes ensure robust pool synchronization by properly categorizing and handling various token implementation issues.
**Changes**
- Set `allow_failure: true` for all ERC20 multicall operations to enable partial success and detailed error information
- Separate error types: `CallFailed` (contract/function missing) vs `DecodingError` (non-ABI encoded responses) vs `EmptyTokenField`
- Add comprehensive test coverage for real-world edge cases including non-ABI encoded tokens and empty metadata
- Include raw response data in errors for better …
=> Improve ERC20 token metadata handling and error recovery

nautilus_trader/adapters/polymarket/execution.py
There are cases when reconciling polymarket orders doesn't fill in the command.venue_order_id, but it is obtained from the cache (see line 485). However, this case appears not to have been thought of on line 504, which uses the immutable command.venue_order_id (despite the fact that a new venue_order_id variable was created on line 485), leading to an exception even if we got the venue from the cache.
This PR allows the query to go through in case we had to get the venue_order_id from the cache.
Tested on my strategy that was previously randomly failing due to exceptions here (usually happening when there were some …
=> Fix venue_order_id handling for Polymarket order status request

nautilus_trader/backtest/config.py, nautilus_trader/backtest/node.py, nautilus_trader/common/config.py, tests/unit_tests/backtest/test_config.py
Added functions to accept both enum and string type parameters (oms_type, account_type, book_type) in the constructor of the BacktestVenueConfig class. Also added related msg encoding/decoding cases.
https://github.com/nautechsystems/nautilus_trader/issues/2843
Added a test `def test_backtest_obj_data_config_to_dict(self)` in `tests/unit_tests/backtest/test_config.py`
=> Support both Enum and String types for BacktestVenueConfig

nautilus_trader/adapters/interactive_brokers/providers.py
This fix skips conversions to IBContract and IBContractDetails if these have been pulled from cache and are handed in as such already
Fixes #2860
=> Fix AttributeError when loading cached IBContract objects

crates/adapters/blockchain/src/cache/database.rs, crates/adapters/blockchain/src/cache/mod.rs, crates/adapters/blockchain/src/data/core.rs, crates/adapters/blockchain/src/exchanges/mod.rs, crates/adapters/blockchain/src/reporting.rs, crates/cli/src/blockchain/sync.rs, crates/cli/src/opt.rs, schema/sql/functions.sql, schema/sql/tables.sql
- Introduced table partitioning on `chain_id` for the `token` table with dedicated PL/pgSQL functions to create and drop partitions
- Improve DEX pool sync process with checkpoint saving and caching properly all the related pools and tokens
- Implement pool batching insertion in the Postgres cache database
- Separate invalid from valid tokens, persist the error message
- Added new CLI command `sync-pools` with proper parameters, enabling usage like `nautilus blockchain sync-pools --chain arbitrum  --dex uniswapv3`
=> Introduce efficient pool syncing command in the cli

.cargo/config.toml, Cargo.lock, Cargo.toml, crates/adapters/bitmex/Cargo.toml, crates/adapters/bitmex/src/common/credential.rs, crates/adapters/coinbase_intx/Cargo.toml, crates/adapters/coinbase_intx/src/common/credential.rs, crates/adapters/okx/Cargo.toml, crates/adapters/okx/src/common/credential.rs
Harden BitMEX credential handling and improve ergonomics.
* Store `api_secret` as `Box<[u8]>` and derive `ZeroizeOnDrop` (skipping `api_key`) so secrets are wiped from memory on drop.
* Implement a custom `Debug` that redacts the secret and add `Clone` for `Credential`.
* `sign()` behavior and public constructor remain unchanged; no breaking API changes.
* Adds `zeroize` (with `alloc`/`zeroize_derive`) and a unit test asserting debug redaction.
=> Improve security for Credential struct

nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, nautilus_trader/data/engine.pyx, tests/acceptance_tests/test_backtest.py
- Rename start params to start_ns used for databento and IB start time when subscribing to live data
- Add update_interval_seconds params for SpreadQuoteAggregator
- Add point_data params for on the fly download of data in order to download single points of data instead of ranges of data.
=> Rename start params to start_ns

crates/adapters/blockchain/src/cache/database.rs, crates/adapters/blockchain/src/cache/mod.rs, crates/adapters/blockchain/src/cache/rows.rs, crates/adapters/blockchain/src/events/pool_created.rs, crates/adapters/blockchain/src/exchanges/arbitrum/camelot_v3.rs, crates/adapters/blockchain/src/exchanges/ethereum/uniswap_v3.rs, crates/adapters/blockchain/src/hypersync/helpers.rs, crates/common/src/actor/tests.rs, crates/common/src/cache/tests.rs, crates/common/src/python/actor.rs, crates/data/tests/engine.rs, crates/model/src/defi/amm.rs, crates/model/src/python/defi/types.rs
- Refactor DEX event parsing to use reusable `extract_address_from_topic` helper function, eliminating code duplication across UniswapV3 parsers and providing proper test coverage for address extraction from event topics.
- Add Camelot V3 DEX support on Arbitrum with pool created event parsing and validation logic, enabling integration with this concentrated liquidity AMM.
- Make pool `fee` and `tick_spacing` fields optional across all modules to support DEXs where these values are either unavailable in initial pool creation events or are dynamic rather than static parameters.
=> Improve event parsing and integrate Arbitrum Camelotv3 new pools signature

crates/common/src/cache/mod.rs
This PR adds the missing `funding_rates` field to the Debug implementation for Cache.
Closes #2893
=> Fix missing funding_rates for Cache Debug impl

crates/adapters/databento/src/decode.rs
The decode_multiplier function was using floating-point arithmetic (value as f64 / 1e9)
followed by string formatting, which introduced precision loss for financial calculations.
This could lead to incorrect multipliers affecting P&L, position sizing, and risk calculations.
Changes:
- Replace floating-point division with exact integer arithmetic
- Handle fixed-point scaling (1e-9) using integer operations only
- Preserve exact decimal representation without rounding errors
- Add comprehensive test coverage for edge cases
- Remove unused DATABENTO_FIXED_SCALAR constant
The fix ensures multipliers are decoded with perfect precision, maintaining consistency
with other decode functions that use exact integer arithmetic for financial values.
=> Use precise integer arithmetic in decode_multiplier to prevent precision loss

crates/adapters/blockchain/src/data/core.rs, crates/adapters/blockchain/src/exchanges/arbitrum/fluid.rs
- fixed the empty token flush buffer bug (when you have tokens in the cache, buffer is empty and we wont flush the pools with this check)
- Added pool parsing function and event signature for the FluidDex on Arbitrum
=> Add Arbitrum FluidDEX pool parsing

nautilus_trader/adapters/bybit/schemas/account/balance.py
When parsing balances from Bybit, tokens with very high values (like MOG with trillions in circulation) can have floating point precision issues where the API returns values that don't exactly add up (total - locked != free).
This fix uses raw integer arithmetic to calculate the free balance, ensuring the AccountBalance invariant is always satisfied.
=> Fix Bybit balance precision errors for high-value tokens

docs/integrations/ib.md, nautilus_trader/adapters/interactive_brokers/execution.py, tests/integration_tests/adapters/interactive_brokers/test_execution_order_transform.py
Fix issue mentioned here 
https://github.com/nautechsystems/nautilus_trader/issues/2890#issuecomment-3225475956
Related
https://www.interactivebrokers.com/campus/trading-lessons/using-the-one-cancels-another-oca-order-attribute-in-ibkrs-ibusopt/
=> Add OCA setting to IB order groups

nautilus_trader/adapters/polymarket/providers.py
Utilize bulk CLOB markets API when requested to load over 200 instruments (feel free to adjust), as sequential requests for each are no longer effective.
Tested with 9000 instruments that were finally loaded using this path, which was impossible in the previous state. Note that iterating the entirety of CLOB markets still takes over 60 seconds, causing initialization warnings and general unease, but this step at least makes it possible to continue.
=> Improve Polymarket instrument provider bulk loading

nautilus_trader/adapters/polymarket/data.py
The polymarket adapter no longer works correctly if we exceed 500 order book deltas subscriptions. When that happens, no OrderBookDeltas messages are received anymore; this seems to be due to an undocumented WS API limitation of a maximum of 500 tokens per connection.
I've tried to address it by creating a new connection once we hit this limit, and for every 500 more thereafter.
My case was breaking when I exceeded 500 subscriptions, now it works with many more hundreds of them. However, I would still like to test whether the extra subscriptions are being received, although my preliminary findings seem to confirm that, as I see updates from markets I haven't seen before. …
=> Fix Polymarket websocket 500 tokens per connection limitation

nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/execution/client.pxd, nautilus_trader/execution/client.pyx
Add mising _send_position_status_report method so that a position update can happen when an option is physically exercised (there's not always an order fill from IB but there's always a position update).
=> Add _send_position_status_report to base execution client

crates/data/src/aggregation.rs, nautilus_trader/adapters/binance/common/schemas/market.py, nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/binance/http/market.py, nautilus_trader/adapters/binance/spot/schemas/market.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/http/market.py, nautilus_trader/adapters/bybit/schemas/market/kline.py, nautilus_trader/adapters/bybit/schemas/market/trades.py, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, tests/unit_tests/data/test_aggregation.py
- Refactor bar aggregators to use ts_init instead of ts_event
- Modify binance and bybit adapters so the result of historical data requests uses ts_init=ts_event
=> Refactor bar aggregators to use ts_init instead of ts_event

nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_aggregation.py
- Allows to pass through bars of the form "BTCUSDT-PERP.BINANCE-1-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL" through the TimeBarAggregator with minimal processing
- Add extra step to start timer of time bar aggregator by calling start method
=> Add passthrough_bar_type to TimeBarAggregator

nautilus_trader/backtest/engine.pyx
When using Binance OrderBookDelta data and Sandbox for simulated trading, the same order can generate two OrderFilled events because the executed quantity check is not performed, and the msgbus event push is incomplete. The executed quantity of the second event is 0.
=> Add matching engine check to return early if last_qty is non-positive

crates/common/src/ffi/logging.rs, crates/common/src/logging/logger.rs, crates/common/src/python/logging.rs, examples/backtest/notebooks/databento_option_greeks.py, nautilus_trader/common/component.pxd, nautilus_trader/common/component.pyx, nautilus_trader/common/config.py, nautilus_trader/core/includes/common.h, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/core/rust/common.pxd, nautilus_trader/system/kernel.py
```python
"""
log_components_only : bool, default False
If only components with explicit component-level filters should be logged.
When enabled, only log messages from components that have been explicitly
configured in `log_component_levels` will be output.
"""
```
Tested that the feature works in databento_option_greeks.py, setting log_components_only to True, the log level to DEBUG and the component level for a component to DEBUG
=> Add log_components_only option to Logger

nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/execution/reports.py, nautilus_trader/live/execution_engine.py
This PR adds support for the `avg_px_open` field in `PositionStatusReport` to properly track the average open price (cost basis) of positions when using the Interactive Brokers adapter.
Previously, when the IB adapter generated position status reports, it did not include the average open price information even though this data is available from IB's API (`avg_cost` field). This caused issues with:
- Accurate P&L calculations
- Position reconciliation 
- Tracking cost basis for tax and reporting purposes
The `target_position_avg_px` parameter in position reconciliation was always `None`, preventing accurate reconciliation when positions changed externally (e.g., through option exercises or assignments).
- Added optional `avg_px_open: Price | None` parameter to constructor
- Updated …
=> Add avg_px_open field to PositionStatusReport for IB adapter

crates/persistence/src/parquet.rs, nautilus_trader/persistence/catalog/parquet.py
Fix for an edge case when after consolidation the file name clashes with one of the original file names
=> Fix consolidation name clash for an overlapping edge case

nautilus_trader/persistence/catalog/parquet.py
- [ X] I have reviewed the `CONTRIBUTING.md` and followed the established practices
An additional parameter to support data deduplication that could have occurred due to using `skip_disjoint_check`
=> Add support for data deduplication on catalog consolidation

crates/adapters/bitmex/README.md, crates/adapters/hyperliquid/README.md, crates/adapters/hyperliquid/bin/http-private.rs, crates/adapters/hyperliquid/bin/http-public.rs, crates/adapters/hyperliquid/bin/ws-exec.rs, crates/adapters/hyperliquid/bin/ws-post.rs, crates/adapters/hyperliquid/src/common/consts.rs, crates/adapters/hyperliquid/src/common/credential.rs, crates/adapters/hyperliquid/src/http/client.rs, crates/adapters/okx/README.md, crates/adapters/okx/src/lib.rs, examples/live/hyperliquid/hyperliquid_data_tester.py, examples/live/hyperliquid/hyperliquid_exec_tester.py, nautilus_trader/adapters/hyperliquid/__init__.py, nautilus_trader/adapters/hyperliquid/config.py, nautilus_trader/adapters/hyperliquid/constants.py, nautilus_trader/adapters/hyperliquid/data.py, nautilus_trader/adapters/hyperliquid/execution.py, nautilus_trader/adapters/hyperliquid/factories.py, nautilus_trader/adapters/hyperliquid/providers.py
Introduce initial Hyperliquid adapter (configs, constants, providers, factories, placeholder data/execution clients), switch network selection to a simple testnet boolean and update URL helpers, Secrets, and HttpClient plus Rust bins to accept it; add live data/exec examples; small README and formatting fixes.
=> Continue Hyperliquid adapter scaffolding and examples

crates/adapters/hyperliquid/src/http/client.rs, crates/adapters/hyperliquid/src/http/error.rs, crates/adapters/hyperliquid/src/http/mod.rs, crates/adapters/hyperliquid/src/http/rate_limits.rs
Introduce a **weighted, minute-bucket rate limiter** for Hyperliquid REST and wire it into Info/Exchange calls. Supports **base weights per endpoint**, **post-response extra debits** (for item-scaled endpoints), **batch-aware Exchange costs**, and **bounded retries** with full-jitter + `Retry-After` handling. Surfaces structured `RateLimit { scope, weight, retry_after_ms }` errors.
* NT’s `Quota` is **uniform per request**; Hyperliquid requires **weighted** charges and **post-response** debits.
* No **batch-size awareness** in `Quota` (Exchange: `1 + floor(n/40)`).
* Adapter needs **minute bucket + anti-stampede** semantics and **exchange-specific weight tables**.
* `WeightedLimiter::per_minute(1200)`: token bucket; `acquire(weight)`, `debit_extra(extra)`, `snapshot()`.
* Weights: …
=> Implement Hyperliquid weighted rate limiter for REST API

nautilus_trader/adapters/polymarket/execution.py, nautilus_trader/adapters/polymarket/websocket/types.py, tests/integration_tests/adapters/polymarket/test_parsing.py
The ws message can contain a single message (which is not wrapped in a list).
See https://docs.polymarket.com/developers/CLOB/websocket/user-channel
See above.
N/A
The failing test before fix (message not wrapped in list) reproduces the error message.
However, I have not observed the fix in production yet, but I can probably let you know by tomorrow whether this does the trick.
=> Fix Polymarket ws user message

Cargo.toml
Adds `unicode-perl` feature to the regex crate dependency to fix compilation and runtime issues on macOS when running `nautilus database init` command.
The `nautilus database init` command fails on macOS with regex pattern compilation errors due to missing Unicode Perl compatibility features in the regex crate.
- Added `unicode-perl` feature to the regex dependency in `Cargo.toml`
- This enables Perl-compatible Unicode regex support required for proper pattern matching on macOS systems
- Maintains compatibility with existing regex usage while fixing macOS-specific issues
This change only adds a feature flag to the existing regex dependency and does not introduce new dependencies.
This change is backward compatible and only enhances regex functionality without breaking existing behavior.
=> Fix nautilus CLI macOS compatibility with regex unicode-perl feature

crates/adapters/hyperliquid/src/data/mod.rs, crates/adapters/hyperliquid/src/http/client.rs, crates/adapters/hyperliquid/src/http/conversion.rs, crates/adapters/hyperliquid/src/http/mod.rs, crates/adapters/hyperliquid/src/http/models.rs, crates/adapters/hyperliquid/src/http/parse.rs, crates/adapters/hyperliquid/src/http/query.rs, crates/adapters/hyperliquid/src/python/http.rs, crates/adapters/hyperliquid/src/python/mod.rs, crates/adapters/hyperliquid/src/signing/signers.rs, nautilus_trader/adapters/hyperliquid/__init__.py, nautilus_trader/adapters/hyperliquid/enums.py, nautilus_trader/adapters/hyperliquid/factories.py, nautilus_trader/adapters/hyperliquid/providers.py, python/nautilus_trader/adapters/hyperliquid/__init__.py
Related to: https://github.com/nautechsystems/nautilus_trader/issues/2981
=> Implement Hyperliquid InstrumentProvider / definitions parsing

nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py
Fixes a critical bug introduced in PR #2870 where historical bar subscriptions fail to resubscribe after IB Gateway disconnects/reconnects due to a parameter
signature mismatch. The fix stores start timestamps separately from the resubscription handle to prevent `TypeError` during automatic resubscription, restoring
proper data flow after connection loss.
Fixes #3001 
Related to #2870
N/A - This is a bug fix that restores intended behavior without changing the public API.
No documentation changes required (code-only fix).
Will add after review.
---
**Problem:**
- PR #2870 passes `start` as a separate kwarg to …
=> Fix IB historical bars resubscription failure after connection loss

crates/model/src/defi/pool_analysis/profiler.rs, crates/model/src/defi/pool_analysis/tests.rs
This change aligns `PoolProfiler::process_collect` with Uniswap V3's actual behavior by removing tick validation for collect events.
The profiler was validating ticks in `process_collect`, causing it to fail on legitimate on-chain collect events with invalid or edge-case tick values (e.g., `tick_lower == tick_upper`). This validation doesn't exist in Uniswap V3's collect function
because invalid positions never accumulate fees to collect.
**Example transaction that caused the error:**
https://arbiscan.io/tx/0x9d8d8511ea136be6758bf7cdfb71e18297ebfc54273552c7c4ddf2c8e40387e2#eventlog#31
**Error logs:**
```
2025-10-01T14:22:43.640Z INFO  [nautilus_cli::blockchain::analyze] Profiling pool events from database...
2025-10-01T14:22:55.636Z ERROR [nautilus] Error executing Nautilus CLI: Invalid …
```
=> Remove tick validation in collect processing for pool profiler

nautilus_trader/backtest/config.py, nautilus_trader/backtest/node.py, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/persistence/config.py, nautilus_trader/system/kernel.py
Allows to have rust specific parameters for querying with the rust catalog as they can be different in name from Python parameters. Thanks to @Johnkhk  for the suggestion.
Also updated BacktestDataConfig, DataCatalogConfig and StreamingConfig accordingly as well as code using them.
=> Add fs_rust_storage_options to Python catalog

crates/model/src/defi/pool_analysis/compare.rs, crates/model/src/defi/pool_analysis/profiler.rs, crates/model/src/defi/tick_map/full_math.rs, crates/model/src/defi/tick_map/mod.rs
Prior to this change, swap simulation logic was likely duplicated or fragmented across `execute_swap` (forward simulation) and `process_swap` (historical replay). This created several critical issues:
- Algorithmic drift risk: Two implementations of the same UniswapV3 math could diverge over time
- Bug multiplication: Fixes needed to be applied in multiple places
- Testing complexity: Same algorithm tested multiple times with potential inconsistencies
- Maintenance burden: Changes to swap logic required coordinating updates across functions
This refactoring extracted all UniswapV3 swap mathematics into a single, canonical implementation: 
- `simulate_swap_through_ticks`: …
=> Unify swap simulation logic in AMM Pool Profiler

nautilus_trader/backtest/engine.pyx
fix(backtest): fallback to standard market fills when simulated book yields no fills
When using custom FillModel implementations like OneTickSlippageFillModel that
create simulated OrderBooks without liquidity at best bid/ask prices, market
orders would fail to fill entirely. This change adds a fallback mechanism that
reverts to the standard market fill logic when the simulated book produces no
fills, ensuring market orders always execute while still allowing custom models
to apply their intended slippage behavior when liquidity is available.
Fixes issue where OneTickSlippageFillModel prevented market order fills when
the simulated book contained no orders at best bid/ask prices (zero quantity
BookOrders), causing strategies to fail unexpectedly in backtesting.
- Modified …
=> Add fallback to default order book for custom fill model

nautilus_trader/adapters/interactive_brokers/data.py
Fix IBKR adapter bars request `TypeError: _handle_bars() takes exactly 6 positional arguments (7 given)`
#3020
=> Fix IBKR adapter bars request
