nautechsystems/nautilus_trader

nautilus_trader/__init__.py, setup.py
- Needs pyzmq>=19.0.1 to be able to compile C headers
- Bump version as release
=> Fix package installation issue

nautilus_trader/__init__.py, nautilus_trader/model/objects.pxd, nautilus_trader/model/objects.pyx, nautilus_trader/serialization/data.pyx, tests/unit_tests/model/test_model_objects.py
- Improve efficiency of Tick and Bar serialization
- Fix tests
- Bump version
=> Improve serialization efficiency

nautilus_trader/model/position.pyx, tests/unit_tests/backtest/test_backtest_simulated_broker.py
As part of the refactoring, commissioning functionality in Position was broken. This PR fixes it.
=> Fix applying the commission to position & tests

nautilus_trader/__init__.py, nautilus_trader/execution/cache.pyx, nautilus_trader/execution/engine.pxd, nautilus_trader/execution/engine.pyx, nautilus_trader/trading/strategy.pyx, tests/unit_tests/common/test_common_generators.py, tests/unit_tests/execution/test_engine.py
=> ExecutionEngine now handles position flipping

nautilus_trader/__init__.py, nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/exchange.pxd, nautilus_trader/backtest/exchange.pyx, nautilus_trader/backtest/execution.pxd, nautilus_trader/backtest/execution.pyx, nautilus_trader/backtest/loaders.pyx, nautilus_trader/model/instrument.pxd, nautilus_trader/model/instrument.pyx, nautilus_trader/model/position.pxd, nautilus_trader/model/position.pyx, nautilus_trader/trading/portfolio.pyx, scripts/instruments.py, tests/acceptance_tests/test_backtest_acceptance.py, tests/unit_tests/backtest/test_backtest_market_bitmex.py, tests/unit_tests/backtest/test_backtest_market_fxcm.py, tests/unit_tests/trading/test_trading_portfolio.py, tests/unit_tests/trading/test_trading_strategy.py, tests/unit_tests/trading/test_trading_trader.py
=> Refactor SimulatedExchange

nautilus_trader/adapters/ccxt/execution.pyx
fix the issue.
https://github.com/nautechsystems/nautilus_trader/issues/339
=> Fix TypeError when timestamp is None

tests/unit_tests/data/test_data_aggregation.py, tests/unit_tests/data/test_data_client.py, tests/unit_tests/data/test_data_engine.py, tests/unit_tests/data/test_data_messages.py, tests/unit_tests/data/test_data_wrangling.py
The following files have been converted (5 total):
- tests/unit_tests/data/*.py
=> Convert unittest tests to pytest (tests/unit_tests/data)

tests/unit_tests/execution/test_execution_client.py, tests/unit_tests/execution/test_execution_engine.py
The following files have been converted (2 total):
tests/unit_tests/execution/*.py
=> Convert unittest tests to pytest (tests/unit_tests/execution)

tests/unit_tests/cache/test_data_base.py, tests/unit_tests/cache/test_data_cache.py, tests/unit_tests/cache/test_execution_base.py, tests/unit_tests/cache/test_execution_cache.py
The following files have been converted (4 total):
- tests/unit_tests/cache/*.py
=> Convert unittest tests to pytest (tests/unit_tests/cache)

README.md, RELEASES.md, examples/live/betfair_live_test.py, nautilus_trader/data/engine.pyx, poetry.lock, pyproject.toml
Patch release. See release notes.
=> Release 1.126.1

nautilus_trader/adapters/betfair/common.pyx, nautilus_trader/adapters/betfair/execution.pyx, nautilus_trader/adapters/betfair/parsing.py, nautilus_trader/backtest/data_loader.py, nautilus_trader/serialization/arrow/core.pyx, nautilus_trader/serialization/arrow/implementations/closing_prices.py, nautilus_trader/serialization/arrow/schema.py, poetry.lock, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/integration_tests/adapters/betfair/test_common.py, tests/integration_tests/adapters/betfair/test_parsing.py
- Fix a bug in order submit
- Clean up some BSP naming
- Couple of minor fixes to parquet serialization
=> Handful of betfair fixes

nautilus_trader/analysis/performance.pyx
=> Fix `max_loser` stat

.github/workflows/build.yml, .github/workflows/release.yml, README.md
=> Release 1.130.0

nautilus_trader/adapters/betfair/util.py, nautilus_trader/live/node.py, nautilus_trader/persistence/config.py
Add (optional) feather persistence and logging to TradingNode
=> Add persistence to live node

nautilus_trader/common/events/risk.pyx, tests/unit_tests/common/test_common_logging.py
Fix typeo in docs and test codes.
=> Fix typeo in docs and test codes

nautilus_trader/persistence/catalog.py, tests/unit_tests/persistence/external/test_core.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_streaming.py
=> Add bars method to catalog

nautilus_trader/adapters/ftx/http/client.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Fix the ftx query requests

nautilus_trader/adapters/ftx/factories.py, nautilus_trader/adapters/ftx/http/client.py
- Add sub account option for HTTP client.
- Fix handling of HTTP params.
=> Fix FTX signed requests containing query params

.binder/requirements.txt, README.md, RELEASES.md, poetry.lock, pyproject.toml, tests/integration_tests/adapters/betfair/test_betfair_providers.py, version.json
Security patch for `pillow < 9.0.0` vulnerabilities. See release notes.
=> Release 1.137.1 security patch

nautilus_trader/serialization/arrow/implementations/bar.py, nautilus_trader/serialization/arrow/schema.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/serialization/test_serialization_arrow.py
Add `instrument_id` to Bar persistence. This should close #552 and #532
=> Add instrument_id to Bar persistence

nautilus_trader/persistence/batching.py, nautilus_trader/persistence/external/core.py
Attempt to fix issues with pyarrow datasets
=> Fix bug in parquet dataset writer

nautilus_trader/persistence/external/core.py, nautilus_trader/persistence/external/readers.py, tests/unit_tests/persistence/test_metadata.py
=> Fixes to catalog/reader

nautilus_trader/adapters/binance/spot/execution.py
update order status to be inflight immediately without delay
=> Update order status inflight immediatelly

nautilus_trader/adapters/binance/spot/execution.py, nautilus_trader/execution/client.pxd, nautilus_trader/execution/client.pyx, nautilus_trader/execution/engine.pxd, nautilus_trader/execution/engine.pyx, nautilus_trader/execution/messages.pxd, nautilus_trader/execution/messages.pyx, nautilus_trader/trading/strategy.pxd, nautilus_trader/trading/strategy.pyx, tests/integration_tests/adapters/binance/test_execution_spot.py
=> sync order status

nautilus_trader/persistence/external/core.py
change  basename_template_name to store the same time  but different type bar
1328054400000000000-1328830260000000000-SIM-1-MINUTE-ASK-EXTERNAL-0.parquet
1328054400000000000-1328830260000000000-SIM-1-MINUTE-BID-EXTERNAL-0.parquet
=> change basename_template

.pre-commit-config.yaml, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/gateway.py, nautilus_trader/adapters/interactive_brokers/historic.py, nautilus_trader/adapters/interactive_brokers/providers.py
Couple of improvements to IB adapter:
- Add `get_future_chain_details`
- Fix bug + cleanup historic data loading into DataCatalog
=> IB improvments

build.py
Added list of filenames used by cythonize function.
Build completed without error.
=> windows linker error fix

nautilus_core/core/src/buffer.rs
Add property tests for Buffer trait
- [ x ] Add tests
Tests were run and they passed
=> Add property tests for Buffer trait

nautilus_core/core/src/buffer.rs, nautilus_core/core/src/uuid.rs, nautilus_core/model/src/identifiers/instrument_id.rs, nautilus_core/model/src/identifiers/symbol.rs, nautilus_core/model/src/identifiers/trade_id.rs, nautilus_core/model/src/identifiers/venue.rs, nautilus_core/model/src/orderbook/order.rs, nautilus_core/model/src/types/currency.rs, nautilus_core/model/src/types/money.rs, nautilus_core/model/src/types/price.rs, nautilus_core/model/src/types/quantity.rs
Use idiomatic `From` trait to implement conversion from `&str` to a struct.
- [ x ] Refactor
Ran tests
=> Refactor models using `From` trait

nautilus_core/Cargo.lock, nautilus_core/core/src/buffer.rs, nautilus_core/model/Cargo.toml, nautilus_core/model/benches/criterion_fixed_precision_benchmark.rs, nautilus_core/model/benches/iai_fixed_precision_benchmark.rs
Benchmark f64_to_fixed_i64
Add tests for Buffer
- [ x ] Add tests
- [ x ] Add benchmarks
tested and benchmarked
=> Add benchmark setup

nautilus_trader/adapters/interactive_brokers/historic.py, tests/integration_tests/adapters/interactive_brokers/test_historic.py
Persist instruments when pulling historic data from Interactive Brokers
=> Persist instruments when pulling historic data

examples/live/betfair.py, nautilus_trader/adapters/betfair/config.py, nautilus_trader/adapters/betfair/factories.py, tests/integration_tests/adapters/betfair/test_betfair_factory.py
Update betfair examples to new config format
=> Update betfair examples to new config

examples/live/interactive_brokers_example.py, nautilus_trader/adapters/betfair/factories.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/gateway.py, nautilus_trader/adapters/interactive_brokers/providers.py, tests/integration_tests/adapters/interactive_brokers/test_execution.py
- Allow IB instrument instrument filters to take multiple filters
=> IB instrument filters

nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/factories.py
interested in early feedback.
Pass client_id and start_geteway or not for IB adapter from config.
trivial change. not tested yet. learning curve for nautilus trader.
=> feature(IB): pass clientId and start_gateway from config layer

nautilus_trader/adapters/interactive_brokers/data.py, tests/integration_tests/adapters/interactive_brokers/test_data.py
Related to this issue:
https://github.com/nautechsystems/nautilus_trader/issues/706
Tested locally
=> Fix IB contract ID dict

nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/providers.py, tests/integration_tests/adapters/interactive_brokers/test_data.py, tests/integration_tests/adapters/interactive_brokers/test_providers.py
Fix a couple of IB bugs (#685 and #712) 
Added tests
=> Fix IB bugs

nautilus_trader/model/instruments/future.pyx, nautilus_trader/model/instruments/option.pyx, tests/unit_tests/model/test_model_instrument.py
Fixes a bug in Future/Option to_dict
Added tests
=> Fix Future/Option to_dict

nautilus_trader/backtest/models.pxd, nautilus_trader/backtest/models.pyx, tests/unit_tests/backtest/test_backtest_exchange.py
Fix overflow bug in LatencyModel
=> Latency model bug

nautilus_core/Cargo.lock, nautilus_core/common/Cargo.toml, nautilus_core/persistence/Cargo.toml, nautilus_core/persistence/src/parquet/mod.rs, nautilus_core/persistence/src/parquet/quote_tick.rs
Upgrade arrow2 dep to latest release
cargo test
=> Upgrade arrow2 dep

nautilus_trader/system/kernel.pyx, nautilus_trader/trading/trader.pxd, nautilus_trader/trading/trader.pyx
Pass loop argument to clock initialization when trader add actors and strategies.
TestClock not affected, so no new test added.
Fix #743
=> Fix Live Trading LiveClock

nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/gateway.py, tests/integration_tests/adapters/interactive_brokers/test_execution.py, tests/integration_tests/adapters/interactive_brokers/test_kit.py
Please describe how this code was/is tested.
=> Implement cancel order, some cleanup

nautilus_trader/data/engine.pyx, nautilus_trader/persistence/catalog/base.py, tests/test_kit/stubs/data.py, tests/unit_tests/data/test_data_engine.py
=> Cache orderbook

nautilus_trader/persistence/catalog/parquet.py
=> Remove old exception details

nautilus_core/core/src/cvec.rs, nautilus_core/persistence/src/parquet/mod.rs, nautilus_trader/core/includes/core.h, nautilus_trader/core/includes/persistence.h, nautilus_trader/core/rust/core.pxd, nautilus_trader/core/rust/persistence.pxd, nautilus_trader/persistence/catalog/rust/common.pyx, nautilus_trader/persistence/catalog/rust/reader.pyx, nautilus_trader/persistence/catalog/rust/writer.pxd, nautilus_trader/persistence/catalog/rust/writer.pyx, nautilus_trader/persistence/catalog/rust/writer_test.py
ParquetWriter Cython wrapper class progress.
=> ParquetWriter

.docker/nautilus_trader.dockerfile, RELEASES.md, build.py, docs/conf.py, nautilus_core/Cargo.lock, nautilus_trader/adapters/ftx/parsing/common.py, nautilus_trader/adapters/ftx/parsing/http.py, poetry.lock, pyproject.toml, version.json
=> Release 1.155.0

nautilus_trader/adapters/interactive_brokers/historic.py, tests/integration_tests/adapters/interactive_brokers/test_historic.py
=> Fix IB historic tick parsing test

nautilus_trader/config/backtest.py, nautilus_trader/examples/strategies/signal_strategy.py, nautilus_trader/persistence/streaming.py, tests/unit_tests/persistence/test_streaming.py
Fixes a bug in signal persistence
=> Fix streaming reading for signal data

nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/examples/strategies/signal_strategy.py, nautilus_trader/persistence/streaming.py, tests/unit_tests/backtest/test_backtest_engine.py, tests/unit_tests/common/test_common_actor.py, tests/unit_tests/persistence/test_streaming.py
Fix bug in ParquetSerializer when running multiple backtests.
=> Persistence bug multiple backtest runs

nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, nautilus_trader/trading/trader.pxd, nautilus_trader/trading/trader.pyx, tests/unit_tests/backtest/test_backtest_engine.py
Fixes strategy clock not advancing with backtest
=> Fix strategy clock not advancing

nautilus_trader/network/socket.pxd, nautilus_trader/network/socket.pyx, poetry.lock, tests/integration_tests/network/conftest.py, tests/integration_tests/network/test_socket.py
Please describe how this code was/is tested.
=> Fix reconnection on socket incomplete read

nautilus_trader/serialization/arrow/implementations/order_events.py, nautilus_trader/serialization/arrow/schema.py, tests/test_kit/stubs/events.py, tests/unit_tests/serialization/test_serialization_arrow.py
Fix a bug in `OrderUpdated` serialization
=> Fix serialization for OrderUpdated

nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py
Fix bug in list_partitions
Added test
=> Fix bug in list_partitions

nautilus_trader/config/live.py, nautilus_trader/live/node_builder.py, tests/integration_tests/live/test_live_node.py
=> Correct loading factory when using dict config with TradingNode

nautilus_trader/backtest/__main__.py, nautilus_trader/backtest/node.py, nautilus_trader/config/backtest.py, tests/integration_tests/adapters/betfair/test_kit.py, tests/test_kit/stubs/config.py, tests/unit_tests/backtest/test_backtest_config.py
BacktestRunConfig to use NautilusConfig, fix bug in parse_obj
=> BacktestRunConfig to use NautilusConfig, fix bug in parse_obj

examples/live/interactive_brokers_book_imbalance.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/parsing/execution.py, nautilus_trader/examples/strategies/orderbook_imbalance.py, tests/integration_tests/adapters/interactive_brokers/responses/account_values.json, tests/integration_tests/adapters/interactive_brokers/test_execution.py, tests/integration_tests/adapters/interactive_brokers/test_kit.py
Couple of fixes/cleanup to IB execution
=> Fixes/cleanup to IB execution

examples/live/interactive_brokers_book_imbalance.py, examples/live/interactive_brokers_example.py, nautilus_trader/adapters/interactive_brokers/providers.py
Fixes IB's Instrument providers filters broken after removal of Pydantic PR #890.
Instrument loads properly as expected.
P.S: Feel free to modify if you prefer different approach.
=> Breakfix for Instrument filters after PR #890

examples/live/betfair.py, nautilus_trader/adapters/betfair/client/core.py, tests/integration_tests/adapters/betfair/test_betfair_client.py, tests/integration_tests/adapters/betfair/test_kit.py
Please describe how this code was/is tested.
=> Fix SSL bug in live

nautilus_trader/backtest/data/wranglers.pyx
Fix for #923. Please check if makes sense.
=> Fix Wrangler process_bar_data NaN Bars

nautilus_trader/serialization/arrow/implementations/order_book.py
Please describe how this code was/is tested.
=> Fix for empty deltas

nautilus_trader/adapters/betfair/parsing/streaming.py, nautilus_trader/test_kit/stubs/data.py, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/integration_tests/adapters/betfair/test_betfair_parsing.py, tests/unit_tests/model/test_orderbook.py
- Fix a bug in BSPOrderBookDeltas
- Cleanup some betfair & orderbook tests
=> Merge BSPOrderBookDeltas, cleanup some tests

nautilus_trader/adapters/interactive_brokers/data.py
This PR allows live subscriptions to different BarTypes in addittion to default 5-sec from IB. Also provides historical data on subscription.
=> Added support for IB historical data and more Bar sizes

nautilus_trader/model/data/bar.pyx
This PR adds the method to BarSpecification to build specification from timedelta.
=> Add support to build BarSpecification from timedelta

nautilus_trader/adapters/betfair/execution.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/live/data_client.py, nautilus_trader/live/execution_client.py
Refactor `self._loop.create_task` into `self.create_task`
=> Refactor create_task for base classes

nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/parsing/data.py, nautilus_trader/config/live.py
This PR will fix connectivity issues, maintain subscriptions and adds refinement for Bar data requests.
- Added watch_dog for monitoring connectivity. Resolves connectivity/subscription issues caused by IB nightly reset and TWS/Gateway restart. Subscriptions will be maintained.
- Removed dict for BarType subscriptions and used the one inherited from parent class
- Refined historical subscription, upon resubscription will load the missing gap bars only (from last received bar onward)
- Added handle_revised_bars config option in LiveDataClientConfig, default to False (existing behavior)
- Moved parsing functions to parsing section i.e. parse_bar_data, bar_spec_to_bar_size, and bar_spec_to_duration_str
As usual, any code level improvements you deem fit will be appreciated.
=> IB DataClient improvements

nautilus_trader/adapters/betfair/data_types.py, tests/integration_tests/adapters/betfair/test_betfair_persistence.py
Tiny fix to BetfairStartingPrice serialization
=> Fix inconsistency in bsp serialization

nautilus_trader/common/actor.pyx, nautilus_trader/data/client.pxd, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx
=> Fix routing for status updates

nautilus_core/persistence/tests/test_parquet_reader.py, nautilus_core/pyo3/src/lib.rs, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_catalog_rust.py
Fix path name so that import works with submodule
Relevant tests were run.
=> Fix submodule import path

build.py, tests/unit_tests/persistence/test_catalog_rust.py
Fix broken/skipped parquet reader tests
Fixing tests and checking by running them
=> Fix parquet reader tests

build.py, nautilus_core/persistence/src/lib.rs, nautilus_core/persistence/tests/test_parquet_reader.rs, nautilus_core/persistence/tests/test_persistence_module.py, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_catalog_rust.py
Writer was expecting to receive a pointer to a buffer was instead receiving a CVec. The logic is now updated to receive a CVec. And a couple of other changes
All persistence module tests are passing
=> Fix persistence module tests

nautilus_trader/system/kernel.py
Skip setting loop in backtest environment
=> Skip setting loop in backtest environment

nautilus_trader/backtest/node.py, nautilus_trader/common/actor.pyx, nautilus_trader/config/backtest.py, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/persistence/streaming/batching.py, nautilus_trader/persistence/streaming/engine.py, nautilus_trader/persistence/streaming/writer.py, nautilus_trader/system/kernel.py, tests/unit_tests/backtest/test_backtest_config.py, tests/unit_tests/common/test_common_actor.py, tests/unit_tests/persistence/external/test_core.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_streaming.py, tests/unit_tests/persistence/test_streaming_batching.py, tests/unit_tests/persistence/test_streaming_engine.py
Refactored batching module into three separate classes to allow merging of nautilus object batches sourced from rust
1. StreamingEngine
2. BufferIterator
3. StreamingBuffer
Added BacktestDataConfig.bar_spec
Added BacktestDataConfig.use_rust
Refactored generate_batches into two separate methods, generate_batches_rust and generate_batches
batching/tests/unit_tests/persistence/test_streaming_engine.py
batching/tests/unit_tests/persistence/test_streaming_batching.py
=> Implement rust batching

tests/integration_tests/adapters/betfair/test_kit.py, tests/unit_tests/persistence/test_streaming.py
Fix for streaming test:
tests.unit_tests.persistence.test_streaming.TestPersistenceStreaming.test_feather_writer
=> Fix streaming test

examples/live/betfair.py, nautilus_trader/adapters/betfair/data.py, nautilus_trader/examples/strategies/orderbook_imbalance.py, tests/integration_tests/adapters/betfair/test_betfair_data.py
Fix warnings when calling betfair subscribe methods
=> Betfair ticker

nautilus_trader/adapters/betfair/execution.py, nautilus_trader/network/socket.pxd, nautilus_trader/network/socket.pyx, tests/integration_tests/network/test_socket.py
Update `SocketClient` flow to match existing `WebSocketClient` flow. Fix a bug in shutdown infinite loop.
Tested live running instance.
=> Fix stopping socket client

nautilus_trader/backtest/data/providers.py, nautilus_trader/test_kit/stubs/data.py, tests/integration_tests/orderbook/test_orderbook.py
Cleaning up some imports and paths that break in downstream packages.
=> Downstream dev

nautilus_trader/common/actor.pyx, tests/unit_tests/common/test_common_actor.py
Fix attribute in Actor.on_bars
Optimising for coverage
=> Fix attribute in Actor.on_bars

nautilus_trader/adapters/interactive_brokers/execution.py, tests/integration_tests/adapters/interactive_brokers/responses/account_values_fa.json, tests/integration_tests/adapters/interactive_brokers/test_execution.py, tests/integration_tests/adapters/interactive_brokers/test_kit.py
- Improve logging in IB account failures, add extra test
- Remove an old test (generate pending cancel) 
tests
=> Add test and better logging for account failures, remove old test

.github/workflows/release.yml, examples/notebooks/backtest_fx_usdjpy.ipynb, examples/notebooks/external_data_backtest.ipynb, examples/notebooks/quick_start.ipynb, nautilus_core/Cargo.lock, nautilus_trader/adapters/betfair/parsing/requests.py, nautilus_trader/adapters/betfair/parsing/streaming.py, nautilus_trader/backtest/engine.pyx, nautilus_trader/model/orders/base.pyx, nautilus_trader/system/kernel.py, nautilus_trader/trading/filters.pyx, poetry.lock, tests/unit_tests/persistence/external/test_core.py, tests/unit_tests/persistence/external/test_parsers.py
=> Release 1.170.0

nautilus_trader/common/clock.pyx
=> Minor fix in Clock

build.py
Enable symbol stripping for Mac x86
=> mac x86 strip symbols

nautilus_core/persistence/Cargo.toml
Disables the default feature causing the build issue.
https://github.com/BLAKE3-team/BLAKE3/issues/298
=> fix windows datafusion build

.github/workflows/release.yml, .gitignore, .pre-commit-config.yaml, RELEASES.md, nautilus_core/Cargo.lock, nautilus_trader/adapters/binance/common/execution.py, nautilus_trader/adapters/binance/futures/execution.py, nautilus_trader/adapters/binance/spot/enums.py, nautilus_trader/adapters/binance/spot/execution.py, nautilus_trader/analysis/reporter.py, nautilus_trader/backtest/engine.pyx, nautilus_trader/backtest/matching_engine.pxd, nautilus_trader/backtest/matching_engine.pyx, nautilus_trader/execution/algorithm.pyx, nautilus_trader/execution/emulator.pyx, nautilus_trader/infrastructure/cache.pyx, nautilus_trader/live/data_client.py, nautilus_trader/live/execution_engine.py, nautilus_trader/live/node.py, nautilus_trader/model/currencies.pyx, nautilus_trader/model/position.pyx, nautilus_trader/system/kernel.py, nautilus_trader/trading/strategy.pyx, poetry.lock, pyproject.toml, tests/acceptance_tests/test_backtest.py, tests/unit_tests/model/test_model_position.py, version.json
=> Release 1.173.0

nautilus_trader/test_kit/mocks/data.py, tests/acceptance_tests/test_backtest.py, tests/integration_tests/adapters/betfair/test_betfair_providers.py, tests/unit_tests/backtest/test_backtest_data_loaders.py, tests/unit_tests/common/test_common_actor.py
Unskip Windows tests which are working now.
Passed on local machine. Trying if pass the CI.
=> Unskip Windows Tests

examples/live/interactive_brokers_example.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/adapters/interactive_brokers/providers.py
Improve expired Future Instruments download and update example
=> Improve expired Future Instruments download and update example

nautilus_trader/adapters/betfair/common.py, nautilus_trader/adapters/betfair/providers.py, nautilus_trader/model/instruments/betting.pyx, nautilus_trader/test_kit/providers.py
Tiny cleanup for BettingInstrument + betfair.
=> Tiny cleanup

tests/mem_leak_tests/crypto_ema_cross_ethusdt_trailing_stop_mem_leak.py, tests/mem_leak_tests/fx_ema_cross_bracket_gbpusd_bars_internal_mem_leak.py, tests/mem_leak_tests/fx_market_maker_gbpusd_bars_mem_leak.py
Created a directory with memory leak testing for 3 backtests.
=> Add memory leak tests

.gitignore, nautilus_core/Cargo.lock, nautilus_core/Cargo.toml, nautilus_core/common/cbindgen.toml, nautilus_core/common/cbindgen_cython.toml, nautilus_core/common/src/clock.rs, nautilus_core/common/src/timer.rs, nautilus_core/core/cbindgen.toml, nautilus_core/core/cbindgen_cython.toml, nautilus_core/core/src/string.rs, nautilus_core/model/cbindgen.toml, nautilus_core/model/cbindgen_cython.toml, nautilus_core/model/src/events/order.rs, nautilus_core/model/src/events/order_api.rs
Use ustr implementation for serde that was behind feature flag
PR tests
=> Use ustr serde implementation

nautilus_core/persistence/benches/bench_persistence.rs
Fix benchmark after session refactor
Ran the benchmark
=> Fix persistence benchmark

nautilus_trader/model/orderbook/book.pyx, nautilus_trader/test_kit/stubs/data.py, tests/unit_tests/model/test_orderbook.py, tests/unit_tests/persistence/test_streaming.py
Add missing fields to orderbook pickle.
Fixed test.
=> Add ts_last and sequence_id to orderbook pickle

nautilus_trader/adapters/binance/futures/providers.py
=> #1238 attach position risk for parsing binance instrument

nautilus_trader/model/objects.pyx
=> fix Money.from_raw

nautilus_trader/adapters/betfair/data_types.py, nautilus_trader/adapters/betfair/parsing/core.py, nautilus_trader/adapters/betfair/parsing/streaming.py, nautilus_trader/adapters/betfair/sockets.py, tests/acceptance_tests/test_backtest.py, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/integration_tests/adapters/betfair/test_betfair_parsing.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_streaming.py
Fixing bugs in betfair trade volumes + betfair ticker subscription.
=> Betfair ticker fix

nautilus_trader/adapters/betfair/data.py, nautilus_trader/adapters/betfair/data_types.py, nautilus_trader/adapters/betfair/parsing/streaming.py, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/integration_tests/adapters/betfair/test_betfair_parsing.py, tests/integration_tests/adapters/betfair/test_betfair_persistence.py
Bug fix in BSP Deltas when writing to catalog.
=> Fixing serialization for BSP deltas

nautilus_core/indicators/src/ema.rs, nautilus_core/indicators/src/lib.rs, nautilus_core/indicators/src/sma.rs, nautilus_core/model/src/data/bar.rs, nautilus_core/model/src/data/quote.rs, nautilus_core/model/src/data/trade.rs
=> Simple and Exponential moving average rust

tests/integration_tests/network/conftest.py, tests/integration_tests/network/test_socket.py
=> Add python socket tests

nautilus_core/model/src/instruments/equity.rs, nautilus_core/model/src/python/instruments/equity.rs, nautilus_core/model/src/python/instruments/mod.rs, nautilus_trader/test_kit/rust/instruments.py, tests/unit_tests/model/instruments/test_equity_pyo3.py
- struct `Equity` with pymethods and pyo3 python tests
=> Add Equity in rust with pyo3

nautilus_core/model/src/instruments/futures_contract.rs, nautilus_core/model/src/python/instruments/futures_contract.rs, nautilus_core/model/src/python/instruments/mod.rs, nautilus_trader/test_kit/rust/instruments.py, tests/unit_tests/model/instruments/test_crypto_perpetual_pyo3.py, tests/unit_tests/model/instruments/test_currency_pair_pyo3.py, tests/unit_tests/model/instruments/test_futures_contract_pyo3.py
- struct `FuturesContract` with pymethods and pyo3 python tests
=> Add FuturesContract in rust with pyo3

nautilus_core/network/src/websocket.rs
- Add optional `message` field in WebSocketConfig
- Send either `Message::Ping` or `Message::Text` in `WebSocketClientInner::spawn_heartbeat_task` depending on presence of `message`
=> Add optional ping message

nautilus_core/common/src/generators/client_order_id.rs, nautilus_core/common/src/generators/mod.rs, nautilus_core/common/src/generators/order_list_id.rs, nautilus_core/common/src/generators/position_id_generator.rs
- implemented `PositionIdGenerator` with rust tests
=> Implement PositionIdGenerator in rust

nautilus_core/indicators/src/average/mod.rs, nautilus_core/indicators/src/average/rma.rs, nautilus_core/indicators/src/python/average/mod.rs, nautilus_core/indicators/src/python/average/rma.rs, nautilus_core/indicators/src/stubs.rs
- Implement WilderMovingAverage in Rust, with tests
=> Implement WilderMovingAverage Indicator in Rust

.gitignore, nautilus_core/Cargo.lock, nautilus_core/persistence/Cargo.toml, nautilus_core/persistence/src/db/database.rs, nautilus_core/persistence/src/db/mod.rs
- create generic `Database` object that creates the connection with the desired database with the help of `sqlx` (currently supported sqlite and postgres)
- it creates a local SQLite database if it doesn't exist for tests
- this local `test_db.sqlite` is not included in the git
=> Generic database struct with sqlx

nautilus_trader/adapters/interactive_brokers/client/client.py
References #1353
Retrieved daily and non-daily (hourly, etc.) bars with success.
=> Fix timestamps in Interactive Brokers daily bars

docs/getting_started/quickstart.md, docs/tutorials/backtest_high_level.md, examples/notebooks/quick_start.ipynb, nautilus_trader/backtest/node.py, nautilus_trader/data/engine.pyx, tests/unit_tests/backtest/test_node.py, tests/unit_tests/persistence/test_streaming.py
Cleanup old `as_nautilus` references, this param is no longer used.
=> Cleanup as_nautilus references

nautilus_core/common/Cargo.toml, nautilus_core/common/src/factories.rs, nautilus_core/common/src/stubs.rs
-  added `OrderFactory` in rust with tests
=> Implement order factory in rust

nautilus_core/model/src/events/order/initialized.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/initialized.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, nautilus_trader/test_kit/rust/identifiers_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished order event `OrderInitialized` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderInitialized in Rust

nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/events/order/submitted.rs, nautilus_core/model/src/identifiers/stubs.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/submitted.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderSubmitted` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderSubmitted in Rust

nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/events/order/updated.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/events/order/updated.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderUpdated` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderUpdated in Rust

nautilus_core/model/src/events/order/accepted.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/accepted.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderAccepted` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderAccepted in Rust 

nautilus_core/model/src/events/order/canceled.rs, nautilus_core/model/src/python/events/order/canceled.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderCanceled` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderCanceled in Rust

nautilus_core/model/src/events/order/expired.rs, nautilus_core/model/src/events/order/stubs.rs, nautilus_core/model/src/python/events/order/expired.rs, nautilus_core/model/src/python/events/order/mod.rs, nautilus_core/model/src/python/mod.rs, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/test_kit/rust/events_pyo3.py, tests/unit_tests/model/test_events_pyo3.py
- finished event `OrderExpired` in rust and exported in with pyo3 and tested on the python side
=> Implement event OrderExpired in Rust

examples/backtest/fx_talib_gbpusd_bars_internal.py, nautilus_trader/examples/strategies/talib_exemplar_strategy.py, nautilus_trader/indicators/ta_lib/__init__.py, nautilus_trader/indicators/ta_lib/common.py, nautilus_trader/indicators/ta_lib/manager.py
Enables straightforward integration of TA-Lib into strategies. Useful for anyone looking to utilize TA-Lib indicators.
=> Implement TA-Lib Integration

.github/workflows/build.yml, nautilus_trader/examples/strategies/talib_strategy.py, nautilus_trader/indicators/ta_lib/manager.py, tests/unit_tests/indicators/test_talib_func_wrapper.py, tests/unit_tests/indicators/test_talib_indicator_manager.py
Adding initial tests for TA-Lib.
=> Add TA-Lib tests

nautilus_trader/backtest/engine.pyx
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix reset backtest engine: add the missing emulator.reset call

nautilus_trader/indicators/ta_lib/manager.py, tests/unit_tests/indicators/test_talib_func_wrapper.py, tests/unit_tests/indicators/test_talib_indicator_manager.py
Add more tests for TALibIndicatorManager and some refinements.
=> Add more tests for TALibIndicatorManager

nautilus_trader/adapters/betfair/client.py, nautilus_trader/adapters/betfair/common.py, nautilus_trader/adapters/betfair/data.py, nautilus_trader/adapters/betfair/execution.py, nautilus_trader/adapters/betfair/parsing/requests.py, tests/integration_tests/adapters/betfair/test_betfair_client.py, tests/integration_tests/adapters/betfair/test_betfair_parsing.py
=> Cleaning up

nautilus_trader/adapters/interactive_brokers/gateway.py
Raises error only when docker is really needed and not in situation when connecting to TWS.
=> Refine docker RuntimeError

nautilus_core/Cargo.lock, nautilus_core/Cargo.toml
=> Bump ustr dependency

nautilus_trader/common/component.pyx
=> Fix unused import psutil

nautilus_trader/indicators/ta_lib/manager.py
This would support direct pickling of `TALibIndicatorManager`.
=> Support pickling of TAFunctionWrapper

nautilus_core/common/src/logging/mod.rs
Fix comparison check that allows a log line to be enabled
Run backtest
=> Fix logging enabled check

nautilus_trader/adapters/betfair/execution.py, nautilus_trader/adapters/betfair/parsing/common.py, nautilus_trader/adapters/betfair/parsing/requests.py, tests/integration_tests/adapters/betfair/test_betfair_parsing.py
FIxing betfair trade ids + account states
=> Fix betfair trade ID

nautilus_trader/adapters/interactive_brokers/client/account.py, nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/connection.py, nautilus_trader/adapters/interactive_brokers/client/contract.py, nautilus_trader/adapters/interactive_brokers/client/error.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/adapters/interactive_brokers/client/order.py, nautilus_trader/adapters/interactive_brokers/client/wrapper.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_error.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_market_data.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_order.py, tests/integration_tests/adapters/interactive_brokers/conftest.py
Refactor the EWrapper class to isolate it from Mixin classes. This simplifies troubleshooting by addressing issues related to method overrides and the unavailability of type hints.
=> Refactor InteractiveBrokersEWrapper

nautilus_trader/adapters/interactive_brokers/client/account.py, nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/contract.py, nautilus_trader/adapters/interactive_brokers/client/error.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/adapters/interactive_brokers/client/order.py, nautilus_trader/adapters/interactive_brokers/client/wrapper.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/historic/client.py, tests/integration_tests/adapters/interactive_brokers/client/test_client.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_error.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_market_data.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_order.py
Implemented minor bug fixes and enhanced the wrapper with asynchronous calls to improve handling of incoming events without blocking.
Existing tests updated to use async.
=> IB minor fixes and Enhanced Wrapper with Async Calls

nautilus_trader/model/data.pxd, nautilus_trader/model/data.pyx, tests/unit_tests/model/test_bar.py
=> Implement Bar.from_raw

.github/workflows/build.yml
Testing if Windows test passes.
=> Refine cache key to include specific Python patch version

nautilus_trader/adapters/interactive_brokers/common.py, nautilus_trader/adapters/interactive_brokers/execution.py
Fixes to accomodate `IBOrderTags` with order tags type list[str].
=> Fix List Support for IBOrderTags

.gitignore
- Iml files are configuration files from Intelij and should be removed from git
- added `*.iml` entry to `.gitignore`
=> Add *.iml files to .gitignore

nautilus_trader/adapters/interactive_brokers/parsing/instruments.py
Fixes IBContractDetails parsing bug.
=> Fix IBContractDetails parsing

nautilus_trader/live/node_builder.py
Fixes portfolio bug for InteractiveBrokers.
=> Fix Portfolio registration for IB

nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py
Fixes issue in Interactive Brokers get_historical_bars as reported on discord.
=> Fix issue in Interactive Brokers get_historical_bars

nautilus_trader/model/data.pxd, nautilus_trader/model/data.pyx
Add from_raw_arrays_to_list method for Bar.
=> Add from_raw_arrays_to_list method for Bar

nautilus_trader/adapters/betfair/execution.py
Two fixes:
1- Refresh the stream connection once a session is invalid (self._client.disconnect() has been replaced with self._disconnect() which disconnect both the client and stream)
2- Avoid multiple reconnect attempts if there are multiple INVALID_SESSION_INFORMATION errors in the current event queue
In Prod
=> Betfair: improved session renewal

examples/sandbox/bybit_sandbox.py
Add an example of a sandbox run with Bybit data.
Locally running the example.
=> Add sandbox example for Bybit

nautilus_trader/adapters/bybit/data.py
The Bybit venue pushes Level 1 depth data every 10ms, versus deltas at depth 50 every 20ms. This PR allows to subscribe both to quote ticks and delta ticks to receive quote ticks as soon as possible but still keep an up to date order book with depth 50 or 200 or 500.
Locally subscribing to quote ticks and delta ticks at level 50.
=> Subscribe to top of the book and deltas for the Bybit adapter

docs/getting_started/installation.md
Issue #1689
Update Install doc to include clang dependency. Added validation step for rustc and clang.
- [ x ] This change requires a documentation update
- N/A this is a documentation-only change
=> Document clang Installation dependency

docs/integrations/ib.md, nautilus_trader/adapters/interactive_brokers/client/contract.py, nautilus_trader/adapters/interactive_brokers/providers.py
- Refactor option chain loading in InteractiveBrokersInstrumentProvider (support loading Index Option Instrument chains)
- Add symbology section to Interactive Brokers documentation
=> Refactor Interactive Brokers and improve docs

nautilus_trader/adapters/interactive_brokers/common.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/model/instruments/__init__.py, nautilus_trader/model/instruments/index_contract.pxd, nautilus_trader/model/instruments/index_contract.pyx, nautilus_trader/serialization/arrow/implementations/instruments.py, tests/integration_tests/adapters/interactive_brokers/test_parsing.py
Add support for Index instrument.
Included some tests.
=> Add index instrument support for Interactive Brokers

Makefile, docs/conf.py, poetry.lock, pyproject.toml
- Added markdown build support.
- `make pre-commit`
=> Add markdown build support in sphinx

docs/concepts/strategies.md
=> Fix time alerts python example in docs

docs/concepts/advanced/advanced_orders.md, docs/concepts/advanced/synthetic_instruments.md, docs/concepts/orders.md, docs/integrations/index.md
=> Fix docs to use markdown link instead of html

nautilus_trader/adapters/binance/common/data.py, nautilus_trader/adapters/binance/common/execution.py, nautilus_trader/adapters/binance/config.py, nautilus_trader/adapters/binance/factories.py, nautilus_trader/adapters/binance/futures/providers.py, nautilus_trader/adapters/binance/spot/providers.py
- Support binance live trading custom Venue. This makes it easier to implement the futures arbitrage.
- Remove account_id hard-coding. New account_id is `AccountId(f"{name or BINANCE_VENUE.value}-{self._binance_account_type.value}-master")`
with existing [binance_futures_testnet_ema_cross_bracket_algo.py](https://github.com/nautechsystems/nautilus_trader/blob/develop/examples/live/binance/binance_futures_testnet_ema_cross_bracket_algo.py), simply replace "BINANCE" with "BINANCE_FUTURE_01"
```python
from decimal import Decimal
from nautilus_trader.adapters.binance.common.enums import BinanceAccountType
from nautilus_trader.adapters.binance.config import BinanceDataClientConfig
from …
```
=> Add venue option to Binance adapter

tests/integration_tests/infrastructure/test_cache_database_postgres.py
- removed all asyncio sleeps with corresponding `evantually` counterpart
- merged add and update account tests into one with the correct updating check
=> Refactor cache database tests

nautilus_trader/adapters/interactive_brokers/execution.py
Refactor order submission error handling i.e TrailingOffsetType other than PRICE doesn't get submitted.
=> Refactor order submission error handling

nautilus_trader/adapters/bybit/websocket/client.py
…tion request
The documentation of the websocket of bybit states: `You can input up to 10 args for each subscription request sent to one connection`
So, now when resubscribing to all data streams, multiple requests are used. Otherwise, the server responds with errors such as:
```
WebSocket error: BybitWsMessageGeneral(op='subscribe', topic=None, success=False, ret_msg='args size >10')
```
Subscribing to 30 data streams during live execution, and forcing a reconnection by switching off the network, and switching it on again.
=> Fix reconnect for Bybit websockets max args

nautilus_core/Cargo.lock, nautilus_core/backtest/Cargo.toml, nautilus_core/backtest/src/models/fill.rs, nautilus_core/backtest/src/models/mod.rs
- created new module `models` in `backtest` crate which will contain models implementations like `FeeModel`, `LatencyModel` , `FillModel` etc
- implemented `FillModel` with random number generation from seed or from entropy
=> Implement FillModel in Rust

nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/data.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_market_data.py
=> Add `ignore_quote_tick_size_updates` option for Interactive Brokers Data Client

nautilus_core/infrastructure/src/sql/cache_database.rs
- log the error if sending sending of data through the channel fails
- propagate the error at the functions ending
=> Improve error handling in PSQL cache database

nautilus_core/Cargo.lock, nautilus_core/infrastructure/Cargo.toml, nautilus_core/infrastructure/src/sql/models/enums.rs
- bumped `sqlx` Rust lib to `0.8.0
- refactored enums PSQL models with new interface
=> Bump sqlx to 0.8.0 and refactoring 

nautilus_core/network/src/python/http.rs
…ient
Rename timeout_sec to timeout_secs
Not mentionable.
Using dYdX adapter.
=> Rename to timeout_secs for consistency

docs/concepts/advanced/custom_data.md
Small improvement to custom data documentation
=> Small improvement to custom data documentation

docs/concepts/advanced/custom_data.md
Improve custom data documentation with a paragraph for signal data and a usage improvement to the stubs description.
=> Improve custom data documentation

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/backtest/src/models/fill.rs
- impl `set_fill_model` in `SimulatedExchange`
- added fill model as ne param in `OrderMatchingEngine`
=> Implement set_fill_model in SimulatedExchange

docs/integrations/bybit.md, docs/integrations/dydx.md
Add integration guide for dYdX and fix spelling mistakes in the Bybit integration guide.
Not tested. Documentation update.
=> Add integration guide for dYdX

nautilus_core/network/src/http.rs, nautilus_core/network/src/python/http.rs, nautilus_core/network/src/python/mod.rs
Detailed http error reporting for timeouts and other cases.
Untested right now
=> Detailed HTTP error reporting

docs/integrations/dydx.md
Add installation instructions for dYdX
Only doc update
=> Add installation instructions for dYdX

nautilus_core/network/src/http.rs, nautilus_core/network/src/python/http.rs, nautilus_core/network/src/python/mod.rs, nautilus_core/network/src/python/websocket.rs
Add Python exception class for Websocket. Refactor Http error to inherit from base exception.
Module tests were run.
=> Add WebSocketClientError Python exception class

nautilus_trader/adapters/dydx/websocket/client.py
Catch WebSocketClientError exceptions in the websocket client of dYdX
Running live example for dYdX
=> Catch WebSocketClientError exceptions in dYdX websocket client

nautilus_trader/adapters/dydx/grpc/account.py, nautilus_trader/adapters/dydx/providers.py
Add retry policy to gRPC client and fallback to zero fees if the gRPC server is not available
Using the live example.
=> Add retry policy to gRPC client with fallback

nautilus_trader/adapters/dydx/data.py
Only call the subscribe and unsubscribe methods from the websocket client for dYdX if there is (not) a subscription. This results in less warning messages if the strategy subscribes to both quotes and deltas.
Live example
=> Check websocket subscriptions for dYdX

nautilus_trader/adapters/dydx/execution.py
Fix error message in execution client of dYdX
pre-commit
=> Fix error message in execution client of dYdX

nautilus_core/execution/src/client.rs
- implemented `generate_*` functions in Rust Execution client for sending target order events
=> Implement generate order functions in Rust execution client

nautilus_trader/adapters/binance/http/client.py
Added support for additional Binance API key types #1767 
New feature (non-breaking change which adds functionality)
`pre-commit run --all-files`
=> Add support for additional Binance API key types

nautilus_trader/adapters/dydx/common/constants.py, nautilus_trader/adapters/dydx/http/errors.py
Use a error retry list for dYdX. The list of error codes can be expanded, but the documentation does not list all error codes.
Live example.
=> Use an error code retry list for dYdX

nautilus_trader/adapters/dydx/execution.py
Generate cancel rejected events for dYdX
Live example
=> Generate cancel rejected events for dYdX

.github/workflows/build.yml, .github/workflows/release.yml
=> Release 1.201.0

nautilus_trader/adapters/dydx/data.py
- Handle internal server errors for dYdX websocket connections. Resubscribe to the order book deltas if an error message "Internal error, could not fetch data for subscription: v4_orderbook" is received. This is a reference to the error as thrown by the venue:
https://github.com/dydxprotocol/v4-chain/blob/8cc37b2b49e8907e11a2636f304d84e3336b03c7/indexer/services/socks/src/lib/subscription.ts#L163 
- Log errors when the websocket messages are not received in the correct order or when a message is not received by using`message_id`. On startup, the `subscribed` messages are regularly received out of order when subscribing to multiple subscriptions unfortunately. Due to these `subscribed` messages, the `message_id` is not guaranteed to be monotonically increasing. An option could be to …
=> Handle internal server error for dYdX

examples/live/interactive_brokers/connect_with_dockerized_gateway.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/gateway.py
Refactor to use dynamic container_image from config.
=> Use dynamic IB gateway container_image from config

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/endpoints/account/address.py, nautilus_trader/adapters/dydx/endpoints/account/asset_positions.py, nautilus_trader/adapters/dydx/endpoints/account/fills.py, nautilus_trader/adapters/dydx/endpoints/account/order.py, nautilus_trader/adapters/dydx/endpoints/account/orders.py, nautilus_trader/adapters/dydx/endpoints/account/perpetual_positions.py, nautilus_trader/adapters/dydx/endpoints/account/subaccount.py, nautilus_trader/adapters/dydx/endpoints/endpoint.py, nautilus_trader/adapters/dydx/endpoints/market/candles.py, nautilus_trader/adapters/dydx/endpoints/market/instruments_info.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/http/account.py, nautilus_trader/adapters/dydx/http/client.py, nautilus_trader/adapters/dydx/http/errors.py, nautilus_trader/adapters/dydx/http/market.py, nautilus_trader/adapters/dydx/providers.py
Refactor HTTP requests to use the RetryManager for dYdX
Live example with testnet and mypy
=> Refactor HTTP requests to use RetryManager for dYdX

nautilus_trader/adapters/dydx/endpoints/account/address.py, nautilus_trader/adapters/dydx/endpoints/account/asset_positions.py, nautilus_trader/adapters/dydx/endpoints/account/fills.py, nautilus_trader/adapters/dydx/endpoints/account/order.py, nautilus_trader/adapters/dydx/endpoints/account/orders.py, nautilus_trader/adapters/dydx/endpoints/account/perpetual_positions.py, nautilus_trader/adapters/dydx/endpoints/account/subaccount.py, nautilus_trader/adapters/dydx/endpoints/endpoint.py, nautilus_trader/adapters/dydx/endpoints/market/candles.py, nautilus_trader/adapters/dydx/endpoints/market/instruments_info.py
Refine logging for RetryManager of dYdX
Live example
=> Refine logging for RetryManager of dYdX

nautilus_core/data/src/aggregation.rs
Add callback for TimeBarAggregator so that bar aggregation can be triggered by a clock
WIP
=> Add callback for TimeBarAggregator

nautilus_trader/adapters/interactive_brokers/client/market_data.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_market_data.py
Fixes bar subscription issue reported in #1933.
Resubscription works and added tests.
=> Fix Bar subscription for IB

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/execution/src/matching_core.rs
- implemented `process_trade_tick` in `SimulatedExchange`
- added test `test_exchange_process_trade_tick`
=> Implement trade tick processing for SimulatedExchange

nautilus_trader/persistence/writer.py
The pull is a supplement and improvement to issue #1945  ，In the latest StreamingFeatherWriter, when recording multiple types or sets of data, the _next_rotation_time is used by one of them, preventing rotation for other types of data. To avoid this issue, _next_rotation_time has been modified to a dictionary format.
Validated using two methodologies: live trading implementation and historical backtesting
=> Fix StreamingFeatherWriter rotation time for multiple data types

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs, nautilus_core/backtest/src/models/latency.rs, nautilus_core/execution/src/client.rs
- implemented some small remaining getter functions in `SimulatedExchange`
=> Implement remaining getter functions in SimulatedExchange

nautilus_trader/adapters/dydx/websocket/client.py
Implement rate limiting when subscribing to websocket stream for dYdX
Live example
=> Apply rate limiting when subscribing to websocket streams for dYdX

nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/grpc/account.py
Implement batch cancel for short terms orders of dYdX
Live example
=> Implement batch cancel for short terms orders of dYdX

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/websocket/client.py
Refactor reconnection handling for dYdX
Live example
=> Refactor reconnection handling for dYdX

.github/workflows/build.yml
Pin pre-commit temporarily to 3.8.0
=> Pin pre-commit to 3.8.0

nautilus_trader/adapters/dydx/websocket/client.py
Add more logs when the websocket is reconnecting for dYdX.
Live example
=> Add error logs to websocket for dYdX

nautilus_trader/adapters/dydx/websocket/client.py
Use rust ratelimiter for dYdX websockets
pre-commit / live example
=> Use Rust rate limiter for dYdX websockets

nautilus_core/backtest/src/exchange.rs, nautilus_core/backtest/src/matching_engine.rs
- implemented `process_instrument_status` in `SimulatedExchange`
- implemented `process_status` in `OrderMatchingEngine` where some status actions changes market status
- added new variant in `Data` enum `InstrumentStatus` with FFI compatible `InstrumentStatus_API`
- tested in `test_exchange_process_instrument_status` were market status was changed from open to close
=> Implement instrument status processing for SimulatedExchange

nautilus_core/backtest/src/matching_engine.rs
- added function `generate_venue_position_id` in `OrderMatchingEngine` which generates position ids based on config of engine
- tested in `test_generate_venue_position_id` with two engine one of which uses position ids and other which doesn't
=> Implement get_venue_position_id in OrderMatchingEngine

examples/backtest/databento_ema_cross_long_only_aapl_bars.py, examples/backtest/databento_ema_cross_long_only_spy_trades.py, examples/backtest/databento_ema_cross_long_only_tsla_trades.py, nautilus_trader/__init__.py, nautilus_trader/test_kit/stubs/persistence.py, tests/acceptance_tests/test_backtest.py, tests/integration_tests/adapters/betfair/test_kit.py, tests/integration_tests/adapters/databento/test_loaders.py, tests/performance_tests/test_perf_backtest.py, tests/performance_tests/test_perf_orderbook.py, tests/unit_tests/accounting/test_calculators.py, tests/unit_tests/backtest/test_data_loaders.py, tests/unit_tests/backtest/test_engine.py, tests/unit_tests/data/test_aggregation.py, tests/unit_tests/model/test_orderbook.py, tests/unit_tests/persistence/conftest.py, tests/unit_tests/persistence/test_backend.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_transformer.py, tests/unit_tests/persistence/test_wranglers.py, tests/unit_tests/persistence/test_wranglers_v2.py, tests/unit_tests/trading/test_filters.py
Move definition of TEST_DATA_DIR so it's easier to experiment or fix some tests outside of the test directory. New location at the same place as PACKAGE_ROOT.
- New feature (non-breaking change which adds functionality
Existing tests unaffected
=> Move definition of TEST_DATA_DIR

nautilus_trader/adapters/dydx/schemas/ws.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py, tests/test_data/dydx/websocket/v4_accounts_subscribed_best_effort_canceled.json
Fix account balance report for dYdX. Thanks for reporting @miller-moore
Add unit test
=> Fix account balance report for dYdX

nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/factories.py
Add timeouts to Interactive Brokers adapter configurations.
=> Add timeouts to Interactive Brokers adapter configurations

nautilus_core/analysis/src/analyzer.rs
- Add terminating periods for docstrings in `Analysis` crate.
`make cargo-test`
=> Refine docstrings

nautilus_core/persistence/tests/test_catalog.rs
- Fixed `nautilus-persistence::test_catalog catalog_query_mem_leak_test` test.
- `make cargo-test`
- `cargo nextest run --package nautilus-persistence`
=> Fix `catalog_query_mem_leak_test` test

nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/binance/futures/execution.py, nautilus_trader/adapters/binance/spot/execution.py
Catch msgspec.ValidationError for Binance websocket messages
No testing at all all, zero testing. Requires validation.
=> Handle ValidationError for Binance websocket messages

nautilus_core/common/src/timer.rs
Use JoinHandle to cancel LiveTimer event loop
Cargo tests were run
=> Simplify LiveTimer cancellation model

nautilus_core/common/src/cache/mod.rs, nautilus_core/common/src/generators/position_id.rs, nautilus_core/execution/src/engine/config.rs, nautilus_core/execution/src/engine/mod.rs, nautilus_core/execution/src/messages/mod.rs, nautilus_core/execution/src/messages/submit.rs, nautilus_core/model/src/instruments/any.rs, nautilus_core/model/src/instruments/betting.rs, nautilus_core/model/src/instruments/binary_option.rs, nautilus_core/model/src/orders/any.rs
Porting the Cython execution engine to Rust
Work in progress. Not executable right now.
=> Port ExecutionEngine to Rust

nautilus_trader/adapters/dydx/factories.py
Cache the dYdX http client with a lru cache
Live example and pre-commit
=> Cache dYdX HTTP client with lru cache

nautilus_trader/adapters/dydx/execution.py
Handle liquidated fills for dYdX
Live example
=> Handle liquidated fills for dYdX

nautilus_trader/adapters/bybit/schemas/account/fee_rate.py, nautilus_trader/adapters/bybit/schemas/asset/coin_info.py, nautilus_trader/adapters/okx/schemas/account/balance.py, nautilus_trader/adapters/okx/schemas/account/positions.py, nautilus_trader/adapters/okx/schemas/account/trade_fee.py
Remove Bybit `msgspec` redundant import alias.
=> Remove Bybit `msgspec` redundant import alias

nautilus_trader/adapters/dydx/execution.py
=> Fix error message for fill events of dYdX

docs/tutorials/index.md
=> Fix Jupyter URL typo

nautilus_trader/adapters/dydx/execution.py
Reject long term market orders for dYdX
Live examle
=> Reject long term market orders for dYdX

nautilus_core/common/src/clock.rs
Cleanup expired timers efficiently.
* For TestClock, expired timers are cleared up in a single pass when the clock iterates over timers to advance them
* For LiveClock, expired timers are cleared up when a new timer is inserted. It is assumed that new timers will be created much less than the events they will produce make the cost
Common module tests were run
=> Efficiently clean up expired timers in clocks

nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/schemas/common.py, nautilus_trader/adapters/bybit/schemas/ws.py, nautilus_trader/adapters/bybit/websocket/client.py, tests/integration_tests/adapters/bybit/resources/ws_messages/private/ws_wallet.json, tests/integration_tests/adapters/bybit/test_ws_decoders.py
Add wallet subscription for Bybit.
=> Add wallet subscription for Bybit

docs/integrations/ib.md, examples/live/interactive_brokers/connect_with_tws.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/adapters/interactive_brokers/providers.py, tests/integration_tests/adapters/interactive_brokers/test_parsing.py
Support for Databento Symbology as discussed in #1790.
Added unit tests and live API testing.
=> Support for Databento symbology

nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/websocket/client.py
Reconcile the order book for dYdX if it is inconsistent.
Fixes #2075 
Live example
=> Reconcile order book for dYdX when inconsistent

nautilus_trader/data/client.pyx
=> Add docs clarity on loading historical bars

docs/integrations/dydx.md, nautilus_trader/adapters/dydx/common/common.py, nautilus_trader/adapters/dydx/execution.py, tests/integration_tests/adapters/dydx/test_common.py
Fix specifying the price for market orders on dYdX
Live example and unit tests
=> Fix specifying the price for market orders on dYdX

nautilus_trader/adapters/_template/data.py, nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/okx/data.py, nautilus_trader/backtest/data_client.pyx, nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/data/client.pxd, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/live/data_client.py
Add params for remaining previously non covered methods: subscribe, unsubscribe and request
Existing tests
=> Add specific params for remaining data subscriptions and requests

nautilus_trader/adapters/bybit/execution.py
Fix incorrect parameter in `BybitExecutionClient`.
=> Fix incorrect parameter in BybitExecutionClient

nautilus_trader/adapters/bybit/config.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/websocket/client.py
Add `max_reconnection_tries` to data client config for Bybit
=> Add `max_reconnection_tries` to data client config for Bybit

nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/schemas/common.py, nautilus_trader/adapters/bybit/schemas/ws.py, nautilus_trader/adapters/bybit/websocket/client.py
Tried in #2097, but it could still trigger a `Request not authorized` error in some cases.
Further modifications have been made to enhance robustness.
=> Refine WebSocket private channel authentication for Bybit

nautilus_trader/adapters/bybit/common/enums.py, nautilus_trader/adapters/bybit/endpoints/account/info.py, nautilus_trader/adapters/bybit/endpoints/account/set_leverage.py, nautilus_trader/adapters/bybit/endpoints/account/set_margin_mode.py, nautilus_trader/adapters/bybit/endpoints/account/switch_mode.py, nautilus_trader/adapters/bybit/endpoints/endpoint.py, nautilus_trader/adapters/bybit/endpoints/user/__init__.py, nautilus_trader/adapters/bybit/endpoints/user/query_api.py, nautilus_trader/adapters/bybit/endpoints/user/update_sub_api.py, nautilus_trader/adapters/bybit/http/account.py, nautilus_trader/adapters/bybit/http/user.py, nautilus_trader/adapters/bybit/schemas/account/info.py, nautilus_trader/adapters/bybit/schemas/account/set_leverage.py, nautilus_trader/adapters/bybit/schemas/account/set_margin_mode.py, nautilus_trader/adapters/bybit/schemas/account/switch_mode.py, nautilus_trader/adapters/bybit/schemas/user/__init__.py, nautilus_trader/adapters/bybit/schemas/user/query_api.py, nautilus_trader/adapters/bybit/schemas/user/update_sub_api.py
=> Add additional API functionality for Bybit

nautilus_trader/adapters/bybit/websocket/client.py
Add `position` and `execution.fast` subscriptions for Bybit.
Next, I will optimize the redundant code related to subscriptions.
=> Add `position` and `execution.fast` subscriptions for Bybit

nautilus_trader/adapters/bybit/websocket/client.py
Refine subscribe and unsubscribe for Bybit.
=> Refine subscribe and unsubscribe for Bybit

nautilus_trader/adapters/bybit/common/urls.py, tests/integration_tests/adapters/bybit/test_factories.py
Change default http_base_url for Bybit.
=> Change default http_base_url for Bybit

nautilus_trader/adapters/bybit/execution.py
Refine `_batch_cancel_orders` for Bybit.
=> Refine `_batch_cancel_orders` for Bybit

nautilus_trader/adapters/bybit/endpoints/trade/batch_place_order.py, nautilus_trader/adapters/bybit/endpoints/trade/place_order.py
Refine struct define for Bybit.
=> Refine struct define for Bybit

RELEASES.md
=> Update release notes

examples/live/databento/databento_historical_data.py, nautilus_core/adapters/databento/src/python/historical.rs, nautilus_core/adapters/databento/src/symbology.rs, nautilus_trader/adapters/databento/data.py, nautilus_trader/common/actor.pyx, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/data/engine.pyx
Fix databento venue conversion for GLBX
Also add use_exchange_as_server as params for request_instruments
Also add possibility to use start argument for live market data in the recent past with databento
Tested on test notebook modified in this PR, working for historical data, live data should benefit from this bug fix as well
=> Fix databento venue conversion for GLBX

nautilus_core/adapters/databento/src/live.rs, nautilus_core/adapters/databento/src/python/live.rs, nautilus_trader/adapters/databento/data.py, nautilus_trader/data/engine.pyx
Fix live databento venue conversion for GLBX
=> Fix live databento venue conversion for GLBX

nautilus_trader/data/engine.pyx
Refactor start of data definition in data engine
=> Refactor start of data definition in DataEngine

docs/concepts/instruments.md
This is only documentation update.
Added two new sections to `instruments.md`:
- **Margins and fees**: 
- Explain margin calculations, leverage, and fee structures
- **Commissions**: 
- Document built-in fee models and custom implementation examples
=> Docs: Added new infos about margins and commissions

nautilus_trader/adapters/bybit/websocket/client.py
Fix timeout error code for Bybit.
=> Fix timeout error code for Bybit

nautilus_trader/adapters/bybit/endpoints/market/instruments_info.py, nautilus_trader/adapters/bybit/http/market.py, nautilus_trader/adapters/bybit/providers.py, nautilus_trader/adapters/bybit/schemas/common.py, nautilus_trader/adapters/bybit/schemas/instrument.py
Fix incomplete instruments info retrieval caused by pagination failure in Bybit.
And refine instrument parse.
=> Fix instruments info retrieval for Bybit

poetry.lock, pyproject.toml
Upgrade v4-proto for dYdX
Live example
=> Upgrade v4-proto for dYdX

tests/unit_tests/data/test_engine.py
Add tests for request_aggregated_bars
=> Add tests for request_aggregated_bars

nautilus_core/Cargo.lock, nautilus_core/common/Cargo.toml, nautilus_core/common/src/cache/mod.rs, nautilus_core/common/src/msgbus/switchboard.rs, nautilus_core/execution/src/client.rs, nautilus_core/execution/src/engine/mod.rs, nautilus_core/model/src/events/order/any.rs, nautilus_core/model/src/events/position/changed.rs, nautilus_core/model/src/events/position/closed.rs, nautilus_core/model/src/events/position/opened.rs, nautilus_core/model/src/identifiers/position_id.rs, nautilus_core/model/src/orders/any.rs, nautilus_core/portfolio/src/portfolio.rs
- Continue porting the `ExecutionEngine` to Rust.
- not tested
=> Continue ExecutionEngine in Rust

nautilus_trader/adapters/dydx/schemas/ws.py
Rename bid_id and ask_id to idx for consistency in dYdX
Live example
=> Rename bid_id and ask_id to idx for consistency in dYdX

nautilus_trader/adapters/dydx/common/types.py
Fix writing a DYDXOraclePrice to the catalog
Using a data recorder
=> Fix writing a DYDXOraclePrice to the catalog

docs/concepts/backtesting.md, docs/concepts/cache.md, docs/concepts/index.md
2 things added:
1. Documentation about Cache added (95%)
2. Documentation: New info on slippage and spread handling in backtesting (5%)
=> Add cache and backtesting docs

nautilus_core/Cargo.lock, nautilus_core/execution/Cargo.toml, nautilus_core/execution/src/manager.rs, nautilus_core/model/src/orders/any.rs
- Port `OrderManager` to Rust
- not yet
=> Port OrderManager to Rust

tests/integration_tests/adapters/dydx/test_types.py
Add unit tests for custom dYdX types
=> Add unit tests for custom dYdX types

nautilus_trader/adapters/bybit/schemas/common.py, nautilus_trader/adapters/bybit/schemas/instrument.py, tests/integration_tests/adapters/bybit/resources/http_responses/linear/instrument_btc_usdt.json, tests/integration_tests/adapters/bybit/resources/http_responses/linear/instruments.json
Enhance the `lotSizeFilter` field for Bybit.
=> Enhance the `lotSizeFilter` field for Bybit

nautilus_trader/adapters/dydx/execution.py
Use a timeout when initializing the account for dYdX
Live example
=> Use a timeout when initializing the account for dYdX

nautilus_trader/adapters/bybit/execution.py
Refine private WebSocket messages processing for Bybit.
=> Refine private WebSocket messages processing for Bybit

nautilus_trader/adapters/bybit/websocket/client.py
Fix reconnect for public channel in Bybit.
=> Fix reconnect for public channel in Bybit

nautilus_core/execution/src/lib.rs, nautilus_core/execution/src/trailing.rs
Implement trailing stop logic in Rust
Added lots of tests
=> Implement trailing stop logic in Rust

nautilus_trader/adapters/bybit/execution.py
Rename WebSocket private client for Bybit.
=> Rename WebSocket private client for Bybit

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/performance.yml, .github/workflows/release.yml
Refine cache key for sccache in CI.
=> Refine cache key for sccache in CI

nautilus_trader/adapters/dydx/websocket/client.py
Refine error logs when sending pong for dYdX
Live example
=> Refine error logs when sending pong for dYdX

nautilus_trader/adapters/bybit/websocket/client.py
Refine WebSocket reconnect for Bybit.
=> Refine WebSocket client re-subscribe log in Bybit

nautilus_trader/adapters/dydx/schemas/ws.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py, tests/test_data/dydx/websocket/v4_markets_cross.json
Fix markets schema for dYdX
Unit tests
=> Fix markets schema for dYdX

nautilus_core/backtest/src/matching_engine/ids_generator.rs, nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs, nautilus_core/model/src/data/order.rs, nautilus_core/model/src/orders/any.rs
- implements market order fill flow in `OrderMatchingEngine`
=> Port market order filling for OrderMatchingEngine in Rust

nautilus_trader/data/engine.pyx
Fix issue mentioned here https://github.com/nautechsystems/nautilus_trader/issues/2192
Tested on databento_option_greeks.py with streaming of data activated
=> Fix CustomData import in DataEngine

nautilus_trader/adapters/databento/data_utils.py
Fix databento helper function when querying 'definition' only
Tested by using it
=> Fix databento helper function

nautilus_core/Cargo.lock, nautilus_core/execution/src/emulator.rs, nautilus_core/model/src/accounts/any.rs, nautilus_core/risk/Cargo.toml, nautilus_core/risk/src/engine/mod.rs
- Completed portfolio related TODO's in Risk Engine.
- Completed relevant unit tests.
- `make cargo-test`
=> Continue Risk Engine in Rust

docs/concepts/data.md
Docs updated: ts_event + ts_init explained.
I kept all the existing information and extended / updated it with additional info / explanations / examples.
=> Improve docs for ts_event + ts_init

nautilus_core/execution/src/emulator.rs, nautilus_core/network/src/http.rs, nautilus_core/network/src/socket.rs, nautilus_core/network/src/websocket.rs
- completed todo's i left in previous PR.
no tests
=> Refine OrderEmulator

build.py
Fix for `CARGO_TARGET_DIR` environment variable.
https://doc.rust-lang.org/cargo/reference/environment-variables.html
=> Fix for `CARGO_TARGET_DIR` environment variable

docs/concepts/advanced/actors.md, docs/concepts/backtesting.md, docs/tutorials/databento_overview.ipynb
Added new tutorial: Databento overview.
for @cjdsellers 
1. **UPDATE SIDEBAR**
* Based on discussion on [Discord](https://discord.com/channels/924497682343550976/1192961049293508673/1331763124860096512) , please add link for this new jupyter notebook to the sidebar navigation here please:
* ![CleanShot 2025-01-23 at 12 35 10@2x](https://github.com/user-attachments/assets/4af3bccf-5d35-4bf5-981f-68e45afee90c)
* This needs to be done in separate repo - `nextjs/docusaurus app`
2. **REFERENCE OTHER JUPYTER NOTEBOOKS**
* When making the changes, please consider whether we need to extend the list - as right now, there are only 3 links (as seen at the image), but there are 7 jupyter notebook tutorials (including this new one) in codebase, that could/should be accessible via the links. Otherwise …
=> Add docs for Databento overview + Actors + Portfolio

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- implement `process_cancel_all` function in `OrderMatchingEngine` 
- designed test scenario where only target instrument orders are correctly canceled and correct events are generated
=> Port process cancel all for OrderMatchingEngine in Rust 

nautilus_trader/adapters/dydx/schemas/ws.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py, tests/test_data/dydx/websocket/v4_markets_channel_data_v8.json
Fix websocket schema for market updates of dYdX
Unit test
=> Fix websocket schema for market updates of dYdX

nautilus_core/backtest/src/matching_engine/mod.rs, nautilus_core/backtest/src/matching_engine/tests.rs
- Implemented the `process_modify` function in the `OrderMatchingEngine` and the `update_order` function.
- Verified that a "modify rejected" event is correctly generated when the order does not exist.
- Bootstrapped several `update_`  functions to support pattern matching in the main `update_order function`, laying the groundwork for their porting in the next PRs.
=> Port process modify for OrderMatchingEngine in Rust

README.md
- updated broken image links.
👀
=> Fix readme image links

nautilus_trader/adapters/dydx/execution.py
Increase log level for ignored order messages of dYdX
=> Increase log level for ignored order messages of dYdX

nautilus_trader/cache/cache.pyx
Fix bug in cache.bar_types
- Bug fix (non-breaking change which fixes an issue
Found and tested while developing another feature
=> Fix bug in cache.bar_types

.pre-commit-config.yaml
=> Release 1.211.0

nautilus_core/Cargo.lock, nautilus_core/Cargo.toml, nautilus_core/backtest/src/exchange.rs, nautilus_core/common/Cargo.toml, nautilus_core/common/src/cache/database.rs, nautilus_core/common/src/cache/mod.rs, nautilus_core/common/src/cache/tests.rs, nautilus_core/common/src/msgbus/database.rs, nautilus_core/execution/Cargo.toml, nautilus_core/execution/src/engine/mod.rs, nautilus_core/infrastructure/Cargo.toml, nautilus_core/infrastructure/src/python/redis/cache.rs, nautilus_core/infrastructure/src/redis/cache.rs, nautilus_core/infrastructure/src/redis/mod.rs, nautilus_core/infrastructure/src/redis/msgbus.rs, nautilus_core/infrastructure/src/redis/queries.rs, nautilus_core/infrastructure/src/sql/cache.rs, nautilus_core/infrastructure/tests/test_cache_database_postgres.rs, nautilus_core/infrastructure/tests/test_cache_postgres.rs, nautilus_core/network/src/backoff.rs, nautilus_core/network/src/mode.rs, nautilus_core/network/src/python/websocket.rs, nautilus_core/network/src/socket.rs, nautilus_core/network/src/tls.rs, nautilus_core/network/src/websocket.rs
- Add Async Support for `load-*` functions.
- Better Error handling
- Better Connection handling with better database configuration.
=> Improve Redis error handling and connection management

.gitignore, nautilus_trader/adapters/_template/data.py, nautilus_trader/adapters/betfair/data.py, nautilus_trader/adapters/binance/data.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/historical/client.py, nautilus_trader/adapters/interactive_brokers/providers.py, nautilus_trader/adapters/okx/data.py, nautilus_trader/adapters/polymarket/data.py, nautilus_trader/adapters/tardis/data.py, nautilus_trader/backtest/data_client.pyx, nautilus_trader/common/actor.pyx, nautilus_trader/data/client.pxd, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/data/messages.pxd, nautilus_trader/data/messages.pyx, nautilus_trader/live/data_client.py, nautilus_trader/test_kit/mocks/data.py, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/unit_tests/backtest/test_commission_model.py, tests/unit_tests/data/test_client.py, tests/unit_tests/data/test_engine.py, tests/unit_tests/data/test_messages.py, tests/unit_tests/live/test_data_engine.py
Refactor data subscribe interfaces into messages
PR following the one about data request interfaces
- Refactoring
Adapted existing tests
=> Refactor data subscribe interfaces into messages

nautilus_trader/cache/base.pxd, nautilus_trader/cache/base.pyx, nautilus_trader/cache/cache.pxd, nautilus_trader/cache/cache.pyx, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/model/greeks.pyx, nautilus_trader/model/greeks_data.py, nautilus_trader/persistence/loaders.py
Refine yield curve data
Tested that databento_option_greeks.py still works
=> Refine yield curve data

docs/getting_started/index.md
While refactoring something else, I happened to come across this **new folder** with useful examples.
Just docs updated.
✅  pre-commit passed
=> Improve getting started doc example dir locations

crates/execution/src/matching_core/mod.rs, crates/network/src/ratelimiter/mod.rs, nautilus_trader/cache/cache.pxd, nautilus_trader/cache/cache.pyx, nautilus_trader/cache/database.pyx, nautilus_trader/cache/facade.pxd, nautilus_trader/cache/facade.pyx
- Add load_all Method to CacheDatabaseAdapter in Cython
- Add cache_all Method.
`make pytest`
=> Add load_all Method to CacheDatabaseAdapter in Cython

crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs
- implemented function `update_stop_market_order` in `OrderMatchingEngine`
- tested correct flow of updating stop market order
=> Port update stop market order for matching engine in Rust

nautilus_trader/common/factories.pyx, nautilus_trader/execution/algorithm.pyx, nautilus_trader/model/events/order.pyx, nautilus_trader/model/orders/limit.pyx, nautilus_trader/model/orders/limit_if_touched.pyx, nautilus_trader/model/orders/market_if_touched.pyx
API docs improved - added more detail.
✅  discussed and confirmed on Discord with @cjdsellers 
✅  pre-commit passed
=> Improve emulation_trigger parameter description

nautilus_trader/model/greeks.pyx
Refine option greeks docstrings
Docstrings change
=> Refine option greeks docstrings

docs/getting_started/index.md
Small addition to the Getting Started docs.
Docs extended.
✅ Checked rendered markdown
✅ pre-commit passed
=> Improve getting started doc for backtesting API levels

docs/developer_guide/testing.md
Add documentation for debugging with rust
=> Add documentation for debugging with Rust

nautilus_trader/system/kernel.py, nautilus_trader/test_kit/mocks/controller.py, nautilus_trader/trading/controller.py, nautilus_trader/trading/controller_commands.py, tests/unit_tests/backtest/test_engine.py
Refactor controller so:
- its create functions take importable configs as argument
- its other functions take ids as argument
- add execute message function in controller
- [New feature (non-breaking change which adds functionality)
Modified existing test_controller so it tests the feature
=> Improve Controller functionality

nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/interactive_brokers/data.py
Fix typo in _request_instrument signature
The typos were only in type annotations, it shouldn't have any impact
=> Fix typo in _request_instrument signature

.config/nextest.toml, Makefile, examples/backtest/databento_test_request_bars.py
Refine nextest cargo-profile config
- Bug fix (non-breaking change which fixes an issue
Allows to use nextest profile correctly with make cargo-test
=> Refine nextest cargo-profile config

examples/backtest/example_003_bar_aggregation/README.md, examples/backtest/example_003_bar_aggregation/run_example.py, examples/backtest/example_003_bar_aggregation/strategy.py
New example: Bar aggregation explained
✅  Strategy ran and checked for valid / expected outputs
✅ Precommit passed
=> Add bar aggregation example

crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs, crates/model/src/orders/base.rs, crates/model/src/orders/builder.rs, crates/model/src/orders/stubs.rs, crates/portfolio/src/tests.rs
- various fixes and improvements in order matching engine and order lifecycle
- changes are separated into distinct commits with good descriptions for better visibility and readability
=> Improve consistency of OrderMatchingEngine and fix issues

examples/other/minimal_reproducible_example/README.md, examples/other/minimal_reproducible_example/run_example.py, examples/other/minimal_reproducible_example/strategy.py
MRE = Minimalistic reproducible strategy for reporting issues.
✅ Strategy runs correctly and produces expected outputs in terminal
=> Add MRE strategy example with generated bars

examples/backtest/example_004_using_data_catalog/README.md, examples/backtest/example_004_using_data_catalog/run_example.py, examples/backtest/example_004_using_data_catalog/strategy.py
New example for beginners:  How to work with data catalog.
✅  Example works and produces expected results in terminal
✅ pre-commit passed locally
=> Add data catalog example

docs/concepts/adapters.md
Doc change to reflect refactoring of data interfaces
=> Update adapters concept documentation

crates/core/src/datetime.rs, crates/core/src/nanos.rs, crates/data/src/aggregation.rs
=> Refine Rust date functions

docs/concepts/adapters.md, nautilus_trader/data/engine.pyx
Refine adapters documentations
=> Refine adapters concept documentation

nautilus_trader/adapters/interactive_brokers/parsing/execution.py
Fix time parsing for ib adapter
In response to issue https://github.com/nautechsystems/nautilus_trader/issues/2359
Not tested, user will need to test it works. Likely fixes issue based on the time format provider by user.
=> Fix time parsing for IB adapter

examples/backtest/example_05_using_portfolio/README.md, examples/backtest/example_05_using_portfolio/run_example.py, examples/backtest/example_05_using_portfolio/strategy.py
A simple strategy demonstrating how to use Portfolio in NautilusTrader.
✅  Strategy works as expected
✅  pre-commit issues solved / passed
=> Add backtest portfolio example

crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs
- implements processing of trailing stop limit and trailing stop market order for `OrderMatchingEngine`
- the function `process_trailing_stop_order` can be used in both market and limit variants because its identical logical flow
- flow tested in `test_process_trailing_stop_orders_rejeceted_and_valid` when order trailing stop orders is rejected and other is accepted
=> Port processing of trailing stop orders for matching engine

crates/execution/src/matching_engine/engine.rs, crates/execution/src/matching_engine/tests.rs
- Implemented function `update_trailing_stop_order` in `OrderMatchingEngine` which handles both the updating of trailing stop limit and market orders
1. Add ask book order of 1 at `1500.00` so we have ask initialized
2. Create trailing stop market order with trigger price of `1505.00` which will be accepted because it's not triggered
3. Move the market down to `1480.00` with trade tick so that trailing order trigger price will be recalculated to `1481.00`
because of trailing offset of 1 unit
- Emitted order events are `OrderAccepted` and later `OrderUpdated` which is expected, but we see that current trigger price of order `1481.00` is bellow ask, which should be triggered by this tick event. This is caused by matching core not being iterated later when prices are updated
- Even if we …
=> Port updating of trailing stop orders for matching engine

nautilus_trader/persistence/catalog/parquet.py
Fix catalog path error on windows
=> Fix catalog path error on windows

build.py
Support for the `CARGO_BUILD_TARGET` environment variable.
=> Add support for `CARGO_BUILD_TARGET` environment variable

docs/concepts/data.md
New documentation about bar aggregation.
🥇 
Credit primarily belongs to @faysou , as he's the one who explained it to me so it finally made sense.
I couldn't figure out how the bar-aggregation functionality really works
without his valuable knowledge and time invested to help me & the community 🙏 
- New information and explanations added
- No existing information was removed
- Some existing information had to be relocated to maintain logical flow and prevent duplication
✅ pre-commit checks passed
✅ documentation was read by me to ensure new content has good logical flow
=> Improve and expand bar aggregation docs

examples/live/interactive_brokers/contract_download.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py
Refine parsing of IB symbols
Required for NIFTY futures
Tested locally on an example, also added
=> Refine parsing of IB symbols

nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/polymarket/execution.py, nautilus_trader/backtest/data_client.pyx, nautilus_trader/data/engine.pyx, nautilus_trader/data/messages.pyx, nautilus_trader/live/execution_client.py, tests/integration_tests/adapters/betfair/test_betfair_data.py, tests/unit_tests/data/test_client.py, tests/unit_tests/execution/test_engine.py
Fix subscribe composite bars
Also added named parameters to all recent new messages for more robustness in case the order of parameters change in the future.
Existing tests should still pass
=> Fix subscribe composite bars

examples/backtest/example_01_load_bars_from_custom_csv/run_example.py, examples/backtest/example_02_use_clock_timer/run_example.py, examples/backtest/example_03_bar_aggregation/run_example.py, examples/backtest/example_04_using_data_catalog/run_example.py, examples/backtest/example_05_using_portfolio/run_example.py, examples/backtest/example_06_using_cache/run_example.py
Existing examples refactored to use less repetitive code.
Just refactoring of existing examples.
✅ Each example was run and works (produces expected output)
✅  pre-commit  passed
=> Refactor repetitive code in examples

examples/backtest/example_07_using_indicators/README.md, examples/backtest/example_07_using_indicators/run_example.py, examples/backtest/example_07_using_indicators/strategy.py
New tutorial style example - How to use indicators
New example added.
✅  Strategy works as expected (produces correct output in Terminal)
✅  pre-commit passed
=> Add indicators example

examples/backtest/example_11_messaging_with_actor_signals/README.md, examples/backtest/example_11_messaging_with_actor_signals/run_example.py, examples/backtest/example_11_messaging_with_actor_signals/strategy.py
New example: Messaging with Actor & Signal
New example added
✅  Strategy works - there is expected output in Terminal
✅  precommit issues fixed
=> Add example messaging with actor & signal

nautilus_trader/common/actor.pyx, nautilus_trader/data/engine.pyx
Refine update catalog docstrings
Remove end and update catalog must not be set together actor condition
Fixed default catalog in update catalog
=> Refine update catalog docstrings

nautilus_trader/adapters/dydx/factories.py
Fix docstrings for dYdX factories
Not at all
=> Fix docstrings for dYdX factories

docs/concepts/actors.md
Fixed a typo in docs/concepts/actors.md
N/A.
=> Fix typo in docs/concepts/actors.md

docs/concepts/instruments.md
Fix singular noun in docs/concepts/instruments.md
N/A
=> Fix singular noun in docs/concepts/instruments.md

docs/concepts/data.md
Fix typo in docs/concepts/data.md.
N/A
=> Fix typo in docs/concepts/data.md

.github/actions/common-wheel-build/action.yml, Cargo.lock, Cargo.toml, RELEASES.md, crates/cli/Cargo.toml, crates/data/src/aggregation.rs, nautilus_trader/adapters/binance/execution.py, nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/okx/execution.py, nautilus_trader/adapters/polymarket/execution.py, nautilus_trader/data/aggregation.pyx, nautilus_trader/execution/messages.pxd, nautilus_trader/execution/messages.pyx, nautilus_trader/live/execution_engine.py
=> Release 1.212.0

nautilus_trader/backtest/data_client.pyx
Remove printing of toto
Not tested
=> Remove printing of toto

nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/dydx/execution.py
Some minor performance optimizations.
=> Some minor performance optimizations

docs/concepts/message_bus.md
Clarification based on @faysou feedback. Thank you 🙏 
Small docs update / clarification.
No special testing here , just 1 sentence changed in docs.
✅  Formatting OK, precommit passed
=> Clarify docs for timestamp properties in Data

nautilus_trader/adapters/bybit/execution.py
Improve `_submit_order_list` performance for Bybit.
=> Improve `_submit_order_list` performance for Bybit

docs/developer_guide/environment_setup.md
Update environment setup document
=> Update environment setup document

crates/adapters/databento/src/live.rs, crates/adapters/databento/src/symbology.rs, crates/common/src/xrate.rs, crates/core/src/parsing.rs, crates/cryptography/src/signing.rs, crates/infrastructure/src/redis/msgbus.rs, crates/model/src/instruments/synthetic.rs, crates/network/src/tls.rs
Standardize use of anyhow::bail
=> Standardize use of anyhow

nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/schemas/ws.py
Refine quote ticks and klines for Bybit by using the instrument definition when building quotes and klines.
When a quote is incomplete, a cached quote is used and the price and size precisions are explicitly set.
Live example
=> Refine quote ticks and klines for Bybit

nautilus_trader/adapters/bybit/execution.py, nautilus_trader/adapters/bybit/websocket/client.py
Add `recv_window_ms` config for Bybit WebSocket order client.
=> Add `recv_window_ms` config for Bybit WebSocket order client

.github/actions/common-setup/action.yml
Fix sccache key for uv
GitHub Actions is automatically triggered.
=> Fix sccache key for uv

crates/adapters/databento/src/symbology.rs, nautilus_trader/adapters/databento/config.py, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/databento/factories.py, nautilus_trader/adapters/databento/loaders.py
+Refactor of venue_dataset_map so it's stored in loader and accessible by instrument provider.
+Changed data type of venue_dataset_map dict to be str, str
Not tested, should be tested by user
=> Refine databento venue dataset mapping

crates/adapters/databento/src/live.rs, crates/adapters/databento/src/python/historical.rs, crates/adapters/databento/src/python/live.rs, nautilus_trader/adapters/databento/data.py, nautilus_trader/adapters/databento/factories.py, nautilus_trader/adapters/databento/providers.py, nautilus_trader/core/nautilus_pyo3.pyi
Refine usage of databento use_exchange_as_venue
Added usage in some live contexts
Not tested, but passes linters and rust compilation
=> Refine usage of databento use_exchange_as_venue

nautilus_trader/backtest/engine.pyx
Ensure that the clock of each component like strategies is set before on_start is called
Existing tests running
=> Refine time initialization of components in backtest

crates/common/examples/greeks_actor_example.rs, crates/common/src/cache/database.rs, crates/common/src/cache/mod.rs, crates/common/src/greeks.md, crates/common/src/greeks.rs, crates/common/src/lib.rs, crates/core/src/lib.rs, crates/core/src/math.rs, crates/infrastructure/src/redis/cache.rs, crates/infrastructure/src/redis/queries.rs, crates/infrastructure/src/sql/cache.rs, crates/model/src/data/greeks.rs, crates/model/src/data/mod.rs, nautilus_trader/model/greeks.pyx
Migrate GreeksCalculator to rust
=> Port GreeksCalculator to Rust

nautilus_trader/adapters/bybit/schemas/market/kline.py, nautilus_trader/adapters/dydx/schemas/ws.py, nautilus_trader/adapters/dydx/websocket/client.py, tests/integration_tests/adapters/dydx/test_websocket_schema.py
- Fix ts_event for Bybit bars
- Breaking change: fix ts_event for dYdX bar
- Refine warning message for internal errors from the dYdX venue
Live example
=> Fix ts_event for Bybit bars

crates/common/src/clock.rs, crates/common/src/logging/logger.rs, crates/common/src/msgbus/mod.rs, crates/common/src/python/timer.rs
Fix clippy lints
pre-commit passing
=> Fix clippy lints

Makefile, build.py
=> Fix debug flags in pre-commit

docs/concepts/data.md, docs/tutorials/databento_data_catalog.ipynb, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py
Revert removing basename_template and force a refresh of the fsspec cache when listing file
Unit tests
=> Revert removing basename_template

nautilus_trader/adapters/dydx/endpoints/endpoint.py, nautilus_trader/adapters/dydx/execution.py, nautilus_trader/adapters/dydx/factories.py, nautilus_trader/adapters/dydx/providers.py, tests/integration_tests/adapters/dydx/test_http_endpoints.py
Filter fill events if the order is already filled for dYdX
Live example
=> Filter fill events if the order is already filled for dYdX

crates/common/src/logging/writer.rs
Rotate log file when date changes
Reusing previous implementation that worked.
=> Revert removal of rotate log file on date change

nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/data/messages.pyx
Adding order book depth subscription to Actor.
=> Add order book depth subscription

nautilus_trader/adapters/dydx/schemas/ws.py
Fix account balance calculation for dYdX
Unit test and live example
=> Fix account balance calculation for dYdX

crates/adapters/databento/src/decode.rs, crates/adapters/databento/src/live.rs, crates/adapters/databento/src/loader.rs, crates/adapters/databento/src/python/historical.rs
Fix ts_init for databento historical data
ts_init was initialized as the now timestamp as of download, which was inconsistent with the rest of the system.
Tested it works on prototype in another PR
=> Fix ts_init for databento historical data

crates/common/src/logging/writer.rs, nautilus_trader/backtest/engine.pyx
Improve rust logging flush
Further small improvements to work done last week on logger file improvement, further ensuring a log file is always flushed when receiving the event to do so.
Tested it works on prototype
=> Improve logging flush

nautilus_trader/system/kernel.py
Improve clear_log_file to happen for each kernel initialization
- 
Tested on prototype
=> Improve clear_log_file to happen for each kernel initialization

nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, tests/unit_tests/backtest/test_data_iterator.py
Refine BacktestDataIterator
Updated tests
=> Refine BacktestDataIterator

crates/adapters/coinbase_intx/src/http/client.rs, crates/network/src/http.rs, crates/network/src/lib.rs, crates/network/src/python/mod.rs, crates/network/src/ratelimiter/quota.rs, crates/network/src/websocket.rs
Separate rate limiter quota python logic under python feature flag
cargo networks tests pass without python feature flag
=> Untangle ratelimiter quota from python flag

nautilus_trader/adapters/bybit/common/enums.py, nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/bybit/execution.py
Fix HTTP batch order operations for Bybit
=> Fix HTTP batch order operations for Bybit

crates/indicators/src/average/dema.rs
> Restores feature-parity and behavioural equivalence between the Rust `DoubleExponentialMovingAverage` (DEMA) implementation and the canonical Python/Cython reference. 
---
* **Correctness ⇄ Consistency**  
Trading logic often relies on a mixed Python + Rust stack (back-testing in Python, execution in Rust/WASM). Divergent indicator outputs introduce invisible drift and hard-to-debug PnL discrepancies.  
* **Predictable resets & counts**  
Several subtle edge-cases (e.g., stale `ema2` state after `reset()`) produced mis-aligned window counts and corrupted warm-up behaviour.  
* **Foundation for future SIMD optimisations**  
A clean, one-for-one port ensures micro-benchmarks are apples-to-apples before we introduce vectorised hot-paths.
---
| Concern | Python/Cython (🏆 source of truth) | …
=> Improve DEMA indicator parity with Cython

nautilus_trader/adapters/bybit/data.py, nautilus_trader/adapters/dydx/data.py, nautilus_trader/adapters/dydx/websocket/client.py
Implement _subscribe_instrument for dYdX and Bybit
Live examples
=> Implement _subscribe_instrument for dYdX and Bybit

nautilus_trader/adapters/interactive_brokers/client/account.py, nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/common.py, nautilus_trader/adapters/interactive_brokers/client/connection.py, nautilus_trader/adapters/interactive_brokers/client/contract.py, nautilus_trader/adapters/interactive_brokers/client/error.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/adapters/interactive_brokers/client/order.py, nautilus_trader/adapters/interactive_brokers/client/wrapper.py, nautilus_trader/adapters/interactive_brokers/config.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/execution.py, nautilus_trader/adapters/interactive_brokers/factories.py, nautilus_trader/adapters/interactive_brokers/gateway.py, nautilus_trader/adapters/interactive_brokers/historical/client.py, nautilus_trader/adapters/interactive_brokers/parsing/data.py, nautilus_trader/adapters/interactive_brokers/parsing/instruments.py, nautilus_trader/adapters/interactive_brokers/providers.py, nautilus_trader/adapters/interactive_brokers/web.py
Refine formatting for readability in files related to the IB adapter. This commit only contains new line changes.
=> Refine formatting of IB adapter files

crates/common/src/ffi/mod.rs, crates/common/src/msgbus/mod.rs, crates/core/src/ffi/string.rs, nautilus_trader/common/component.pxd, nautilus_trader/common/component.pyx, nautilus_trader/core/includes/common.h, nautilus_trader/core/rust/common.pxd, tests/performance_tests/test_perf_msgbus.py
Use fast matching logic in Cython through ffi
#2634
=> Use faster message bus pattern matching logic from Rust

nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_engine.py
Add bars from request_aggregated_bars to cache
- New feature (non-breaking)
=> Add bars from request_aggregated_bars to cache

nautilus_trader/serialization/base.pyx, tests/unit_tests/serialization/test_msgpack.py
Add missing serialisation mappings for some instruments, for Commodity, CryptoOption, IndexInstrument
=> Add missing serialization mappings for some instruments

nautilus_trader/live/execution_engine.py, tests/unit_tests/live/test_execution_recon.py
=> Fix fill reconciliation when discrepancy with redis cache

nautilus_trader/adapters/interactive_brokers/client/client.py
Restore task error logging removed in #2710. I removed a bit too much.
https://github.com/nautechsystems/nautilus_trader/pull/2710
=> Restore task error logs for IBKR 

nautilus_trader/backtest/config.py, nautilus_trader/persistence/catalog/parquet.py, nautilus_trader/persistence/funcs.py, tests/unit_tests/persistence/test_consolidate_by_period.py, tests/unit_tests/persistence/test_funcs.py
=> Add consolidate catalog by period

docs/api_reference/adapters/interactive_brokers.md, docs/integrations/ib.md
=> Update IB adapter documentation

nautilus_trader/adapters/interactive_brokers/client/wrapper.py, nautilus_trader/adapters/interactive_brokers/common.py
Add hidden order support for IBKR
Tested in live.
=> Add hidden order support for IBKR

nautilus_trader/backtest/node.py, nautilus_trader/data/engine.pyx
=> Avoid catalog queries with BacktestNode.download_data

nautilus_trader/adapters/bybit/websocket/client.py
Fix incorrect error parsing for Bybit
- Bug fix (non-breaking)
Live testing
=> Fix Bybit Unknown Error

crates/persistence/src/backend/catalog_operations.rs, crates/persistence/src/python/catalog.rs, crates/persistence/tests/test_catalog.rs, docs/concepts/data.md, nautilus_trader/core/nautilus_pyo3.pyi, nautilus_trader/persistence/catalog/parquet.py, tests/unit_tests/persistence/test_catalog.py, tests/unit_tests/persistence/test_catalog_pyo3.py
=> Add delete data range to catalog

crates/persistence/src/backend/catalog.rs, crates/persistence/src/backend/catalog_operations.rs, crates/persistence/src/parquet.rs, crates/persistence/tests/test_catalog.rs
Attemp to improve path handling in rust catalog for fixing tests in windows. Code improvement but requires more work in windows for fixing the issue.
=> Refine Rust catalog path handling

examples/backtest/notebooks/databento_backtest_with_data_client.py, nautilus_trader/adapters/databento/data.py
Also fix bug in databento_backtest_with_data_client.py example
=> Fix end date in some databento request functions

crates/common/examples/greeks_actor_example.rs, crates/common/src/greeks.rs, nautilus_trader/model/greeks.pyx
=> Add greeks_filter function to portfolio_greeks

Makefile
Can be useful to reduce token consumption from LLMs
=> Add VERBOSE option to common make functions

crates/common/src/greeks.rs
- Add builder methods for rust instrument_greeks and portfolio_greeks methods
=> Refine Rust GreeksCalculator

examples/backtest/notebooks/databento_test_request_bars.py, nautilus_trader/backtest/node.py
=> Improve databento_test_request_bars example

docs/concepts/data.md, nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/common.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_market_data.py
- Add timeout for publishing bar after a small delay (1 second) when no new partial bar is received for the next period
=> Fix IB EOD bar

tests/integration_tests/adapters/dydx/test_data_client_bars.py
This PR introduces a full test-suite that validates the new bar-partitioning logic used by `DYDXDataClient` to fetch large spans of historical data safely and efficiently.
**Key points**
* **Partitioning boundaries** – verifies when requests should/shouldn’t be split across multiple HTTP calls.
* **Time-frame coverage** – checks minute, 5-minute, 15-minute, hourly, 4-hour and daily bar calculations.
* **Chunk sizing** – asserts correct chunk counts for 1 000–3 000 bar ranges.
* **Partial-bar handling** – guarantees that incomplete candles are excluded yet still returned separately.
* **Error resilience** – simulates API failures and rate-limiting delays to ensure graceful degradation.
* **Limit enforcement** – confirms global `limit` is honored across all partitions.
=> Add integration tests for dYdX bar-partitioning and large-history handling

examples/backtest/notebooks/databento_option_greeks.py, nautilus_trader/backtest/engine.pxd, nautilus_trader/backtest/engine.pyx, tests/acceptance_tests/test_backtest.py, tests/unit_tests/backtest/test_data_iterator.py, tests/unit_tests/backtest/test_engine.py
=> Refactor BacktestDataIterator

crates/adapters/blockchain/bin/node_test.rs, crates/adapters/blockchain/src/cache/database.rs, crates/adapters/blockchain/src/cache/mod.rs, crates/adapters/blockchain/src/cache/rows.rs, crates/adapters/blockchain/src/contracts/base.rs, crates/adapters/blockchain/src/contracts/erc20.rs, crates/adapters/blockchain/src/contracts/mod.rs, crates/adapters/blockchain/src/data.rs, crates/adapters/blockchain/src/reporting.rs, crates/adapters/blockchain/src/rpc/http.rs, crates/common/src/actor/tests.rs, crates/common/src/cache/tests.rs, crates/common/src/python/actor.rs, crates/data/tests/engine.rs, crates/model/src/defi/amm.rs, crates/model/src/python/defi/types.rs
- Implements `Multicall` contract functionality via new base contract module (`contracts/base.rs`) to batch multiple calls into single RPC request
- Integrates pool caching into sync process with database methods for insert/update operations
- Updates `Pool` definition to use `SharedDex` type for better memory management and thread safety
- Enhances ERC20 contract error handling with robust fallbacks for `TokenInfo` retrieval
- Refactors `sync_exchange_pools` to eliminate duplication and handle empty tokens
- Refined Blockchain sync reporter
=> Improve DEX pool sync process in the blockchain adapter

docs/developer_guide/rust.md, examples/other/debugging/debug_mixed_jupyter.ipynb, nautilus_trader/test_kit/debug_helpers.py
=> Add mixed debugging instructions and example

examples/live/interactive_brokers/with_databento_instrument_id.py, nautilus_trader/adapters/interactive_brokers/data.py, nautilus_trader/adapters/interactive_brokers/providers.py
=> Add loading of options chain from request_instruments with IB

nautilus_trader/adapters/polymarket/scripts/set_allowances.py
Adjusts web3 usage so it's compatible with the latest version (7.21.1) that brought many breaking changes.
I tested it locally and all transactions were successful.
=> Upgrade web3 for Polymarket allowances script

docs/concepts/data.md
=> Update request_aggregated_bars example

nautilus_trader/common/actor.pxd, nautilus_trader/common/actor.pyx, nautilus_trader/data/client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_engine.py
=> Allow several instrument versions with request_instrument

docs/integrations/ib.md
=> Update IB documentation

nautilus_trader/analysis/reporter.py, nautilus_trader/trading/trader.py, tests/unit_tests/analysis/test_reports.py
Enhance positions report to mark snapshots
**Please review the test carefully.** I am not confident, I haven't introduced a test, which will start failing in future due to not being "realistic enough".
=> Enhance positions report to mark snapshots

examples/backtest/notebooks/databento_backtest_with_data_client.py, examples/backtest/notebooks/databento_download.py, examples/backtest/notebooks/databento_option_greeks.py, examples/backtest/notebooks/databento_test_request_bars.py, examples/live/databento/databento_historical_data.py, examples/live/interactive_brokers/notebooks/run_ratio_spread_1x2_qty3.py, examples/live/interactive_brokers/notebooks/with_databento_instrument_id.py, nautilus_trader/backtest/data_client.pxd, nautilus_trader/backtest/data_client.pyx, nautilus_trader/backtest/node.py, nautilus_trader/common/actor.pyx, nautilus_trader/data/aggregation.pxd, nautilus_trader/data/aggregation.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, nautilus_trader/model/greeks.pyx, nautilus_trader/model/instruments/base.pyx, nautilus_trader/model/instruments/option_spread.pyx, nautilus_trader/model/tick_scheme/implementations/fixed.pyx, nautilus_trader/model/tick_scheme/implementations/tiered.pyx, nautilus_trader/persistence/writer.py, tests/unit_tests/backtest/test_data_client.py, tests/unit_tests/data/test_aggregation.py, tests/unit_tests/persistence/test_streaming.py
=> Add support for option spread quotes in backtest

nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/adapters/interactive_brokers/data.py, tests/integration_tests/adapters/interactive_brokers/client/test_client_market_data.py
Request past bars when subscribing only from the end of a catalog if available.
=> Refine subscribe_bars in IB adapter

nautilus_trader/adapters/interactive_brokers/execution.py
https://github.com/nautechsystems/nautilus_trader/issues/2890
=> Fix IB submit_order_list

nautilus_trader/backtest/data_client.pxd, nautilus_trader/backtest/data_client.pyx, nautilus_trader/data/engine.pxd, nautilus_trader/data/engine.pyx, tests/unit_tests/data/test_engine.py
Moved management of spread quote aggregators from data engine to BacktestMarketDataClient.
=> Refactor SpreadQuoteAggregator

Cargo.lock, crates/adapters/hyperliquid/Cargo.toml, crates/adapters/hyperliquid/src/common/consts.rs, crates/adapters/hyperliquid/src/common/credential.rs, crates/adapters/hyperliquid/src/common/enums.rs, crates/adapters/hyperliquid/src/common/mod.rs, crates/adapters/hyperliquid/src/common/parse.rs, crates/adapters/hyperliquid/src/common/types.rs, crates/adapters/hyperliquid/src/http/error.rs, crates/adapters/hyperliquid/src/http/models.rs, crates/adapters/hyperliquid/src/http/query.rs, crates/adapters/hyperliquid/src/lib.rs, crates/adapters/hyperliquid/src/websocket/enums.rs, crates/adapters/hyperliquid/src/websocket/messages.rs
Add common & secrets layer with network config, credential handling, trading enums, lossless decimals, error taxonomy, HTTP models, WebSocket messages, and 46 tests following existing patterns.
=> Implement initial Hyperliquid adapter

examples/backtest/notebooks/databento_option_greeks.py, nautilus_trader/backtest/option_exercise.pxd, nautilus_trader/backtest/option_exercise.pyx, tests/unit_tests/backtest/test_option_exercise.py
Simulation module to physically exercise options or close them properly at expiry (cash settlement for ITM index options or closing an  OTM option to realise pnl).
=> Add OptionExerciseModule

Cargo.toml, crates/adapters/hyperliquid/src/http/models.rs, crates/adapters/hyperliquid/src/lib.rs, crates/adapters/hyperliquid/src/signing/mod.rs, crates/adapters/hyperliquid/src/signing/nonce.rs, crates/adapters/hyperliquid/src/signing/signers.rs, crates/adapters/hyperliquid/src/signing/types.rs
- Add signing module with EIP-712 signer for L1 and user actions
- Implement thread-safe nonce management with replay protection
- Add action canonicalization for Hyperliquid protocol
=> Implement Hyperliquid EIP-712 signing and nonce management

examples/backtest/notebooks/databento_test_request_bars.py, examples/live/interactive_brokers/notebooks/run_ratio_spread_1x2_qty3.py, examples/live/interactive_brokers/notebooks/test_bracket_order.py, examples/live/interactive_brokers/notebooks/test_oca_group.py, examples/live/interactive_brokers/notebooks/with_databento_instrument_id.py, nautilus_trader/adapters/interactive_brokers/execution.py, tests/integration_tests/adapters/interactive_brokers/test_execution_order_transform.py
- Disable automatic creation of OCA group for bracket orders
- Refactor handling of IB order tags
https://github.com/nautechsystems/nautilus_trader/issues/2978
=> Fix Interactive Brokers modify bracket order

docs/integrations/ib.md, examples/live/interactive_brokers/notebooks/test_simple_conditions.py, nautilus_trader/adapters/interactive_brokers/common.py, nautilus_trader/adapters/interactive_brokers/execution.py, tests/integration_tests/adapters/interactive_brokers/test_execution_order_transform.py
- Add possibility of conditional orders in IB
- Update IB documentation
- Add tests
- Add live example testing all conditions and it works with IB
=> Add Interactive Brokers order conditions

nautilus_trader/adapters/interactive_brokers/client/order.py, nautilus_trader/adapters/interactive_brokers/client/wrapper.py, nautilus_trader/adapters/interactive_brokers/execution.py
Tested it works with a live node and IB
=> Implement Interactive Brokers generate_fill_reports

crates/adapters/hyperliquid/src/data/mod.rs, crates/adapters/hyperliquid/src/websocket/mod.rs
Related to: https://github.com/nautechsystems/nautilus_trader/issues/2981
=> Implement Hyperliquid DataClient in Rust

nautilus_trader/adapters/hyperliquid/execution.py
Related to: https://github.com/nautechsystems/nautilus_trader/issues/2981
=> Implement Hyperliquid ExecutionClient in Python

nautilus_trader/adapters/interactive_brokers/client/client.py, nautilus_trader/adapters/interactive_brokers/client/common.py, nautilus_trader/adapters/interactive_brokers/client/market_data.py, nautilus_trader/adapters/interactive_brokers/data.py
=> Refine filtering of bars in IB adapter after disconnection

crates/adapters/hyperliquid/bin/http_private.rs, crates/adapters/hyperliquid/src/common/consts.rs, crates/adapters/hyperliquid/src/common/converters.rs, crates/adapters/hyperliquid/src/common/enums.rs, crates/adapters/hyperliquid/src/common/mod.rs, crates/adapters/hyperliquid/src/common/parse.rs, crates/adapters/hyperliquid/src/execution/mod.rs, crates/adapters/hyperliquid/src/http/models.rs, crates/adapters/hyperliquid/src/python/enums.rs, crates/adapters/hyperliquid/src/python/mod.rs, crates/adapters/hyperliquid/src/websocket/messages.rs
Related: https://github.com/nautechsystems/nautilus_trader/issues/2981
=> Implement Hyperliquid conditional / advanced orders

Cargo.lock, Cargo.toml, crates/adapters/hyperliquid/Cargo.toml, crates/adapters/hyperliquid/bin/ws_exec.rs, crates/adapters/hyperliquid/bin/ws_post.rs, crates/adapters/hyperliquid/src/common/parse.rs, crates/adapters/hyperliquid/src/data/mod.rs, crates/adapters/hyperliquid/src/execution/mod.rs, crates/adapters/hyperliquid/src/http/client.rs, crates/adapters/hyperliquid/src/http/error.rs, crates/adapters/hyperliquid/src/http/models.rs, crates/adapters/hyperliquid/src/http/parse.rs, crates/adapters/hyperliquid/src/http/query.rs, crates/adapters/hyperliquid/src/signing/signers.rs, crates/adapters/hyperliquid/src/websocket/client.rs, crates/adapters/hyperliquid/src/websocket/messages.rs, crates/adapters/hyperliquid/src/websocket/post.rs, crates/execution/src/client/base.rs, crates/model/src/defi/dex.rs, examples/live/hyperliquid/hyperliquid_data_tester.py, examples/live/hyperliquid/hyperliquid_exec_tester.py
Related: https://github.com/nautechsystems/nautilus_trader/issues/2981
=>  Implement Hyperliquid execution reconciliation
